### ISSUE TITLE
Add submit transaction mutation

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-graphql#10]

**Comment by rhyslbw** [comment]
Forward request to https://github.com/input-output-hk/cardano-explorer/tree/master/cardano-tx-submit

**Comment by rhyslbw** [comment]
Repo now at https://github.com/input-output-hk/cardano-rest/tree/master/tx-submit

**Comment by roccomuso** [comment]
Does this project expose an API to submit a tx?

**Comment by rhyslbw** [comment]
Not yet, but it's planned

**Comment by roccomuso** [comment]
Will this be ready before Shelley launch?
It will avoid the hassle of spawning cardano-rest just to broadcast a tx.

**Comment by SebastienGllmt** [comment]
@roccomuso yes, that's the plan

**Comment by rhyslbw** [comment]
It's in progress now. First step was a refactor (#200) to establish a pattern of composition, as not every instance needs this API segment.

**Comment by islishude** [comment]
hi,any updates?

**Comment by rhyslbw** [comment]
@islishude 
At this stage the suggestion is to use [cardano-wallet](https://github.com/input-output-hk/cardano-wallet) with the [postExternalTransaction](https://input-output-hk.github.io/cardano-wallet/api/edge/#operation/postExternalTransaction) endpoint.

**Comment by islishude** [comment]
yes,I'm using cardano-wallet for submitting transactions at now
