### ISSUE TITLE
Improve docker-compose examples to use Docker secrets for credentials passed to Hasura

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-graphql#120]
Waiting for https://github.com/hasura/graphql-engine/issues/3989

**Comment by AlanVerbner** [comment]
@rhyslbw as temp workaround what do you think about creating a new image based on `hasura/graphql-engine` one (using `FROM`) but with a modified `CMD` with a custom entrypoint script?

The main problem I see is that a specific version version needs to be configured when extending _but_ I think the proper version to be picked should be stated in the `README` anyways.

**Comment by rhyslbw** [comment]
Hi @AlanVerbner , apologies for the delay.

We originally had an extended image while prototyping, but it was abandoned due to seemingly unnecessary complexity. Having worked with both, I can see there is value, not just in this particular issue, but also to remove the need for the source code to provide the metadata.

Thanks, I'll update this when it's available.

**Comment by AlanVerbner** [comment]
Thanks @rhyslbw for the answer. If you need some help I could try to implement this and create a PR. Just let me know if you are not already working on it.

**Comment by rhyslbw** [comment]
Thanks @AlanVerbner. It's not something I'm working on right now, so would be happy to collaborate on this.
