### ISSUE TITLE
Transaction outputs should be ordered by their on-chain index

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/cardano-graphql#139]
An example for the transaction `a3fb04b5e04be5ee317cf1a60905c51a69c0dba8e9dd974689aa6c5209b844b3` on the testnet:

![Screenshot from 2020-04-14 14-46-30](https://user-images.githubusercontent.com/5680256/79227112-b6aceb00-7e5f-11ea-8a3c-ca6b7d966aa7.png)

There's no reason to order things differently and it's actually quite confusing (as a reader, I'd expect the first output shown to correspond to the 1st output of the transaction, the second to the 2nd etc..

**Comment by rhyslbw** [comment]
Default should be `index`. Will resolve as priority
