### ISSUE TITLE
Another noob error running yarn start ....?

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-graphql#144]
Actions
----------
1. Cloned repo
2. Went to home directory of repo
3. Ran command _yarn_  (no error)
4. Ran command _yarn start_

Expected Behavior
------------------
No error when running _yarn start_

Actual Behaviour
-------------------
Got error
_yarn run v1.22.4
error Command "start" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command._

Additional Behavior
------------------------
- Am using node v10.19.0 and yarn 1.22.4 
- package.json file in directory where i run commands
- package.json matches what's in the repo 
- _yarn run_ does not indicate _start_ is an option
- Will keep trying to work this out and update ticket if i find a solution

**Comment by SebastienGllmt** [comment]
This project doesn't have a `start` script. Maybe you want `yarn dev`

**Comment by rhyslbw** [comment]
I'm working on better docs and supporting material now @gmanroney, including an interface to run example queries using our deployed instance without needing to install and sync a local node. The latter can be achieved however by setting up some secrets, and running `docker-compose up`. I will add a `start` script that will simply map to that command.

Thanks @SebastienGllmt for jumping in on this. `yarn dev` is only useful during development

**Comment by rhyslbw** [comment]
FWIW, there is now a [start script](https://github.com/input-output-hk/cardano-graphql/blob/master/package.json#L18), however it only starts the HTTP server, and expects the dependencies to already be running
