### ISSUE TITLE
Error when creating environment for first time

### ISSUE THREAD

**Issue by gmanroney** [input-output-hk/cardano-graphql#154]
Run command "NETWORK=testnet docker-compose up"

Get following output

[3/4] Linking dependencies...
warning " > graphql-type-datetime@0.2.4" has incorrect peer dependency "graphql@^0.13.2".
warning " > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > @typescript-eslint/parser@1.13.0" has incorrect peer dependency "eslint@^5.0.0".
[4/4] Building fresh packages...

.....

Creating cardano-graphql_postgres_1        ... error
Creating cardano-graphql_cardano-graphql_1 ... done
Creating cardano-graphql_cardano-node_1    ... done
ql/config/secrets/postgres_db

ERROR: for postgres  Cannot create container for service postgres: invalid mount config for type "bind": bind source path does not exist: <path>/cardano-graphql/config/secrets/postgres_db
ERROR: Encountered errors while bringing up the project.

There are NO docker images or containers on my server; not sure why it keeps giving this error

Any ideas?

**Comment by ArturWieczorek** [comment]
@gmanroney Have you removed the `example` suffix from files in: https://github.com/input-output-hk/cardano-graphql/tree/master/config/secrets

**Comment by gmanroney** [comment]
hi there - did not do that - done it now. 
it went much further but now getting the following repeating error


_cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:65] [2020-04-25 22:50:26.58 UTC] {"event":"Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (No such file or directory)","kind":"SubscriptionTrace"}
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2020-04-25 22:50:26.59 UTC] {"event":"ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 12>: does not exist (No such file or directory))) 20s 20s","kind":"ErrorPolicyTrace","address":"LocalAddress {getFilePath = \"/node-ipc/node.socket\"}"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:34] [2020-04-25 22:50:26.61 UTC] {"event":"Failed to start all required subscriptions","kind":"SubscriptionTrace"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:34] [2020-04-25 22:50:27.61 UTC] {"event":"Restarting Subscription after 1.027482732s desired valency 1 current valency 0","kind":"SubscriptionTrace"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:34] [2020-04-25 22:50:36.59 UTC] {"event":"Starting Subscription Worker, valency 1","kind":"SubscriptionTrace"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:67] [2020-04-25 22:50:36.59 UTC] {"event":"Connection Attempt Start, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"}","kind":"SubscriptionTrace"}_

I will clear my environment and retry again in the morning

thanks for your help @ArturWieczorek

**Comment by gmanroney** [comment]
i did the following:
_docker-compose down -v_
then 
_docker-compose up -d_
and it worked. must have had some incomplete data from a previous run that affected its operation. 
the command:
 _NETWORK=testnet docker-compose up_
did not work. don't know why.

i think some mods to the documentation needed so this is a smooth process for any one who comes to this site 'cold' in future.

**Comment by rhyslbw** [comment]
The node socket is [created in a volume](https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L25), that's also [mounted](https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L43) in the `cardano-db-sync-extended` container. This means that it's persisted across complete rebuilds of the stack, except when volumes are explicitly removed (`-v`). The only time I've hit an issue here is when the container structure changed, so the executables expect a different path . Do you remember when you first attempted to start the stack? 

> i think some mods to the documentation needed so this is a smooth process for any one who comes to this site 'cold' in future.

The [Wiki](https://github.com/input-output-hk/cardano-graphql/wiki/Docker) now has more information @gmanroney, but there's certainly a few areas we can smooth out. In particular I think making the `docker-compose.json` load the example secrets would allow the stack to be demonstrated without manually creating them.
