### ISSUE TITLE
is there a public API server?

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-graphql#155]

**Comment by rhyslbw** [comment]
Not currently, but you're welcome to use the development deployments in the interim: 
- https://cardano-graphql-mainnet.daedalus-operations.com/
- https://cardano-graphql-testnet.daedalus-operations.com/

**Comment by gshohat** [comment]
Both serves can't be reached:
https://cardano-graphql-mainnet.daedalus-operations.com/
https://cardano-graphql-testnet.daedalus-operations.com/

Are there other dev servers we can use at the meantime?
10x

**Comment by rhyslbw** [comment]
Those instances have been terminated @gshohat as we're encouraging the adoption of local or self-hosted instances currently.
