### ISSUE TITLE
Investigate why address details can't be displayed

### ISSUE THREAD

**Issue by ArturWieczorek** [input-output-hk/cardano-graphql#158]
I can't display address details for this particular address in the new explorer: 

**Address**: `DdzFFzCqrhstmqBkaU98vdHu6PdqjqotmgudToWYEeRmQKDrn4cAgGv9EZKtu1DevLrMA1pdVazufUCK4zhFkUcQZ5Gm88mVHnrwmXvT`

**Steps to reproduce**:
- Go to the explorer and search for transaction: txId=`3d0d3cde783d20a4efc6b0bde36b32aef86a3a34bae1f43d64a25117574983eb` 
- Find address mentioned above - it should be located at the bottom of addresses list on the left side 

-  Try to click on it to display its details - it will not work

**REST API** returns results (after few seconds) :
https://explorer.cardano.org/api-new/addresses/summary/DdzFFzCqrhstmqBkaU98vdHu6PdqjqotmgudToWYEeRmQKDrn4cAgGv9EZKtu1DevLrMA1pdVazufUCK4zhFkUcQZ5Gm88mVHnrwmXvT

**Additional info**:
> John Lotoski
> that address is one of the busiest addresses available.  It had > 55k Txs as of July 2019.  It's likely timing out in the postgres query.
>

**Comment by rhyslbw** [comment]
@ArturWieczorek Please test this against https://input-output-hk.github.io/cardano-rest/explorer-api/ too

**Comment by rhyslbw** [comment]
... or is that the service running at `api-new` ?

**Comment by disassembler** [comment]
that service is running at api-new

**Comment by disassembler** [comment]
That endpoint returns a 314 MB file!

**Comment by disassembler** [comment]
There are 130,384 transactions associated with that address.

**Comment by ArturWieczorek** [comment]
Sorry, I forgot to post a comment here with an update but I informed Rhys in DM on Slack last week about it's size:

> cardano-rest$ ll --block-size=MB
> drwxr-xr-x  9 artur artur   1MB Apr 29 23:42 ./
> drwxrwxr-x 11 artur artur   1MB Apr 29 20:01 ../
> -rw-r--r--  1 artur artur   1MB Apr 29 19:52 bors.toml
> drwxr-xr-x  2 artur artur   1MB Apr 29 19:52 .buildkite/
> -rw-r--r--  1 artur artur   1MB Apr 29 19:52 cabal.project
> -rw-r--r--  1 artur artur 324MB Apr 29 23:42 cardano_rest_response_for_addresses_summary.json
