### ISSUE TITLE
Mismatched TransactionInput.index

### ISSUE THREAD

**Issue by neville-freeman** [input-output-hk/cardano-graphql#182]
While running the following query:

```
curl --location --request POST ‘http://xxx:xxx’ \
--header ‘Content-Type: application/json’ \
--data-raw ‘{
   “query”:
   “{blocks(where:{number:{_in:[4207825]}}){epochNo,number,id,slotWithinEpoch,createdAt,previousBlock { id },transactions { id,fee,inputs(order_by:{index:asc}){sourceTxId,sourceTxIndex,address,index,value} } } }”
}’
```
we found the index is not added in order (see attached)

![image (4)](https://user-images.githubusercontent.com/42548310/82880977-0094f080-9f37-11ea-8214-6a20558e62ce.png)

is that index equal to sourceTxIndex?

**Comment by rhyslbw** [comment]
Yes, the index is currently invalid. I've added tests to reveal this, but the resolution is dependent on https://github.com/input-output-hk/cardano-db-sync/issues/106
