### ISSUE TITLE
Transactions always returning different response

### ISSUE THREAD

**Issue by segersniels** [input-output-hk/cardano-graphql#191]
After searching for a public facing API I encountered the following endpoint which was given in one of the issues: `https://cardano-graphql-mainnet.daedalus-operations.com/graphql`.

I've been trying to fetch the transactions of a specific address with the following query:
```
gql`
    query getAddressTransactions($address: String!) {
      transactions(
        where: {
          _or: [
            { inputs: { address: { _eq: $address } } }
            { outputs: { address: { _eq: $address } } }
          ]
        }
      ) {
        block {
          epochNo
          number
          slotWithinEpoch
        }
        hash
        includedAt
        inputs {
          address
          sourceTxHash
          value
        }
        outputs {
          address
          index
          value
        }
        totalOutput
      }
    }
  `
```

Unfortunately every response I get is different from the last one with transactions missing in one and then others in another. Is this intentional for the endpoint I'm using and is it only for development purposes? If so, is there another endpoint that actually makes sense and returns what I need?

Also, I was getting some responses from the API `https://explorer.cardano.org/` is using, using  curl. But whenever I tried moving them to apollo-client I started getting `Forbidden` errors.

**Comment by rhyslbw** [comment]
The instance at https://cardano-graphql-mainnet.daedalus-operations.com/graphql is a standard deployment used internally, but should not be relied upon. 

To ensure the order of return is consistent across calls, you need to pass an `order_by` argument. Have a look at the ` Transaction_order_by` type
