### ISSUE TITLE
Block.slotWithinEpoch is incorrect for shelley

### ISSUE THREAD

**Issue by disassembler** [input-output-hk/cardano-graphql#194]
the `slotWithinEpoch` is calculated by `block.slot_no - (block.epoch_no * (10 * (select protocol_const from meta)))` This doesn't account for `f` and could be simplified to just `block.slot_no % meta.slots_per_epoch`

**Comment by rhyslbw** [comment]
Thanks @disassembler. This meta column was added in https://github.com/input-output-hk/cardano-db-sync/commit/388226d64347322b5238473d09c203816b89786a, so support for this will require targeting a pre-release version of the dep
