### ISSUE TITLE
Migration for slots_per_epoch is failing

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/cardano-graphql#216]
During update to the new version following error about migrations occurs:

<img width="1071" alt="Screenshot 2020-07-07 at 0 37 08" src="https://user-images.githubusercontent.com/58727428/86649392-62428300-bfea-11ea-8f2b-36acc0496c15.png">

cardano-db-sync-extended container just hangs in the restart loop, and I have no idea how to access /tmp/migrate-***.log in a dead container for more information.

**Comment by rhyslbw** [comment]
Has the `postgres-data` been removed and recreated? Please see the [release notes](https://github.com/input-output-hk/cardano-graphql/releases/tag/v1.0.0-rc.13), where I've linked to a new section in the Wiki regarding this action. Feel free to re-open if you are still stuck
