### ISSUE TITLE
The latest stable 1.0.0 release is erroring out Unexpected token " in JSON at position 0

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-graphql#222]
### Environment

``` console
npx @cardano-graphql/cli system-info
```
{ os:
   { arch: 'x64',
     cpus:
      { count: 8,
        model: 'Intel(R) Xeon(R) Platinum 8175M CPU @ 2.50GHz' },
     release: '4.14.181-142.260.amzn2.x86_64',
     totalMem: 66714206208,
     type: 'Linux' },
  version: '1.0.0' }

#### Platform
docker image in k8s

#### Runtime

- [ ] Node.js
- [v] Docker

**Runtime version**: 
19.06.x

### Steps to reproduce the bug

The moment I start `cardano-graphql` I get
```
SyntaxError: Unexpected token " in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (/application/node_modules/body-parser/lib/types/json.js:158:10)
    at parse (/application/node_modules/body-parser/lib/types/json.js:83:15)
    at /application/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/application/node_modules/raw-body/index.js:224:16)
    at done (/application/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/application/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

And it's in loop. 

### What is the expected behavior?

No logs, as nothing is connecting to the endpoint

**Comment by rhyslbw** [comment]
I've just added issue templates to better assist with support @ksemaev . Would you mind patching this issue using the markdown from https://github.com/input-output-hk/cardano-graphql/issues/new?template=bug.md ?

**Comment by ksemaev** [comment]
Done, please take a look. Although it doesn't cause any problems AFAIK

**Comment by rhyslbw** [comment]
I can't reproduce this, however the error is indicating a malformed client request (`body-parser` extracts the query from the HTTP request). Do you have a client immediately calling the API? Maybe try [master](https://hub.docker.com/layers/inputoutput/cardano-graphql/master/images/sha256-f3b65d22450db914614417d528b0b061e63d244b38fb4a1e6c21e33d4205b69a?context=repo) to see if there's any difference, and reopen if you can provide a way for me to reproduce this in isolation.
