### ISSUE TITLE
Place /genesis dir in docker image

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-graphql#260]
Is it possible to build inputoutput/cardano-graphql with contents of https://github.com/input-output-hk/cardano-graphql/tree/master/config/network/mainnet/genesis so we won't have to map them separately or to build a new layer please?

**Comment by rhyslbw** [comment]
Yes good idea, I'll come up with a solution using stages. Can also load the default config, which can then be mounted over to customise
