### ISSUE TITLE
Current 2.0.0 Beta Release can't start with db-sync v3.1.1 working

### ISSUE THREAD

**Issue by ksemaev** [input-output-hk/cardano-graphql#263]
After the start `graphql` just does 10 attempts of ```Applying PostgreSQL schema and Hasura metadata: Attempt 7 of 10, retying..``` and exits. I suspect this is because db-sync is writing to PG at the moment. 

We need either to add this part to the db-sync, or mention in requirements that `graphql` needs exclusive access for first start.

**Comment by ksemaev** [comment]
Have no idea why it's hapenning, I left only graphql app running and see the same attempts loop. We need some error trace in logs

**Comment by rhyslbw** [comment]
It's not a requirement, the system is intended to be resilient to start order. You're actually on an [incompatible version pair](https://github.com/input-output-hk/cardano-graphql/releases/tag/2.0.0-beta.0) there, so the result is expected.

Good news is `2.0.0` is out! :tada:  Please stick to the strict pairings as per the release notes https://github.com/input-output-hk/cardano-graphql/releases/tag/2.0.0

**Comment by ksemaev** [comment]
TY! I still believe we need to improve logging to see the reason for the failed attempt

**Comment by ksemaev** [comment]
@rhyslbw I've just started a completely separate setup with coin-node inputoutput/cardano-node:1.18.0, db-sync inputoutput/cardano-db-sync:3.1.0, graphql inputoutput/cardano-graphql:2.0.0, hasura inputoutput/cardano-graphql-hasura:2.0.0

And I still see the same loop ```Applying PostgreSQL schema and Hasura metadata: Attempt 8 of 10, retying...```
Please advice

**Comment by rhyslbw** [comment]
Try the dev setup:
1. fresh clone of the repo
2. yarn mainnet:up

**Comment by ksemaev** [comment]
It started working with full root permissions (had used a user with restricted access), TY

**Comment by rhyslbw** [comment]
The startup logging and error handling needs work. Glad you got up and running
