### ISSUE TITLE
What's the difference between `number` and `slotNo`?

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-graphql#264]

**Comment by rhyslbw** [comment]
@islishude 
Slots are a measure of time in the blockchain, and can be determined with knowledge of the genesis parameters. Blocks are created _within_ a slot window, but the sequence is established through an identifying `Block.number`. During the Byron era, each slot was expected to be filled, although not all were, so it has been a slightly confusing concept. The new protocol however only expects a block to be forged within a range of slots, so you will see a significant difference.

Check out the first post-Byron epoch to help visualise this https://explorer.cardano.org/en

Feel free to reopen if you need further clarification, or advice on which to use in your application.
