### ISSUE TITLE
Wrong name "Hash32HexString"

### ISSUE THREAD

**Issue by SebastienGllmt** [input-output-hk/cardano-graphql#271]
The name `Hash32HexString` shows up in many places despite many of these hashes actually being hash28. Presumably this was caused by many of these hashes previously being 32 until some of them were changed to 28 in the binary spec. Since some hashes are 28 and some hashes are 32, it may be simpler to just rename this to not include the length in the name (or you can create a "Hash28" type)

**Comment by rhyslbw** [comment]
Yes the opportunity to generalise the label of this scalar to `Hash` was missed at the `2.0.0` release. We'll consider the best approach to correct this once [CIP5 ](https://github.com/cardano-foundation/CIPs/pull/6) lands.
