### ISSUE TITLE
Not more than 100 inputs per transaction can be returned

### ISSUE THREAD

**Issue by quyse** [input-output-hk/cardano-graphql#276]
It seems that number of inputs returned per transaction is capped at 100, even if `limit` is set to a bigger value.

Example query (for mainnet, reproducible with https://cardano-graphql-mainnet.daedalus-operations.com/graphql):
```
{
  transactions(
    where: { hash: {_eq: "ee0d811b75e0fbbd5d2bca9542b37225d2c5a58b8f371953d6494ab48ae3b9f0"}}
  )
    { inputs(limit: 1000)
      { address value sourceTxHash sourceTxIndex }
    }
}
```

Returns just 100 inputs. According to data we exported with `cardano-explorer-api`, this transaction has 344 inputs.

Is it possible to override this limit of 100, to fetch all inputs without issuing multiple queries with pagination? Also it is very confusing that this limit is not mentioned anywhere.

**Comment by SebastienGllmt** [comment]
Yes, we've unfortunately hit the exact same problem at EMURGO and our workaround was to use pagination for some endpoints and just write SQL queries for things where we can't paginate

**Comment by rhyslbw** [comment]
This should just be a documentation issue, as the API allows for pagination via `limit` and `offset`. Which queries or fields are not compatible with this approach @SebastienGllmt ?
