### ISSUE TITLE
search by Hex28String input 

### ISSUE THREAD

**Issue by piyushthapa** [input-output-hk/cardano-graphql#282]
I am trying to search StakePool info  with hash 

```
{
  stakePools(where: {hash: {_eq: "e0337098957416ab539aabdcd59568d81ad56bef6f6e83263f9f9f28"}}){
    hash,
    url,
    pledge,
    margin
  }
}

``` 

```
"message": "Expected type Hash32HexString, found \"e0337098957416ab539aabdcd59568d81ad56bef6f6e83263f9f9f28\"; e0337098957416ab539aabdcd59568d81ad56bef6f6e83263f9f9f28 is not a valid hash",
```

maybe we  need to change  validateInput function  or add new Scalar type?
https://github.com/input-output-hk/cardano-graphql/blob/master/packages/util/src/scalars/Hash32HexString.ts#L21
```
function validateInput (input: string) {
  if (input.length !== 64) throw new GraphQLError(`${input} is not a valid hash`)
  return `\\x${input}`
}
```

Any workaround for this?

**Comment by rhyslbw** [comment]
Hi @piyushthapa. It's fixed in https://github.com/input-output-hk/cardano-graphql/pull/280/files, and should be out this week if a dependent `cardano-db-sync` release is made.
