### ISSUE TITLE
GraphQL startup fails during PostgresSQL schema and Hasura metadata update

### ISSUE THREAD

**Issue by satran004** [input-output-hk/cardano-graphql#283]
Cardano DB Sync version : 4.0.0 , Cardano node: 1.19.0, cardano-graphql-hasura:2.0.0

Cardano-GraphQL - 2.0.0

During Cardano-GraphQL nodejs server startup, it fails with the  error "column delegation.update_id does not exist"
It seems that there is no update_id column in "delegation" table and view creation fails because of that.

While debugging, I found that the update_id was removed from the schema in DB-sync-module in this commit. 
https://github.com/input-output-hk/cardano-db-sync/commit/0b44b29145e01e33d2e131843f675cc464d96264

Is Cardano-GraphQL 2.0.0 compatible with DB Sync 4.0.0 ? 

Error stack: 
----------
Applying PostgreSQL schema and Hasura metadata: Attempt 10 of 10, exiting
Command failed: hasura --skip-update-check --project /application/packages/api-cardano-db-hasura/hasura/project --endpoint http://hasura:80 migrate apply --up all
time="2020-08-23T01:31:12Z" level=fatal msg="apply failed: [postgres-error] query execution failed ($.args[0].args)\r\nFile: '1589369664961_init/up.sql'\r\n{\n    \"check_metadata_consistency\": false,\n    \"sql\": \"CREATE VIEW \\\"Block\\\" 
...
...
(\\n\\t  SELECT stake_address.hash\\n\\t  FROM stake_address\\n\\t  WHERE stake_address.id = withdrawal.addr_id\\n  ) AS \\\"address\\\",\\n  withdrawal.tx_id AS \\\"tx_id\\\"\\nFROM withdrawal;\\n\\nCREATE function utxo_set_at_block(\\\"hash\\\" hash32type)\\nRETURNS SETOF \\\"TransactionOutput\\\" AS $$\\n  SELECT\\n    \\\"TransactionOutput\\\".address,\\n    \\\"TransactionOutput\\\".value,\\n    \\\"TransactionOutput\\\".\\\"txHash\\\",\\n    \\\"TransactionOutput\\\".index\\n  FROM tx\\n  JOIN tx_out\\n    ON tx.id = tx_out.tx_id\\n  JOIN \\\"TransactionOutput\\\"\\n    ON tx.hash = \\\"TransactionOutput\\\".\\\"txHash\\\"\\n  LEFT OUTER JOIN tx_in\\n    ON tx_out.tx_id = tx_in.tx_out_id\\n    AND tx_out.index = tx_in.tx_out_index\\n  WHERE tx_in.tx_in_id IS NULL\\n  AND tx.block \\u003c= (SELECT id FROM block WHERE hash = \\\"hash\\\")\\n$$ LANGUAGE SQL stable;\\n\"\n}\r\n[42703] FatalError: column delegation.update_id does not exist"

**Comment by rhyslbw** [comment]
There will be a release this week targeting `cardano-node@1.19.0` + `cardano-db-sync@4.0.0`
