### ISSUE TITLE
Why my request is so slow?

### ISSUE THREAD

**Issue by alexeirbv** [input-output-hk/cardano-graphql#287]
Hi. I send this request - 

``` graphql
query getTxs($address: String) {
    transactions (
        limit: 20,
        order_by: {
            includedAt: desc
        },
        offset: 0,
        where: {
            outputs: {
                address: {
                    _like: $address
                }
            }
        }) {
        fee
        hash
        inputs {
            address
            sourceTxHash
            sourceTxIndex
            txHash
            value
        }
        outputs {
            address
            index
            txHash
            value
        }
        totalOutput
        size
        inputs_aggregate {
            aggregate {
                sum {
                    value
                }
            }
        }
        outputs_aggregate {
            aggregate {
                sum {
                    value
                }
            }
        }
        blockIndex
        block {
            number
            forgedAt
            slotNo
        }
        includedAt
    }
}
```

```json
{
   "query":"$query",
   "operationName":"getTxs",
   "variables":{
      "address":"DdzFFzCqrhsyjbBTjyyQnELyfbGbu7kfmN3RTwSYmynr3z9sbPn3Xqs6oYfUiD9oYA7uq5TyUgfgVaDJMGWD6hVaiEftfqdZnB5NLRz6"
   }
}
```

It goes reaaaaly slow (about 8-9 secs). My cardano-graphql instance is running on bare-metal server with this specs: 
CPU - Intel(R) Xeon(R) CPU E3-1275 v5 @ 3.60GHz
RAM - 62GB
SSD - 480 NVMe. 

I think this resources more than enough for this query. I also tried to tune my PostgreSQL with PGTune. It didn't helped at all.

**Comment by rhyslbw** [comment]
@alexeirbv I've reformatted your content to present the query as `graphql`. 

I'm getting a 37ms response in my dev env on the `master` branch. Try profiling with `TRACING=true`:

![Screenshot from 2020-09-08 15-11-07](https://user-images.githubusercontent.com/303881/92435450-b255e580-f1e5-11ea-8c46-805cef98f0bd.png)
![Screenshot from 2020-09-08 15-10-50](https://user-images.githubusercontent.com/303881/92435453-b41fa900-f1e5-11ea-8f93-0a28abe18a40.png)

Feel free to re-open if you can reproduce this on `master`
