### ISSUE TITLE
Include the OS, docker and docker-compose versions used in testing for each tag/release.

### ISSUE THREAD

**Issue by TrevorBenson** [input-output-hk/cardano-graphql#289]
I was having issues bringing up cardano-graphql which appeared to tie back to the OS version. I tested on both tag 2.0.0 and Master branch. I went through CentOS 7, Fedora 32 (both with docker-compose and then tried podman-compose), Ubuntu 20.04 and Ubuntu 18.04. Each system was a fresh VM or physical build following the cardano-graphql directions to clone and "compose up". 

Until the Ubuntu 18.04 there was an issue either with image names not being found or errors like some other component being built or the table schema not matching (the newer *_raw fields vs. without being used for inserts)  which I assume was likely the Master branch in the middle of updates when I cloned it. I tried pre pulling the 5 images, modifying the docker-compose.yml to match exact images names since sometimes it had issues finding a match. Each of these failed until I moved to Ubuntu 18.04 and then "compose up" succeeded and the containers worked without generating errors or crashing. 

It seems either the composition file or docker-compose is not very system agnostic, or seems that way if it works on Ubuntu 18.04 but fails on Ubuntu 20.04. Having details about the working environment the compose configuration passes tests for the developer would be beneficial. Especially if the developer transitions to Ubuntu 20.04 (or CentOS/RHEL, Mint, Arch, etc.) and the environment changes. 

I don't mind the effort to modify something to work in an alternate environment as I  prefer using CentOS or RHEL for systems I put into datacenters over Ubuntu anyhow. However knowing where it works without issue can be a great help in that regards or allow one to decide using another OS is not worth the effort and instead stick with the environment it was built on.

Thanks!

**Comment by TrevorBenson** [comment]
I found a stackexchange which references issues with `sudo docker-compose` which is what I was doing on most systems until Ubuntu 18.04 in frustration I just tried it directly as root. The given explanation is about referencing the root of the filesystem in the docker compose configuration, which I do not see in this docker-compose.yml file. I'll give it a few tries and see if I have better results when only running this as root instead of a user with sudo privileges.

The version info could still be useful if someone is running into a bug with docker or docker-compose.

Thanks

**Comment by TrevorBenson** [comment]
Does appear to have been a sudo level issue. I was able to start up on both 18.04 and 20.04 (as 18.04 had an error in logs about the nodejs version mismatch). However now that I have the system up it appears to be stuck at `"syncPercentage": 99.89`, I'll open a bug ticket specific to that. However given that specific nodejs versions are required and error, I still think providing details about the OS version and docker-compose versions would be helpful and save time. I'm going to leave this ticket open and let it be closed when a decision is made to either include these details in the README.md or a response as to why this data won't be included.

Thanks.

Thanks!

**Comment by vae520283995** [comment]
I have the same problem, I'm waiting for the next version
