### ISSUE TITLE
How to change listen host and port localhost:3100

### ISSUE THREAD

**Issue by atomlab** [input-output-hk/cardano-graphql#290]
I need to change `localhost -> 0.0.0.0` and port to `3101`. Which env variables can I use for that?

**Comment by rhyslbw** [comment]
The server already listens on `0.0.0.0`, however I will leave this issue open to make it configurable. You change the port using the [`API_PORT`](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/server/src/config.ts#L88) ENV
