### ISSUE TITLE
Insistence in  addresses in Graphql  API( Delegation and UTXO)

### ISSUE THREAD

**Issue by djalillounis** [input-output-hk/cardano-graphql#310]
#### Platform

- [X] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [X] Docker

### Steps to reproduce the bug

The API return address in format:
``` json
"id": 1,
"address": "\\xe10e5b086df87a2a0c5c398b41d413f84176c527da5e5cb641f4598844"
```

But the UTXO return:
``` json
"address": "DdzFFzCqrhsovkfLD1zPrUrmz8By3NgbByBwBpKn1AKXwREruTMXg29puPMWgV7gR6UrtE6KpY4CuQzmcBwatvnGo5mHmqhtTmsvcy4W",
"value": 454433000000
```
I am building a tool  in python to get some stats of ADA block-chain and I could not find any solution to convert hex address to  bech32 in python 

### What is the expected behavior?

Add the Address ID or the bech32 address to UTXO tables .

**Comment by rhyslbw** [comment]
@djalillounis 
> The API return address in format:

Please provide a specific query to reproduce this
