### ISSUE TITLE
 FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by btbf** [input-output-hk/cardano-graphql#323]
This is the display during synchronization after building with version 2.1.0.
Is this normal?

> postgres_1                  | 2020-09-21 14:56:20.668 UTC [4215] FATAL:  password authentication failed for user "postgres"
postgres_1                  | 2020-09-21 14:56:20.668 UTC [4215] DETAIL:  Password does not match for user "postgres".
postgres_1                  |   Connection matched pg_hba.conf line 95: "host all all all md5"
postgres_1                  | 2020-09-21 14:56:21.368 UTC [4216] FATAL:  password authentication failed for user "postgres"
postgres_1                  | 2020-09-21 14:56:21.368 UTC [4216] DETAIL:  Password does not match for user "postgres".
postgres_1                  |   Connection matched pg_hba.conf line 95: "host all all all md5"

**Comment by rhyslbw** [comment]
Is this a fresh stack? If not, did you [rebuild the database](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db)

**Comment by btbf** [comment]
Yes. It's a fresh stack.
I deleted it a couple of times and started over, but the result is the same.

**Comment by btbf** [comment]
>  docker image list
REPOSITORY                           TAG                        IMAGE ID            CREATED             SIZE
inputoutput/cardano-graphql          2.1.0                      4fa40fc9d04d        14 hours ago        93.7MB
<none>                               <none>                     8e3f79d68114        14 hours ago        41MB
<none>                               <none>                     82d5b88f5f6f        14 hours ago        311MB
<none>                               <none>                     dab1f2a67ae9        14 hours ago        681MB
inputoutput/cardano-graphql-hasura   2.1.0                      a1570134ba12        14 hours ago        123MB
inputoutput/cardano-db-sync          5.0.0                      c0403833fde3        8 days ago          1GB
inputoutput/cardano-node             1.19.1                     263f2061b567        2 weeks ago         826MB
hasura/graphql-engine                v1.2.1.cli-migrations-v2   768e0d8e0155        4 months ago        123MB
frolvlad/alpine-glibc                alpine-3.11_glibc-2.30     4df8f5abf8fd        8 months ago        17.4MB
postgres                             11.5-alpine                da01ecfbabe1        11 months ago       71.8MB
node                                 10.15.3-alpine             56bc3a1ed035        16 months ago       71MB

**Comment by btbf** [comment]
Sorry.
The volume of posgre could not be deleted.
After rebuilding the database it worked fine
