### ISSUE TITLE
block sync stop at 4826859

### ISSUE THREAD

**Issue by bitcodernull** [input-output-hk/cardano-graphql#338]
my two nodes met the same problem
block sync stop at 4826859
the error is :

[String "ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed \"<socket: 27> closed when reading data, waiting on next header True\")",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"\"}"]

**Comment by SebastienGllmt** [comment]
Update to cardano-db-sync 5.0.2 (it's backwards compatible with 5.0.1) and it should fix your issue.

**Comment by bitcodernull** [comment]
i update to the 5.0.2,  the same problem
thanks

**Comment by CyberCyclone** [comment]
I ran into this issue as well. I changed to master branch but it's now stuck on 4828638. I've also tried cardano-db-sync 5.0.2 while using graphql master branch and still stuck. I was hoping that this would be considered production ready 
(even if there are missing features) but after these blocks becoming stuck I'm not so sure.

**Comment by SebastienGllmt** [comment]
Probably you're stuck on a different issue that was fixed in cardano-db-sync master yesterday. The fix require a full re-sync of the database, but if you don't want to resync you can use the workaround mentioned in https://github.com/input-output-hk/cardano-db-sync/issues/351

**Comment by lcgogo** [comment]
@SebastienGllmt I have resync db by CARDANO_NODE_VERSION=1.21.1, but the height stopped at 482638

**Comment by vae520283995** [comment]
I have the same problem, I have to close the exchange's deposit and withdrawal of cardano

**Comment by CyberCyclone** [comment]
Using the latest release of cardano-db-sync version and doing a db reset fixed it for me. Just putting it out there, the block becoming stuck isn't related to graphql, it's a cardano-db-sync issue.

**Comment by rhyslbw** [comment]
> Using the latest release of cardano-db-sync version and doing a db reset fixed it for me
@CyberCyclone the latest release (`5.0.2`) will still require the workaround @SebastienGllmt mentioned in https://github.com/input-output-hk/cardano-graphql/issues/338#issuecomment-711160261

@vae520283995 I'll get back to you regarding patches on the `v2` line of `cardano-graphql`

**Comment by rhyslbw** [comment]
@vae520283995 https://github.com/input-output-hk/cardano-graphql/releases/tag/2.2.1
