### ISSUE TITLE
Use the latest commit, still wrong

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-graphql#341]
This is images:
          Container                          Repository                                 Tag                        Image Id       Size  
----------------------------------------------------------------------------------------------------------------------------------------
cardano-db-sync-mainnet          rhyslbw/cardano-db-sync              09205d901ee86299cc68b3a0d0a8feb52489858f   4ccd14b6d526   1.005 GB
cardano-graphql-hasura-mainnet   inputoutput/cardano-graphql-hasura   2.2.0                                      e424b1d258dc   123.5 MB
cardano-graphql-mainnet          inputoutput/cardano-graphql          2.2.0                                      56b0b8aaa9be   93.65 MB
cardano-node-mainnet             inputoutput/cardano-node             1.20.0                                     1769d6a7d80b   825.4 MB
cardano-submit-api-mainnet       inputoutput/cardano-submit-api       2.1.3                                      d21072d66eb7   788.2 MB
postgres-mainnet                 postgres                             11.5-alpine                                da01ecfbabe1   71.85 MB

This is error logs:
cardano-db-sync-extended: FatalError {fatalErrorMessage = "readDbSyncNodeConfig: Error parsing config: AesonException \"Error in $: key \\\"NodeConfigFile\\\" not found\""}
Connecting to network specified in configuration.yaml
cardano-db-sync-extended: FatalError {fatalErrorMessage = "readDbSyncNodeConfig: Error parsing config: AesonException \"Error in $: key \\\"NodeConfigFile\\\" not found\""}
Connecting to network specified in configuration.yaml

Use this commit
https://github.com/input-output-hk/cardano-graphql/commit/f180c9a5ea785856d85ef00d40b9d199ac0f256a

**Comment by rhyslbw** [comment]
The changes being staged will go out as `3.0.0`, and will include upgrade instructions. I suggest waiting for the release
