### ISSUE TITLE
Host networking not allowing access to hasura-cli

### ISSUE THREAD

**Issue by satonz** [input-output-hk/cardano-graphql#360]
![image](https://user-images.githubusercontent.com/38401802/98187289-8a67d180-1f4b-11eb-8280-242f6b55f3f6.png)

**Comment by satonz** [comment]
Yesterday afternoon, when I set up the node, this error occurred，    I started using docker

**Comment by rhyslbw** [comment]
It appears to be an issue with your host networking, as the curl RUN command is failing

What do you see running:
```
 docker run -i --rm alpine ping google.com
```
