### ISSUE TITLE
Timeout while rewards_aggregate on epoch 227

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#368]
## Platform

- [ X] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 
GraphQL 3.0.0 and 2.2.1

#### Runtime

- [ ] Node.js
- [X ] Docker

### Steps to reproduce the bug
Running this query causes high CPU usage (on 8 core 16GB DigitalOcean server) and an eventual timeout.
```
{
    rewards_epoch_227: rewards_aggregate(where:{stakePool:{hash: {_eq: "5b9a5633289c52003d359bce18f77f571a701fd3942a52bde3262558"}} earnedIn:{number: {_eq: 227}}}) {aggregate { sum {amount}}  }
}
```

Running on previous epoch values completes successfully (i.e, running with 226 returns instantly). This happens on any pool hash I've tried (not related to whether the pool has rewards or not in that epoch.

### What is the expected behavior?
It should return the sum within a few seconds.

**Comment by rhyslbw** [comment]
The schema is missing the conditional fields on the `Rewards_bool_exp` type. The correct query when the fix is merged and released will be:

``` graphql
rewards_aggregate (
    where: { 
      _and: [
        { earnedIn: { number: { _eq: 227 } } },
        { stakePool: { hash: { _eq: "5b9a5633289c52003d359bce18f77f571a701fd3942a52bde3262558"}}}
      ]
    }
  ) {
    aggregate {
      count
      sum {
        amount
        
      }
    }
  }
```

**Comment by CyberCyclone** [comment]
Thanks for that. Unfortunately this hasn't resolved it for me. I've built from master branch and also run the exact command you've given. Sadly it still times out while the query runs with high cpu in the background.

![image](https://user-images.githubusercontent.com/4373888/99160549-366fa080-2734-11eb-893b-33e751435a24.png)

`git rev-parse master` gives me 6f20487ed6969bb7df057e3794fd57741d420349 which looks correct as the latest master commit.

I've also run `docker system prune -a` to make sure it's not using a cache build, and stopped and started docker to make sure it is running the correctly built version. Plus, the _and operator works now so it's running the correct version.

Doing the query with epoch 226 returns instantly:

![image](https://user-images.githubusercontent.com/4373888/99160778-6c158900-2736-11eb-809a-da90a45cf0cd.png)

**Comment by CyberCyclone** [comment]
@rhyslbw I've just tried again on release 3.0.1 and I'm not having any timeouts on any of the epochs I've chosen. I've tried it on 2 nodes so far without any issues. I was going to try and dig into this a bit today to see if I could find anything obvious but it's fine now.

Is there anything that you know of that's changed that could have fixed this? I'm a bit hesitant to say it's "fixed" unless there was an obvious change. I know previously I had this running for a while before the 227 epoch caused high CPU loads. Since then I've kept this "disabled" on my dashboard and only now trying again.

**Comment by CyberCyclone** [comment]
I was incorrect. Transitioning to this epoch 233 has broken it again. After changing to the new epoch the CPU remains high for about an hour and then drops to normal levels. Now doing a rewards query times out as before.

**Comment by rhyslbw** [comment]
> After changing to the new epoch the CPU remains high for about an hour and then drops to normal levels

Is this without making a query? Can you identify which service is causing the CPU demand?

**Comment by CyberCyclone** [comment]
I suspect that the high CPU load wasn't directly related to the epoch change, but more to do with running the rewards lookup query on a particular epoch after an epoch change. I disabled any rewards lookup during the last epoch change and there was no high CPU usage. Since I get about 200 unique users a day to my dashboard, running the rewards query seems to be the one that pushes it to high CPU directly after an epoch change. 

I've now waited 24 hours since the epoch change (with rewards queries disabled) and I've run the below query which results in a timeout:

```
{rewards_aggregate (
    where: { 
      _and: [
        { earnedIn: { number: { _eq: 233 } } },
        { stakePool: { hash: { _eq: "cdb10209d937fc1559c635e35b9147febde5307b4a7d276f868775cd"}}}
      ]
    }
  ) {
    aggregate {
      count
      sum {
        amount
        
      }
    }
  }}
```

![image](https://user-images.githubusercontent.com/4373888/101999352-d9add880-3d27-11eb-8782-7b5d36816b3e.png)

I don't have this problem if I change the epoch to anything other than the last epoch we know the rewards for. As in, for this case, it's currently epoch 235 (24 hours into this epoch), so running the query against 233 gives a timeout and causes high CPU. Running it on 232 and before runs fine.

While GraphQL gives a timeout, it seems that the query is still running against postgres for a while. I've run the above query in the Hasura playground and the query has been running for at least 20 minutes without a timeout, and eventually returns with this (it should have found some results, but it hasn't):

```
{
  "data": {
    "rewards_aggregate": {
      "aggregate": {
        "count": 0,
        "sum": {
          "amount": null
        }
      }
    }
  }
}
``` 

This means that I can do a query in GraphQL and it will timeout, but it will keep running in postgres. So if 4 or more queries are running, it triggers a really high CPU load.

I've looked in the table and there are rewards for that epoch:

![image](https://user-images.githubusercontent.com/4373888/101999845-af124e80-3d2c-11eb-97eb-173f1eaf89b3.png)

**Comment by CyberCyclone** [comment]
Just an update on this. I've done the update to version 3.1.0 and cleared the db. Querying the rewards_aggregate on epoch 233 (current is 235) is still timing out. So it doesn't seem to be an issue with running live during an epoch change. As in, running fresh (and tested on 2 nodes) still shows this bug.

**Comment by CyberCyclone** [comment]
@rhyslbw Just an update on this. I haven't seen this happen in a long time and I've retried it now without any issues. No one else seems have come across this issue, so I'm pretty confident this bug no longer exists. I'll close the issue and if it happens again I'll comment with the updated info.
