### ISSUE TITLE
activeStake inaccurate?

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#369]
I've been using cardano-graphql for a while and one thing that has become obvious is the activeStake doesn't seem to align with other dashboards.

Running the query with epochNo being 229 (the current epoch):
```
{
  activeStake_aggregate(where: {epochNo: {_eq: 229}, registeredWith: {hash: {_eq: "5b9a5633289c52003d359bce18f77f571a701fd3942a52bde3262558"}}} ) {
	aggregate {
		sum {
			amount
		}
	}
}
  }

```

Gives me this result:
```
{
  "data": {
    "activeStake_aggregate": {
      "aggregate": {
        "sum": {
          "amount": "337750037611"
        }
      }
    }
  }
}
```

When the amount should be "79709691106" according to adapools and pooltool.

Have I misinterpreted how it's meant to be queried? Based on the wording here: https://github.com/input-output-hk/cardano-graphql/issues/345, "the record is active stake in an epoch". I take that to mean, "in epoch 229, this is the active stake".

To get the current active stake for 229, I have to query epoch 230. Is this the correct way, so it's interpreted as, "the active stake up until the snapshot for the next epoch (230 in this case)"?

Thanks!

**Comment by rhyslbw** [comment]
This was addressed in https://github.com/input-output-hk/cardano-graphql/pull/371
``` graphql
{
  activeStake_aggregate (
    where: { 
      _and: [
        { epochNo: { _eq: 229 }},
        { registeredWith: { hash: { _eq: "5b9a5633289c52003d359bce18f77f571a701fd3942a52bde3262558"}}}
      ]
    }
  ) {
    aggregate {
      count
      sum {
        amount
      }
    }
  }
}
```

``` json
{
  "data": {
    "activeStake_aggregate": {
      "aggregate": {
        "count": "6",
        "sum": {
          "amount": "79709691106"
        }
      }
    }
  }
}
```

We'll make a release early next week, but you can build from `master` to get access to the fix.
