### ISSUE TITLE
Correct CHANGELOG link on 3.0.0 release page

### ISSUE THREAD

**Issue by tatyanavych** [input-output-hk/cardano-graphql#370]
On https://github.com/input-output-hk/cardano-graphql/releases/tag/3.0.0  in the statement:
> _You may be impacted by breaking changes, which are listed in the CHANGELOG_

the CHANGELOG link is incorrect; the correct one is https://github.com/input-output-hk/cardano-graphql/blob/3.0.0/CHANGELOG.md. Please, correct. 

P.S. In future, before releasing ensure all links in Release Notes are resolved ;)

**Comment by rhyslbw** [comment]
Thanks @tatyanavych. It needed to be targeting the anticipated tag, not the release branch
