### ISSUE TITLE
Active Stake empty for epoch 231

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#375]
I've been using cardano-graqhql and I've noticed that retrieving data for ActiveStake epoch 231 is completely empty. I've compared it against 2 nodes that was **NOT** affected by this bug: https://github.com/input-output-hk/cardano-db-sync/issues/398 and I am pulling transactions.

I've checked the actual tables and looking up 230 pulls data, 231 has no records. 

![image](https://user-images.githubusercontent.com/4373888/99890857-31b86880-2caf-11eb-8467-24dd1088b367.png)

I'm currently running cardano-graphql commit 6f20487ed6969bb7df057e3794fd57741d420349 which is using cardano-db-sync:6.0.0

**Comment by CyberCyclone** [comment]
As mentioned in https://github.com/input-output-hk/cardano-graphql/issues/376, this is fixed by doing a db and node re-sync, but it doesn't seem to be directly linked to the db-sync 398 bug because db-sync worked fine after the epoch boundary. It's just the extra graphql features that failed at the boundary.

**Comment by rhyslbw** [comment]
If you are not seeing records in the Hasura Console, then the data isn't in the DB at that point. `ActiveStake` is simple [SQL View](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql#L160-L171) that remaps the names of a table and it's columns to the semantics that an 'active stake' record contains the stake registered with a stake key for a given epoch.

I'll try to reproduce this and get back to you.

**Comment by rhyslbw** [comment]
Will close as it's not reproducible, however feel free to reopen should it occur again
