### ISSUE TITLE
Apply db-sync fix for epoch crash

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#377]
Can we please get a patch branch created to be able to apply the fix for the broken epoch issue: https://github.com/input-output-hk/cardano-db-sync/issues/398

I've tried changing the docker image for db-sync to 'master' but Hasura isn't able to start up:

![image](https://user-images.githubusercontent.com/4373888/100157615-8b5ea400-2ef6-11eb-8f3d-97aab3b070cb.png)

**Comment by satonz** [comment]
When will this problem be fixed,

**Comment by erikd** [comment]
@CyberCyclone The db-sync error message in that image has nothing to do with that db-sync issue.

However, for that issue, commit `a8129c54c7caa663dc8826a33a3655e32579d4d6` of `cardano-db-sync` is due to be tagged as `6.0.1` RealSoonNow (tm).

**Comment by CyberCyclone** [comment]
@erikd thanks for that.  This was more specifically to do with cardano-graphql and trying to run against the docker file tagged "master" for db-sync. I should have been specific in that the first line in the screenshot says "Remote schema is missing Block" and Hasura doesn't start up. 

I have since then tried running the master branch of db-sync with the docker-comose config but postgres isn't populating for some reason so that might be why cardano-graphql isn't able to use db-sync:master yet.

**Comment by rhyslbw** [comment]
Fix release being prepared in https://github.com/input-output-hk/cardano-graphql/pull/380

**Comment by rcmorano** [comment]
Hi guys, I'm using this [0] versions combo (docker images) and tho it works for `testnet`, I can't get it to work on `mainnet` cos of this `Remote schema is missing Block`.

This instance was initially sync using @erikd's temporary fix branch for `6.0.0` and `(hasura|graphql)-3.0.0` (which also worked in for `testnet` deploy); then smoothly upgraded to corresponding `6.0.1` and `3.0.1`, but nothing changed :(

Any hint/workaround :D?

[0]
```
cardano-db-sync-6.0.1
hasura-3.0.1
cardano-graphql-3.0.1
```
