### ISSUE TITLE
cardano-db-sync 6.0.1

### ISSUE THREAD

**Issue by satonz** [input-output-hk/cardano-graphql#379]
rhyslbw/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-3a6e7199c1f2f0883960c3e4ee7312051cb92911}

May I ask whether this version has been tested and can be used？

**Comment by satonz** [comment]
@rhyslbw

**Comment by erikd** [comment]
`db-sync` version `6.0.1` has been through the official QA and release process, tagged and released on GH. Since this the changes from `6.0.0` to `6.0.1` are purely bugfixes, it should JustWork(tm).

**Comment by satonz** [comment]
Thanks
