### ISSUE TITLE
rewards(order_by: {address: ?

### ISSUE THREAD

**Issue by AskBid** [input-output-hk/cardano-graphql#382]
Is it possible to order the `rewards(order_by ...)` query by address?

currently I only see  `StakeAddress_comparison_exp` (`_eq`, `_in`) and not `order_by` (`asc`, `desc`).

**Comment by CyberCyclone** [comment]
Yeah, this looks like a bug. Here in the schema it has 'StakeAddress_comparison_exp' when I think it should be 'order_by'.

```
input Reward_order_by {
  address: StakeAddress_comparison_exp
  amount: text_comparison_exp
  earnedIn: Epoch_order_by
  stakePool: StakePool_order_by
}
```

Like how ActiveStake has:

```
input ActiveStake_order_by {
  address: order_by
  amount: order_by
  epoch: Epoch_order_by
  epochNo: order_by
  registeredWith: StakePool_order_by
}
```

If that's it then it should be simple for the devs to fix.

**Comment by AskBid** [comment]
yes, that's exactly it.
Thanks

**Comment by rhyslbw** [comment]
Thanks for the leg work, I'll patch this shortly
