### ISSUE TITLE
Public API Procedures

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#394]
Hi, I'm looking at making a publicly accessible API as an alternative to the one listed here: https://github.com/input-output-hk/cardano-graphql/issues/155

The Hasura console isn't publicly accessible (IP restricted), however the GraphQL playground is. I don't see a reason for turning it off. Is there anything further that I would need to do to make sure the environment is safe for public use?

Thanks!

**Comment by CyberCyclone** [comment]
No worries. It was low priority. 

I haven't set them up yet, however I was just wondering if there's any special setup that I would need to do to make it safe for public use? E.g, by default is there any mutations / other ways that would allow anyone to alter the data if they only had access to the GraphQL endpoint?

Was there anything special about the GraphQL servers that IOHK was running? 

I'm definitely looking at setting up a public testnet version that people can play with and I might do a mainnet.

**Comment by rhyslbw** [comment]
>  if there's any special setup that I would need to do to make it safe for public use?
 
The main issue is that aggregation queries can be quite intensive, but with a trusted client can be managed. I'm thinking of a way to start the server with a mode that rejects calls to these queries, or starts with a subset that we consider safe.

> are there any mutations / other ways that would allow anyone to alter the data if they only had access to the GraphQL endpoint?

No, the only mutation is to submit a serialized and signed transaction

**Comment by CyberCyclone** [comment]
> The main issue is that aggregation queries can be quite intensive, but with a trusted client the load can be managed. I'm thinking of a way to start the server with a mode that rejects calls to these queries or starts it with a subset that we consider safe.

Yeah, some can be so intense that they don't seem to ever return (graphql times-out, but the query keeps running). Since I'm using cardano-graphql to power adatools.io, I'm wanting to add a playground area for users who want to play with it without setting up a full node. 

To handle the users, I'm thinking of adding a basic queue like how the React Expo simulator has with it's playground. This should limit people abusing it or trying to power their apps from it since it's just a playground, not a full service I'm offering.

I'll post back here once I've got it setup up if anyone wants to use it.

**Comment by CyberCyclone** [comment]
Just for future reference, I've created a Mainnet endpoint here: https://graphql.adatools.io

I couldn't work out a practical queue system, so I've settled for limiting Postgres to timing out after 60 seconds (it seems to work). That should be enough for people to play with.

The server it's running on is "cheap" for a 12 core, 48GB RAM (I paid about $350 for 3 years). I can't guarantee it's reliability, but it should be fine for a playground environment. At this point it's just a single server, so no backup at this point if it goes down. :) 

Once I get some more spare time I'll be creating a testnet playground.

**Comment by rhyslbw** [comment]
Just looping back to this as we've just integrated [query complexity rate limiting](https://github.com/input-output-hk/cardano-graphql/pull/502), and there will be a release making this feature available once `cardano-db-sync@10.0.0` is out. It comes with a default and configuration option to relax or tighten the allowance.

**Comment by CyberCyclone** [comment]
> Just looping back to this as we've just integrated [query complexity rate limiting](https://github.com/input-output-hk/cardano-graphql/pull/502), and there will be a release making this feature available once `cardano-db-sync@10.0.0` is out. It comes with a default and configuration option to relax or tighten the allowance.

Could we please have some documentation on how to set the environment variable for it to edit the value? The default 200 seems to small for my queries and setting ```maxQueryComplexity=1000``` in the environment section of docker-compose.yml under graphql doesn't change it. Not sure if it's hooked up for that.

**Comment by rhyslbw** [comment]
The release branch has been made, and we'll be tagging once final QA checks are performed: 
https://github.com/input-output-hk/cardano-graphql/tree/5-0-stable
