### ISSUE TITLE
How to get pending transactions

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-graphql#398]
curl 'http://localhost:3100/' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'Accept: application/json' -H 'Connection: keep-alive' -H 'DNT: 1' -H 'Origin: http://localhost:3100/' --data-binary '{"query":"query{transactions(where:{hash:{ _eq:\"4b8bb94226668cdec803a865e30ddf8f9d787d1b1fa180330d0f63deb6ce5a05\"}}){blockIndex,fee,hash,inputs{,address,sourceTxHash,sourceTxIndex,value},outputs{address,index,value},size,includedAt}}\n"}' --compressed

Return an empty set when the transaction is pending

**Comment by erikd** [comment]
`cardano-graphql` sits on top of `cardano-db-sync` and `db-sync` does not provide information about pending transactions.

**Comment by vae520283995** [comment]
> `cardano-graphql` sits on top of `cardano-db-sync` and `db-sync` does not provide information about pending transactions.

Is there any other way to get pending transactions

**Comment by erikd** [comment]
There is currently no way that I know of to get pending transactions.

**Comment by vae520283995** [comment]
> There is currently no way that I know of to get pending transactions.

ok, thank you
