### ISSUE TITLE
ActiveStake Pool Hash Improvement

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#399]
~~Based on the example here (which I've been using regularly): https://github.com/input-output-hk/cardano-graphql/blob/f180c9a5ea785856d85ef00d40b9d199ac0f256a/packages/api-cardano-db-hasura/src/example_queries/active_stake/activeStakeForAddress.graphql~~

Based on this query:

```
{
    delegators: activeStake(
        where: {
            _and: [
                {epochNo: {_eq: 241}}, 
                {registeredWith: {hash: {_eq: "9417e18efcc4c258df21c89942009a498a751a0a63f8d72714cf75b2"}}}
            ]
        }
        limit:100
        offset:100 
    ) {
        amount
        address
        epochNo
    }
}
```

I've noticed that on pools that have a large amount of delegators (over 5000 for this pool 9417e18efcc4c258df21c89942009a498a751a0a63f8d72714cf75b2), it will most likely timeout. Even using a limit of 10 can take a few seconds to return.

From what I can tell in Hasura, am I correct in that **pool_hash** is part of the root row and therefore doesn't have to do a further table lookup, while using the query above has to query the Stake Pool table to do the match? 

If **pool_hash** is in fact part of the top level, can we please have that exposed in GraphQL? Based on my tests querying on pool_hash returns almost instantly, so this should be a major improvement.

**Comment by rhyslbw** [comment]
Thanks for raising this @CyberCyclone . From memory that was a recent change upstream I've not taken advantage of, but can do so to address the performance issue. I can get it done for the `3.2.0` release
