### ISSUE TITLE
I am getting an error when i try to deploy to an aws instance but no error when I deploy to a VM at my home.

### ISSUE THREAD

**Issue by stackBlock** [input-output-hk/cardano-graphql#400]
I am getting this error when i try to deploy to an aws instance but no error when I deploy to a VM at my home. Both machines are running ubuntu 20. 

step 25/81 of the setup:
ERROR: Service 'cardano-graphql' failed to build : The command '/bin/sh -c cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd' returned a non-zero code: 1

Is there something I need to configure on the aws instance that I am missing? 
thanks

**Comment by rhyslbw** [comment]
I'll investigate and get back to you @stackBlock

**Comment by rhyslbw** [comment]
The repository now has `cardano-node` as a git submodule, so ensure these have been pulled

```
git clone git@github.com:input-output-hk/cardano-graphql.git --recurse-submodules
```
or on an existing clone:
```
git submodule update --init
```

I'll update the readme to reflect this change

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-graphql/commit/ef884f3c91a8ff8c6135a3479549553534ec6c53
