### ISSUE TITLE
docker compose error

### ISSUE THREAD

**Issue by tahussle** [input-output-hk/cardano-graphql#403]
Getting the below error when building using docker-compose file . how do i resolve?

Step 25/81 : RUN cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd
 ---> Running in b6772d8bef9d
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] unknown package: cardano-cli (user goal)
[__0] fail (backjumping, conflict set: cardano-cli)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-cli

**Comment by rhyslbw** [comment]
Is this the `master` branch? I'll try to replicate it and get back to you

**Comment by tahussle** [comment]
yes used 
git clone https://github.com/input-output-hk/cardano-graphql.git

**Comment by rhyslbw** [comment]
Looks like a duplication of #400

**Comment by rhyslbw** [comment]
cc @tahussle  https://github.com/input-output-hk/cardano-graphql/issues/400#issuecomment-759866064

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-graphql/commit/ef884f3c91a8ff8c6135a3479549553534ec6c53

**Comment by tahussle** [comment]
Yes  i can confirm this now works . Thanks for your help
