### ISSUE TITLE
Nodejs error: connection timeout

### ISSUE THREAD

**Issue by asnakep** [input-output-hk/cardano-graphql#405]
Hello,

I'm running cardano-graphql 3.1.1 on same server where I run db-sync-extended, it suddenly stopped to work returning nodejs timeout error to postgres. No changes have been applied.
If I  run cardano-graphql from my local machine, no issues connecting to remote postgres.

Binaries built with nix on nixos.

Please let me know more details are needed.

Many thanks in advance,
kind regards,
Emanuele

**Comment by rhyslbw** [comment]
Hi @asnakep
It sounds like you just have an authorisation problem with postgres on the remote server. Is `cardano-db-sync-extended` able to connect?

**Comment by asnakep** [comment]
Hello,

db-sync-extended is on a remote machine, if I plug graphql from my local it works fine.

While if I plug graphql on same remote server where db-sync-extended runs, I get connection timeout.

it was previously working fine. Just suddenly stopped to work.

I can connect with the used postgres user via psql.

I'll try to write a simple nodejs connector to postgres.

So resuming the issue, graphql can connect to remote postgres, but not to local.

Thank you,
Cheers.

**Comment by asnakep** [comment]
Hello,

some more details:

**On cardano-graphql launch having hasura running fine**

Error: connect ETIMEDOUT 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
DbClient.pgSubscriber: Reconnecting attempt 1

**Command failed:** /home/nodo/cardano-graphql/nix-build/hasura-cli/bin/hasura --skip-update-check --project /nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/packages/api-cardano-db-hasura/hasura/project --endpoint http://localhost:8090 migrate apply --up all

**Manual run of failed command**
....Lot of SQL actions output.....
[42P07] FatalError: relation "Block" already exists 

I'll try to recreate hasura db objects, since it seems related with hasura schema.
I let you know in a while.

**Comment by asnakep** [comment]
I've dropped and recreated hasura objects

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE SCHEMA IF NOT EXISTS hdb_catalog;
CREATE SCHEMA IF NOT EXISTS hdb_views;
ALTER SCHEMA hdb_catalog OWNER TO hasura;
ALTER SCHEMA hdb_views OWNER TO hasura;
GRANT SELECT ON ALL TABLES IN SCHEMA information_schema TO hasura;
GRANT SELECT ON ALL TABLES IN SCHEMA pg_catalog TO hasura;
GRANT USAGE ON SCHEMA public TO hasura;
GRANT ALL ON ALL TABLES IN SCHEMA public TO hasura;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO hasura;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA public TO hasura;

I'm getting same timeout error, with a new sql error
FatalError: relation "idx_block_hash" already exists 

this index belongs to cexplorer.public schema.

So for now I don't want to touch cexplorer.public schema objects.

Cheers.

**Comment by asnakep** [comment]
I dropped and recreated those indexes which I said don't want to touch them, but they are created by graph-ql.
So metadata has been recreated successfully. Graphql works fine from my local machine.
But I have same connection issue on remote machine where graphql connects to local postgres.

**launch_cardano-graphql.sh** 
Error: connect ETIMEDOUT 127.0.0.1:5432
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 5432
}
DbClient.pgSubscriber: Reconnecting attempt 1
{"level":"info","msg":"Applying migrations...","time":"2021-01-25T10:33:26Z"}
{"level":"info","msg":"migrations applied","time":"2021-01-25T10:33:26Z"}

{"level":"info","msg":"Applying migrations...","time":"2021-01-25T10:33:26Z"}
{"level":"info","msg":"migrations applied","time":"2021-01-25T10:34:25Z"}

{"level":"info","msg":"Clearing metadata...","time":"2021-01-25T10:34:25Z"}
{"level":"info","msg":"Metadata cleared","time":"2021-01-25T10:34:26Z"}

DbClient.pgSubscriber: Fatal database connection error: Error: Re-initializing the PostgreSQL notification client after connection loss failed: Stopping PostgreSQL reconnection attempts after 3000ms timeout has been reached.
    at /nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:108:47
    at step (/nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:43:23)
    at Object.next (/nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:24:53)
    at step (/nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:28:139)
    at Object.next (/nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:24:53)
    at fulfilled (/nix/store/vfbgg6dgyx2x6x6p7ji15sla0blnm5fs-cardano-graphql-3.1.1/node_modules/pg-listen/dist/index.js:15:58)

**Connect user via psql**
psql -h localhost -p 5432 -d cexplorer -U hasura -W
Password: 
psql (12.5, server 11.10)
Type "help" for help.

cexplorer=> 

Thank you,
kind regards
Emanuele
