### ISSUE TITLE
3.2.0 docker compose --build can't find package cardano-cli

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-graphql#416]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
{
  os: {
    arch: 'x64',
    cpus: { count: 2, model: 'AMD EPYC 7571' },
    release: '5.4.0-1029-aws',
    totalMem: 4077387776,
    type: 'Linux'
  },
  version: '3.2.0'
}
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Ubuntu 20.04 LTS

**Platform version**: 

#### Runtime

**Runtime version**: 
node
v14.15.4

docker
Docker version 20.10.3, build 48d30b5

### Steps to reproduce the bug

sudo docker-compose up -d --build

### What is the expected behavior?

docker-compose up should work as usual.

Getting instead:

Step 25/80 : RUN cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd
 ---> Running in 9076d56951b7
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] unknown package: cardano-cli (user goal)
[__0] fail (backjumping, conflict set: cardano-cli)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-cli

The command '/bin/sh -c cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd' returned a non-zero code: 1
Service 'cardano-graphql' failed to build

**Comment by MarcelKlammer** [comment]
In the README the " --recurse-submodules" is not visible at first glance, please include a line break.

**Comment by rhyslbw** [comment]
Ah yes, this is currently hidden. I will do as suggested

**Comment by rhyslbw** [comment]
Done in https://github.com/input-output-hk/cardano-graphql/commit/9543837ea3eab2cf346d740ae5ce69880a456cb8
