### ISSUE TITLE
syncPercentage counting backwards 

### ISSUE THREAD

**Issue by stackBlock** [input-output-hk/cardano-graphql#419]
System: ubuntu 20.04 desktop.

When the instillation gets to the point where you can check the syncPercentage, the percentage counts backwards. It eventually stops and I can no longer connect to the playground. It also completely filled up the remaining space on my hard drive... about 12 gigs.
It is a brand new instillation of ubuntu. I tried to twice with the same result.
I used the same process on an older instigation of ubuntu and ubuntu server 20.04 on an aws instance with no problems.
It shouldn't matter whether it is the desktop vs server because it is a docker image, is that correct?
Any help would be appreciated.
Anthony

**Comment by rhyslbw** [comment]
Counting backwards indicates `cardano-db-sync` has stopped syncing, as the node is now moving ahead. What is filling up your disk? Are you using a configuration provided in this repo or your own? If the latter please share it here

> It shouldn't matter whether it is the desktop vs server because it is a docker image, is that correct?
Correct, that alone is an unlikely cause.

**Comment by stackBlock** [comment]
I am using the one provided by this repo. Before it started going backwards, it was jumping around... going forward a bit and then back until finally it was just going backwards. I am not sure what was filling up the hard drive, I just cleared everything and started again. 
It is strange because it worked on a vm setup without a problem and I have it running on an aws instance currently but I want to get it off the instance and I would rather not run it in a vm if at all possible.  
This is not a priority I just wanted to document what happened in case it happens for someone else.

Anthony

**Comment by stackBlock** [comment]
In case your interested, this is what I did with it... It's nothing ground-breaking but it was fun: 
https://www.youtube.com/watch?v=bgQXKd4Upa8

**Comment by rhyslbw** [comment]
Nice one @stackBlock ! Next iteration could have the user construct the transaction (and pay fees) on their side :smile:
