### ISSUE TITLE
What's the output value in transaction of MultiToken?

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-graphql#420]
```graphql
query($txid: Hash32Hex!) {
  transactions(where: { hash: { _eq: $txid } }) {
    hash
    inputs {
      sourceTxHash
      sourceTxIndex
    }
    outputs {
      address
      value
      tokens {
        assetId
        assetName
        policyId
        quantity
      }
    }
  }
}
```

If a tx of MultiToken,what is value of output? is zero ?

**Comment by rhyslbw** [comment]
`Output.value` is the ada value of the output. Technically the model moving forward has ada being transacted as tokens, however ada is a special case since it must be included in every UTxO, but we also have backwards compatibility to deal with.
