### ISSUE TITLE
Broken link to API Documentation

### ISSUE THREAD

**Issue by kss-espeo** [input-output-hk/cardano-graphql#427]
Hi. I would like to look at cardano-graphql API Documentation, however this link: https://input-output-hk.github.io/cardano-graphql/ apears to not load.

Context: I am developing an application that pulls data off the different blockchains and does offline analysis on it for the purpose of Anti-Money-Laundering. I consider integrating my application with Cardano. As a part of that process, I will need to import all the blocks one by one, along with the transactions contained in them and parse that data into my domain model. I am searching for a way to do that and it seems that cardano-graphql is currently the only way (correct me if I'm wrong please!) . There also is a `cardano-explorer-api` but set of methods it offers is does not match all my needs.

**Comment by alexqrid** [comment]
Hi. It's not a full documentation but you can find some query examples here [https://input-output-hk.github.io/cardano-rest/migration-guide/explorer-api/](https://input-output-hk.github.io/cardano-rest/migration-guide/explorer-api/)

**Comment by kss-espeo** [comment]
Sweet, this is much better. Thank you!

**Comment by rhyslbw** [comment]
The docs have been refactored to reference local source, so https://input-output-hk.github.io/cardano-graphql/ is no longer dependent on a remote server.

**Comment by kss-espeo** [comment]
Awesome. One more questions then @rhyslbw @alexqrid . Is there a public Cardano node with an open GraphQL API that I can interact with to play around before hosting my node?

**Comment by alexqrid** [comment]
I have found [this](https://graphql-api.mainnet.dandelion.link/)
