### ISSUE TITLE
cardano-db-sync-extended: Identity Connect Attempt Exception

### ISSUE THREAD

**Issue by Datiswaken** [input-output-hk/cardano-graphql#428]
Hi,
after updating to version 3.2.0 I am receiving the following error upon running `docker-compose up --build -d && docker-compose logs -f`
```
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:41] [2021-02-13 11:41:15.53 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:173] [2021-02-13 11:41:15.53 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:173] [2021-02-13 11:41:15.53 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 13>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2021-02-13 11:41:15.53 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 13>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:41] [2021-02-13 11:41:15.56 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:41] [2021-02-13 11:41:16.56 UTC] Identity Restarting Subscription after 1.026282484s desired valency 1 current valency 0
```
The error happens for both, docker-compose.yml as well as docker-compose.dev.yml.

I am running it locally on my laptop.
Ubuntu 18.04.5 LTS
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
8 GB RAM

Any help is appreciated.

**Comment by rhyslbw** [comment]
That's expected on startup when `cardano-node` is still initialising and can sometimes take a minute or two. Did it resolve?

**Comment by Datiswaken** [comment]
Nope, I ran it multiple times and waited 10-15 minutes. Using the `docker-compose.yml` file my laptop started to get unresponsive and was under high workload. Maybe the specs of my laptop are too small to facilitate the initialisation of the `cardano-node`.

**Comment by rhyslbw** [comment]
What's your machine spec?

**Comment by Datiswaken** [comment]
Specs are:
Ubuntu 18.04.5 LTS
Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
4 Cores
8 GB RAM
500 GB SSD, 55% occupied.

Any other specs that are of interest?

**Comment by rhyslbw** [comment]
Moving to `3.2.0` introduces a new version of `cardano-db-sync` that requires the local state to be rebuilt.

https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db

Was this performed?

`

**Comment by Datiswaken** [comment]
I did this when moving to version 3.0.0, but not for 3.2.0. I will try to see if this helps.

**Comment by Datiswaken** [comment]
Rebuilding with `cgql docker rebuild-service` did not help. I now managed to get it fixed by rebuilding the whole project and downloading the whole blockchain again. The error still pops up for the first few minutes on startup, like you mentioned before, but afterwards it is fine.
