### ISSUE TITLE
v3.2.0 docker-compose up -d build error

### ISSUE THREAD

**Issue by lichao-cobo** [input-output-hk/cardano-graphql#431]
I met followed error when
docker-compose -f docker-compose.yml up -d

`Step 17/80 : RUN git clone https://github.com/input-output-hk/libsodium.git &&  cd libsodium &&  git fetch --all --tags &&  git checkout ${IOHK_LIBSODIUM_GIT_REV}
 ---> Using cache
 ---> 74fd496cb4e0
Step 18/80 : WORKDIR /app/src/libsodium
 ---> Using cache
 ---> 8c3e4c43147c
Step 19/80 : RUN ./autogen.sh && ./configure && make && make install
 ---> Using cache
 ---> 92d858cf14a9
Step 20/80 : ENV LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH"
 ---> Using cache
 ---> 6316eef4d689
Step 21/80 : ENV PKG_CONFIG_PATH="/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH"
 ---> Using cache
 ---> 48454c253cfd
Step 22/80 : WORKDIR /app/src
 ---> Using cache
 ---> de73d59235e8
Step 23/80 : COPY /cardano-node /app/src/cardano-node
 ---> Using cache
 ---> 9567628cc01e
Step 24/80 : WORKDIR /app/src/cardano-node
 ---> Using cache
 ---> da21c2428249
Step 25/80 : RUN cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd
 ---> Running in 3ebad85bb720
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] unknown package: cardano-cli (user goal)
[__0] fail (backjumping, conflict set: cardano-cli)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: cardano-cli

ERROR: Service 'cardano-graphql' failed to build : The command '/bin/sh -c cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd' returned a non-zero code: 1`

**Comment by Datiswaken** [comment]
Same issue as [here](https://github.com/input-output-hk/cardano-graphql/issues/416#issuecomment-771645142).
You have to add the `--recurse-submodules` option:
```
git clone \
  --single-branch \
  --branch <VERSION> \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
```
