### ISSUE TITLE
How to retrieve current epoch number using GraphQL API

### ISSUE THREAD

**Issue by kss-espeo** [input-output-hk/cardano-graphql#433]
Hi,

I would like to be able to programatically retrieve current epoch number in order to be able to use `/api/blocks/pages` method to retrieve blocks from the most recent epoch.

Context: I develop an app that does offchain analysis of blockchain data. It needs to first download all the blocks off the Cardano blockchain, and then be able to process blocks that are being added in the most recent epoch as quickly as possible.

**Comment by rhyslbw** [comment]
Hi @kss-espeo 
[This query](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/src/example_queries/cardano/chainTipAndCurrentEpochNumber.graphql) will get you the chain tip, however I would suggest considering [cardano-ogmios](https://github.com/KtorZ/cardano-ogmios) for your use-case, as rollbacks cannot be effectively handled by simply polling the tip. The API you're referring to (`/api/blocks/pages`) is in maintenance mode, and will be depreciated at some point, so best to avoid integrations with it.
