### ISSUE TITLE
Resource exhausted (Resource temporarily unavailable) error

### ISSUE THREAD

**Issue by devilus** [input-output-hk/cardano-graphql#434]
`curl   -X POST   -H "Content-Type: application/json"   -d '{"query": "{ cardanoDbMeta { initialized syncPercentage }}"}'   http://localhost:3100/graphql`

`{"errors":[{"message":"Error: \ncardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)","locations":[{"line":1,"column":3}],"path":["cardanoDbMeta"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Error: ","cardano-cli: Network.Socket.connect: <socket: 11>: resource exhausted (Resource temporarily unavailable)","    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:143:35)","    at Generator.throw (<anonymous>)","    at rejected (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:6:65)","    at runMicrotasks (<anonymous>)","    at processTicksAndRejections (internal/process/task_queues.js:93:5)"]}}}],"data":null}
`

After 2-5 attempts:
`{"data":{"cardanoDbMeta":{"initialized":true,"syncPercentage":100}}}`

And then again the same error. What could be the problem?

**Comment by rhyslbw** [comment]
Is this reproducible? It would help to know some more context as requested in the bug submission form:

https://github.com/input-output-hk/cardano-graphql/issues/new?assignees=&labels=&template=bug.md

**Comment by rhyslbw** [comment]
Closed in favour of #435
