### ISSUE TITLE
The Submit-api of cardano-rest is now deprecated. Is there an alternative api for cardano-graphql? Is the submitted format the same as cardano-rest?

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-graphql#439]
The Submit-api of cardano-rest is now deprecated. Is there an alternative api for cardano-graphql? Is the submitted format the same as cardano-rest?

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/src/example_queries/transactions/submitTransaction.graphql

`transaction` here is the value output in the `cborHex` property from `cardano-cli` build output. You can see it mapped here: 
https://github.com/input-output-hk/cardano-graphql/blob/3.2.0/packages/api-cardano-db-hasura/src/CardanoNodeClient.ts#L104-L108
