### ISSUE TITLE
The cardano-graphql use too much memroy after docker restart

### ISSUE THREAD

**Issue by lcgogo** [input-output-hk/cardano-graphql#440]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

After I stop the docker-compose and restart later, the cardano-graphql use more than 6GB memory
![图片](https://user-images.githubusercontent.com/8175573/109783126-9b4bf980-7c44-11eb-902d-0a106191bb9a.png)

My server is no responsing for about 10 mins, then back to work.

![图片](https://user-images.githubusercontent.com/8175573/109783786-55dbfc00-7c45-11eb-85b7-3e457167951a.png)

It should use less than 100MB memory as usual.

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 
18.04

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 
```console
cardano-graphal 3.2.0

docker version
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

### Steps to reproduce the bug
1. docker-compose down
2. wait some time
3. docker-compose up -d

### What is the expected behavior?

**Comment by rhyslbw** [comment]
This will be addressed in the next release. I'll let you know when the pre-release state can be used to remove this resource consumption
