### ISSUE TITLE
We need to field fingerprint in token schema

### ISSUE THREAD

**Issue by huynhngocmyibl** [input-output-hk/cardano-graphql#442]
Cardano native token need field **fingerprint** in token schema unique asset, we can't be distinguished by assetId
``` TOKEN
assetId | String!
assetName | String!
policyId | Hash28Hex!
fingerprint | String! (asset1xxx) please
quantity | String!
transactionOutput | TransactionOutput

**Comment by SebastienGllmt** [comment]
Although this is possibly just a temporary workaround for your issue, you can use https://www.npmjs.com/package/@emurgo/cip14-js to generate the fingerprint yourself.

**Comment by huynhngocmyibl** [comment]
SebastienGllmt your package can't implement with error ```AssetFingerprint is not a constructor

**Comment by SebastienGllmt** [comment]
Sounds like probably you didn't import the package properly and so `AssetFingerprint` is set to `undefined`

**Comment by huynhngocmyibl** [comment]
I resolved it, you was define constructor in a ``default`` property of object
const AssetFingerprint = require('@emurgo/cip14-js').default;

**Comment by rhyslbw** [comment]
It's been implemented in https://github.com/input-output-hk/cardano-graphql/pull/437, so will be included in the next release
