### ISSUE TITLE
Block and Asset requests fail with `Cannot query field "assets" on type "Query"`

### ISSUE THREAD

**Issue by ew-kislov** [input-output-hk/cardano-graphql#453]
I try query
```
query($ticker: String!) {
    assets(where: { ticker: { _eq: $ticker } }) {
      ticker
      assetName
      description
      fingerprint
      logo
      name
      url
    }
  }
```
and it fails with error that I mentioned in title. The same error for assets_aggregate, blocks, blocks_aggregate.
Please check it

**Comment by rhyslbw** [comment]
Best to stick to the latest released version: https://github.com/input-output-hk/cardano-graphql/releases

`4.0.0` with the `assets` query will be out this week.
