### ISSUE TITLE
Mint and Token Confusion

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#456]
The way the queries and tables were created is causing confusion in what they do.

E.g, When using Hasura I can see that there's a table called "Mint" which shows all the tokens that have been minted. Can we please have this exposed to GraphQL? As far as I can see, there isn't a reliable way of retrieving all the minted tokens with the correct quantities while using the "token" interface/table. E.g, you can do a distinct, but you can't order it by includedAt, so any selected "distinct" isn't guaranteed to be the minted transaction. Exposing "Mint" would solve this.

GraphQL has the "tokens" table exposed however this isn't a unique set of tokens and is actually all the transactions that have happened against a token. I feel like it would be more appropriate to call it token_transactions and token_transactions_aggregate.

**Comment by rhyslbw** [comment]
Yes you're right @CyberCyclone , the mint table is a closer match for resolving a query called `tokens`. 

> I feel like it would be more appropriate to call it token_transactions and token_transactions_aggregate.

Given the current results are only relevant in the context of transactions, I'll just change the SQL queries to resolve from `mint` instead as we only really care about the minting and or burning of tokens in this context.

**Comment by CyberCyclone** [comment]
The approach in the release of 4.0.0 works a lot better now. Thanks!
