### ISSUE TITLE
Heads up about new major version of set-interval-async

### ISSUE THREAD

**Issue by ealmansi** [input-output-hk/cardano-graphql#459]
Hi @rhyslbw,

A new version of set-interval-async is available with improvements on error handling and including a bug fix. You may see the changes in more detail in the [release notes](https://github.com/ealmansi/set-interval-async/releases/tag/v2.0.0).

I'm reaching out because I noticed an instance of the following pattern in your project ([link](https://github.com/input-output-hk/cardano-graphql/blob/96aa7088de16134808758fc97775569121ab253b/packages/server/src/Server.ts#L118)), which may lead to undesired results:

```javascript
const timer = setIntervalAsync(async () => {
  // ...
  if (/* some condition */) {
    await clearIntervalAsync(timer);
  }
}, interval);
```

The code above generates a chaining promise cycle which never resolves, because:
- `await clearIntervalAsync(timer)` will not resolve until the last execution has finished, AND
- the last execution will not finish until `await clearIntervalAsync(timer)` has been resolved.

Simply not awaiting `clearIntervalAsync` may be enough to avoid this issue, but the right solution will depend on your application's requirements. This didn't surface earlier due to the bug in set-interval-async that has now been fixed in the latest major version.

Best,
Emilio

**Comment by rhyslbw** [comment]
Thanks for the notification and walk-through @ealmansi. I'll move to the new version and fix this logic
