### ISSUE TITLE
how do I listen to the new block number or epoch number on Cardano via my local node

### ISSUE THREAD

**Issue by gitloverr** [input-output-hk/cardano-graphql#460]
Hi everyone,

I set the Cardano-graphql  via docker images, and my node synced now. I want to listen to the new block number broadcast on the network from my node.js api  via using a web socket or similar way. how do i do this?  I got the last block number with qraphql query, but I want to know if the new block is published....

can you help me?

thank you

**Comment by rhyslbw** [comment]
Hi @gitloverr
There are currently no subscriptions offered over the `cardano-graphq` API, however you can setup a live query via the Hasura interface directly to achieve a push-based interaction. The service is [mapped to the host on port 8080](https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L79) 

https://hasura.io/docs/latest/graphql/core/databases/postgres/subscriptions/index.html

**Comment by gitloverr** [comment]
thank you!
