### ISSUE TITLE
Cannot read property 'major' of undefined

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-graphql#462]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

4.0.0

#### Platform

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 
```console
node -v
docker version
```

### Steps to reproduce the bug

curl --location --request POST 'http://127.0.0.1:3100/graphql' --header 'Content-Type: application/json' --data-raw '{"query":"mutation SendRawTx($rawtx: String!) {\n\tsubmitTransaction(transaction: $rawtx) {\n\t  hash\n\t}\n  }","variables":{"rawtx":"83A30081825820CDE0B166727111FE0EA0513FD971854624DAB6D0AA41F48F3EA3CC40E52F925900018282584C82D818584283581C345BB97BE6C3E95585DD9D49C30AD523FDCDC9C8939D4AFB1A66C7B4A101581E581C83D3E2DF30EDF9004C127B8571DF0BEB870AD12ADC9CAB8FBD46EF3C001A07C614B1821A0B0B3BAFA082582B82D818582183581C9E8AB503AFBB9D83256BA7E9D5C5B1FD7BE4383C526418A112C899C3A0001A6724EE00821A00C8C9E2A0021A00030D40A100818258200E5841DC0B723F94729E9058696EAADC2FBB0580047A820FDDF4DE4927FBBFD358405E9213B8E1F85ECE3424CCAAE616C422FEB0790079825A77BCB1C1DE18346D3E8DFCE5904ED5F55F5BC8AB1FDBD4C85CC6DBB7E79D26CA63DFA212FC598D6F0EF6"}}'

{"errors":[{"message":"Cannot read property 'major' of undefined","locations":[{"line":2,"column":2}],"path":["submitTransaction"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Cannot read property 'major' of undefined","    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:605:65)","    at Generator.next (<anonymous>)","    at /app/packages/api-cardano-db-hasura/dist/HasuraClient.js:27:71","    at new Promise (<anonymous>)","    at __awaiter (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:23:12)","    at HasuraClient.isInCurrentEra (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:599:16)","    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:44:38)","    at Generator.next (<anonymous>)","    at /app/packages/api-cardano-db-hasura/dist/executableSchema.js:8:71","    at new Promise (<anonymous>)"]}}}],"data":null}

### What is the expected behavior?

**Comment by vae520283995** [comment]
I used cardano-rest to broadcast transactions normally. When I learned that cardano-rest will be deprecated, I use cardano-graphql, but it cannot broadcast.
`{
  "errors": [
    {
      "message": "Cannot read property 'major' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "submitTransaction"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'major' of undefined",
            "    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:605:65)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/HasuraClient.js:27:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:23:12)",
            "    at HasuraClient.isInCurrentEra (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:599:16)",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:44:38)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/executableSchema.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}`

**Comment by rhyslbw** [comment]
Looking into this now

**Comment by rhyslbw** [comment]
Did you rebuild the data store @islishude and @vae520283995, following https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db ?
The error being reported here is indicative of this not being done, or that the sync has not made it into the current era.

**Comment by islishude** [comment]
I deleted all postgres data before upgrading to 4.0.0.

> cardao-db-sync:9.0.0 This release requires the database to be dropped and recreated. https://github.com/input-output-hk/cardano-db-sync/releases/tag/9.0.0

**Comment by islishude** [comment]
> or that the sync has not made it into the current era.

I can confirm that the node and db-sync has been synchronized with the latest height blocks

**Comment by vae520283995** [comment]
> Did you rebuild the data store @islishude and @vae520283995, following https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db ?
> The error being reported here is indicative of this not being done, or that the sync has not made it into the current era.

I deleted all the data, resynchronized, and the synchronization is complete
`{
  "data": {
    "cardanoDbMeta": {
      "initialized": true,
      "syncPercentage": 100
    }
  }
}`

**Comment by rhyslbw** [comment]
> I deleted all postgres data before upgrading to 4.0.0

I've just updated the instructions to cover the second volume that must be dropped too.
https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db

> I can confirm that the node and db-sync has been synchronized with the latest height blocks
> I deleted all the data, resynchronized, and the synchronization is complete

Are you still having this issue? If so please run with debug logging enabled and paste the logs: `LOGGER_MIN_SEVERITY=debug`

**Comment by islishude** [comment]
> I've just updated the instructions to cover the second volume that must be dropped too.

I deleted before all the data of db-sync and postgres

**Comment by islishude** [comment]
> Are you still having this issue? If so please run with debug logging enabled and paste the logs: `LOGGER_MIN_SEVERITY=debug`

can't you reproduce the bug on your end?

**Comment by vae520283995** [comment]
> I've just updated the instructions to cover the second volume that must be dropped too.
> https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db

root@ip-172-31-38-16:/data/cardano-graphql/cardano-graphql-v4.0.0/cardano-graphql# docker-compose ps -a
Name   Command   State   Ports
------------------------------
root@ip-172-31-38-16:/data/cardano-graphql/cardano-graphql-v4.0.0/cardano-graphql# docker volume ls
DRIVER              VOLUME NAM

I cleared all the data, starting from 0, still the same error

**Comment by MarcelKlammer** [comment]
I also get this bug. Fresh AWS instance. Fresh 4.0.0 installation.

```
query {
  cardano {
    tip {
      epochNo
      number
    }
  }
  
  ada {
    
    supply {
      
      circulating
    }
  }
}
```

results in

```
{
  "errors": [
    {
      "message": "Cannot read property 'major' of undefined",
      "locations": [
        {
          "line": 8,
          "column": 3
        }
      ],
      "path": [
        "ada"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'major' of undefined",
            "    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:605:65)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/HasuraClient.js:27:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:23:12)",
            "    at HasuraClient.isInCurrentEra (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:599:16)",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:44:38)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/executableSchema.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by rhyslbw** [comment]
@MarcelKlammer are you able to run with `LOGGER_MIN_SEVERITY=debug` ?

**Comment by vae520283995** [comment]
I upgraded cardano-node to 1.26.1 and it succeeded
`
{
  "data": {
    "submitTransaction": {
      "hash": "f0d8df8bb2a9c223c22c5097fe75085ba866db7947c5dde7fa1dd934b7b8003f"
    }
  }
}
`

**Comment by vae520283995** [comment]
> I upgraded cardano-node to 1.26.1 and it succeeded
> `{ "data": { "submitTransaction": { "hash": "f0d8df8bb2a9c223c22c5097fe75085ba866db7947c5dde7fa1dd934b7b8003f" } } }`

@rhyslbw Is there a bug in cardano-node v1.25.1?

**Comment by rhyslbw** [comment]
> Is there a bug in cardano-node v1.25.1?

No, the reported error is not related to `cardano-node`. Did you restart the stack without rebuilding prior to upgrading @vae520283995 ?

**Comment by jbpin** [comment]
I had a similar issue. I fix it by opening Hasura console and follow instruction to resync all table. In case it can help..

**Comment by rhyslbw** [comment]
> I had a similar issue. I fix it by opening Hasura console and follow instruction to resync all table. In case it can help..

Thanks for the suggestion @jbpin , but that just indicates rebooting the `cardano-graphql` service would have resolved this as it manages the schema migration on startup.

**Comment by vae520283995** [comment]
> No, the reported error is not related to `cardano-node`. Did you restart the stack without rebuilding prior to upgrading @vae520283995 ?

When I downgraded to 1.25.1 and then reported an error again, I upgraded to 1.26.1 again, still reporting an error, I don't know why, every time I execute docker-compose down -v and then clear all data

**Comment by rhyslbw** [comment]
You should never have to run `docker-compose down -v` as that will require a complete build from scratch, including `cardano-node`. Once synced, `docker-compose restart` should resolve any issues

**Comment by vae520283995** [comment]
> You should never have to run `docker-compose down -v` as that will require a complete build from scratch, including `cardano-node`. Once synced, `docker-compose restart` should resolve any issues

It can work normally after executing docker-compose restart, is this a code bug?

**Comment by islishude** [comment]
> You should never have to run `docker-compose down -v` as that will require a complete build from scratch, including `cardano-node`. Once synced, `docker-compose restart` should resolve any issues

**Comment by CherryDT** [comment]
I have the same problem. Fresh install. Sync completed. `docker-compose restart` doesn't change anything.

**Comment by CherryDT** [comment]
Any news on this? It's happening even in 5.0.0.

```json
{
  "errors": [
    {
      "message": "Cannot read property 'major' of undefined",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "paymentAddresses"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: Cannot read property 'major' of undefined",
            "    at HasuraClient.<anonymous> (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:501:61)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/HasuraClient.js:27:71",
            "    at new Promise (<anonymous>)",
            "    at __awaiter (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:23:12)",
            "    at HasuraClient.isInCurrentEra (/app/packages/api-cardano-db-hasura/dist/HasuraClient.js:496:16)",
            "    at Object.<anonymous> (/app/packages/api-cardano-db-hasura/dist/executableSchema.js:46:38)",
            "    at Generator.next (<anonymous>)",
            "    at /app/packages/api-cardano-db-hasura/dist/executableSchema.js:8:71",
            "    at new Promise (<anonymous>)"
          ]
        }
      }
    }
  ],
  "data": {
    "paymentAddresses": null
  }
}
```
