### ISSUE TITLE
Installation: Identity Faield to start all required subscriptions

### ISSUE THREAD

**Issue by jkain88** [input-output-hk/cardano-graphql#463]
![cardano-error (2)](https://user-images.githubusercontent.com/36409853/113135107-4b1c8300-9254-11eb-9436-2908cf2a3fd7.png)

Steps:

`git clone \
  --single-branch \
  --branch 4-0-stable \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql`
  
Then

`docker-compose up -d --build && docker-compose logs -f`

Not sure if I just did something wrong

OS : WSL Ubuntu-20.04
Docker version: Docker version 20.10.3, build 48d30b5

**Comment by rhyslbw** [comment]
1. Is this not running in WIndows rather than the WSL? the `hasura` container is failing due to invalid line endings.
2. The `cardano-db-sync-extended` error is can occur on startup, but it should resolve eventually.
