### ISSUE TITLE
cardano-graphql_1 crash - Host for metadata server does not exist

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#464]
### Steps to reproduce the bug

Using cardano-graphql 4.0.0 seems have the cardano-graphql_1 service crash about every 20 seconds and the below error message comes up:

```
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"b5c42d77194d","pid":1,"level":50,"msg":"Host for metadata server does not exist","time":"2021-04-02T00:54:05.406Z","v":0}
cardano-graphql_cardano-graphql_1 exited with code 1
```

![image](https://user-images.githubusercontent.com/4373888/113368623-9f357d80-93a2-11eb-92ca-e39b881b31b8.png)

While I've had cardano-graphql:4.0.0 running for a few days (I updated and started the db rebuild a few hours after the 4.0.0 release), it's only become evident about the bug because I poll ```{ cardano { tip { number slotNo epoch { number } } } }``` every second to display the most up-to-date "tip". While I doubt this fact is relevant to the bug itself, it means that the tip isn't always retrieved since the graphql service has died and is returning an error (and takes about another 20 seconds to restart).

I've replicated this on my local machine and also an offline production server for ADATools.io.

### What is the expected behavior?
I'm not sure if it's by deliberate design that the graphql server will crash as that takes down the entire API. I'm also not sure what the correlation is for the metadata server (either it's grabbing data on the fly from the server or its gathering the data when the token populates in the db). Either way, I feel like the entire API going down is overkill.

**Seperate Question:**
Is ```ARG METADATA_SERVER_URI="https://tokens.cardano.org"``` this project: https://github.com/input-output-hk/metadata-server? If so, I'd rather run my own token/metadata server instead of depending on cardanos.

**Comment by CyberCyclone** [comment]
I just noticed that there's several references to ```METADATA_SERVER_URI``` throughout cardano-graphql. In the docker-compose file it's referencing ```- METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://metadata.cardano.org/metadata}``` and that server is in fact down as of now.

The docker file has this line: ```ARG METADATA_SERVER_URI="https://tokens.cardano.org"```. It's easy to get confused with the same variable names.

**Comment by rhyslbw** [comment]
> I'm not sure if it's by deliberate design that the graphql server will crash as that takes down the entire API. 

The design is to exit on startup if the configured host is not immediately available, but not crash if the metadata service is unreachable after this initial check. Better thought of as not starting if the configuration is likely invalid, although I can appreciate in this case there could have been an outage

> I'm also not sure what the correlation is for the metadata server (either it's grabbing data on the fly from the server or its gathering the data when the token populates in the db).

The latter.

> Is ARG METADATA_SERVER_URI="https://tokens.cardano.org" this project: https://github.com/input-output-hk/metadata-server? If so, I'd rather run my own token/metadata server instead of depending on cardanos.

It is, but this is just the default you can override by setting the env. Policy owners submit metadata to the registry though, so it's not just a matter of running infrastructure unless you're planning to sync all records.

> The docker file has this line: ARG METADATA_SERVER_URI="https://tokens.cardano.org", and this one seems to be up. It's easy to get confused with the same variable names.

Ah yes that wasn't updated when the URL changed. I'll issue a patch, but for now replacing `https://metadata.cardano.org/metadata` with `https://tokens.cardano.org` will work.

**Comment by CyberCyclone** [comment]
Thanks for that @rhyslbw, so by design it's doing exactly what it's meant to do.

I can confirm that swapping ```https://metadata.cardano.org/metadata``` with ```https://tokens.cardano.org``` in the docker-compose file fixes the crash.

I'll leave this open until it's been patched.

**Comment by rhyslbw** [comment]
I've pushed a fix to `master` but will wait until next week to release the patch since this can be worked around at runtime by setting `METADATA_SERVER_URI` to `https://tokens.cardano.org`

**Comment by rhyslbw** [comment]
Also added https://github.com/input-output-hk/cardano-graphql/wiki/Configuration#metadata_server_uri to the Wiki. Thanks for the prompt

**Comment by rhyslbw** [comment]
The release branch has been made, and we'll be tagging once final QA checks are performed: 
https://github.com/input-output-hk/cardano-graphql/tree/5-0-stable
