### ISSUE TITLE
Create NFT

### ISSUE THREAD

**Issue by jkain88** [input-output-hk/cardano-graphql#471]
Can I create NFT through this?

**Comment by rhyslbw** [comment]
The API support submitting a serialised transaction to the local node which can contain minted tokens. What behaviour are you looking for here?

**Comment by jkain88** [comment]
@rhyslbw we plan to create a website that enables users to mint their own tokens. we want to take advantage of this using graphql

**Comment by rhyslbw** [comment]
Have you had a read of https://docs.cardano.org/en/latest/native-tokens/learn-about-native-tokens.html ? You can submit transactions with the API, but creating policies and minting is a client-side operation, or at least sits within the application scope.
