### ISSUE TITLE
[bug] "ada results are only available when close to the network tip. This is expected during the initial chain-sync.

### ISSUE THREAD

**Issue by MarcelKlammer** [input-output-hk/cardano-graphql#473]
### Environment

{
  os: {
    arch: 'x64',
    cpus: {
      count: 8,
      model: 'Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz'
    },
    release: '5.4.0-1038-aws',
    totalMem: 21455163392,
    type: 'Linux'
  },
  version: '4.0.0'
}

#### Platform

- [x] Linux / Ubuntu 20.04 LTS

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 

node -v
v14.16.0

docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:18:20 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:15 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Steps to reproduce the bug

In any *guild* graphql playground running v4.0.0, paste:

```
query {
  cardano {
    tip {
      epochNo
      number
    }
  }

  cardanoDbMeta {
    initialized
    syncPercentage
  }

  ada {
    supply {
      total
    }
  }
}

```

The guild network has a 1 hour epoch length. The setup is on tip. No question about it. The ada supply should be queriable, but it isn't.

### What is the expected behavior?

No error.

**Comment by rhyslbw** [comment]
What do you get from thew following?:

```graphql
query {
  cardanoDbMeta {
    initialized
    syncPercentage
  }
```

**Comment by MarcelKlammer** [comment]
I got true and 100%.

I'm switching to postgREST and rpc functions for now and might give it a shot later again.
