### ISSUE TITLE
Many errors on docker installation

### ISSUE THREAD

**Issue by aleincsharp** [input-output-hk/cardano-graphql#475]
Hello to all,

i've already tried to install in several ways (blank from source on lxc, docker compose, yarn) but i am still encountering following errors (last installed with docker on lxc).

I am thankful for any help, Arthur.

**Cardano-node:**
`cardano-node_1              | [0567b65f:cardano.node.ChainDB:Notice:307] [2021-04-08 20:53:36.26 UTC] Chain extended, new tip: 643a48cb8ca0b92da2f77baabd1ca7250893f2126be759eaa9feb08acad6bd26 at slot 26348925
cardano-node_1              | [0567b65f:cardano.node.LocalErrorPolicy:Error:324] [2021-04-08 20:53:44.15 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 30> closed when reading data, waiting on next header True")
cardano-node_1              | [0567b65f:cardano.node.ChainDB:Notice:307] [2021-04-08 20:53:46.17 UTC] Chain extended, new tip: 38ae1f0b662ea78a60a75ba7f2ff03589381fbec33d451901f013136c1b46a68 at slot 26348935
cardano-node_1              | [0567b65f:cardano.node.ChainDB:Info:88963] [2021-04-08 20:53:48.05 UTC] before next, messages elided = 5736328675869759
cardano-node_1              | [0567b65f:cardano.node.ChainDB:Info:88963] [2021-04-08 20:53:48.05 UTC] Ignoring block already in DB: 38ae1f0b662ea78a60a75ba7f2ff03589381fbec33d451901f013136c1b46a68 at slot 26348935
cardano-node_1              | [0567b65f:cardano.node.LocalErrorPolicy:Error:324] [2021-04-08 20:53:54.16 UTC] IP LocalAddress "" ErrorPolicyUnhandledApplicationException (MuxError MuxBearerClosed "<socket: 24> closed when reading data, waiting on next header True")`

**cardano-db-sync-extended**
`cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:46] [2021-04-08 20:59:33.45 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:46] [2021-04-08 20:59:34.64 UTC] Identity Restarting Subscription after 1.221642607s desired valency 1 current valency 0
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:46] [2021-04-08 20:59:43.43 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:17201] [2021-04-08 20:59:43.43 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:17201] [2021-04-08 20:59:43.43 UTC] Identity Connection Attempt End, destination LocalAddress "/node-ipc/node.socket" outcome: ConnectSuccessLast
cardano-db-sync-extended_1  | [db-sync-node.Handshake:Info:17201] [2021-04-08 20:59:43.43 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073)]))
cardano-db-sync-extended_1  | [db-sync-node.Handshake:Info:17201] [2021-04-08 20:59:43.43 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_8 (TInt 764824073))
cardano-db-sync-extended_1  | [db-sync-node.Mux:Info:17201] [2021-04-08 20:59:43.43 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Handshake Client end, duration 0.000506936s
cardano-db-sync-extended_1  | [db-sync-node.Mux:Info:17202] [2021-04-08 20:59:43.43 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Mature
cardano-db-sync-extended_1  | [db-sync-node:Info:17205] [2021-04-08 20:59:43.43 UTC] Starting chainSyncClient
cardano-db-sync-extended_1  | [db-sync-node:Error:17205] [2021-04-08 20:59:43.43 UTC] ChainSyncWithBlocksPtcl: libpq: failed (no connection to the server
cardano-db-sync-extended_1  | )
cardano-db-sync-extended_1  | [db-sync-node.Mux:Info:17202] [2021-04-08 20:59:43.43 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Dead
cardano-db-sync-extended_1  | [db-sync-node.Mux:Notice:17202] [2021-04-08 20:59:43.43 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Miniprotocol MiniProtocolNum 5 InitiatorDir terminated with exception libpq: failed (no connection to the server
cardano-db-sync-extended_1  | )
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:17201] [2021-04-08 20:59:43.43 UTC] Identity Application Exception: LocalAddress "/node-ipc/node.socket" libpq: failed (no connection to the server
cardano-db-sync-extended_1  | )
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Error:4] [2021-04-08 20:59:43.43 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicyUnhandledApplicationException libpq: failed (no connection to the server
cardano-db-sync-extended_1  | )
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:46] [2021-04-08 20:59:43.45 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:46] [2021-04-08 20:59:44.71 UTC] Identity Restarting Subscription after 1.284401106s desired valency 1 current valency 0`

**postgres:**
`postgres_1                  | 2021-04-08 21:00:16.627 UTC [15771] ERROR:  relation "public.Epoch" does not exist at character 296
postgres_1                  | 2021-04-08 21:00:16.627 UTC [15771] STATEMENT:  SELECT  coalesce(json_agg("root" ORDER BY "root.pg.number" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."number" AS "number"       ) AS "_1_e"      ) ) AS "root", "_0_root.base"."number" AS "root.pg.number" FROM  (SELECT  *  FROM "public"."Epoch"  WHERE ('true')     ) AS "_0_root.base"    ORDER BY "root.pg.number" DESC NULLS FIRST LIMIT 1 ) AS "_2_root"      
postgres_1                  | 2021-04-08 21:00:21.630 UTC [15771] ERROR:  relation "public.Epoch" does not exist at character 296
postgres_1                  | 2021-04-08 21:00:21.630 UTC [15771] STATEMENT:  SELECT  coalesce(json_agg("root" ORDER BY "root.pg.number" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."number" AS "number"       ) AS "_1_e"      ) ) AS "root", "_0_root.base"."number" AS "root.pg.number" FROM  (SELECT  *  FROM "public"."Epoch"  WHERE ('true')     ) AS "_0_root.base"    ORDER BY "root.pg.number" DESC NULLS FIRST LIMIT 1 ) AS "_2_root"      
postgres_1                  | 2021-04-08 21:00:58.658 UTC [15771] ERROR:  relation "public.Epoch" does not exist at character 296
postgres_1                  | 2021-04-08 21:00:58.658 UTC [15771] STATEMENT:  SELECT  coalesce(json_agg("root" ORDER BY "root.pg.number" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."number" AS "number"       ) AS "_1_e"      ) ) AS "root", "_0_root.base"."number" AS "root.pg.number" FROM  (SELECT  *  FROM "public"."Epoch"  WHERE ('true')     ) AS "_0_root.base"    ORDER BY "root.pg.number" DESC NULLS FIRST LIMIT 1 ) AS "_2_root"      
postgres_1                  | 2021-04-08 21:01:03.644 UTC [15771] ERROR:  relation "public.Epoch" does not exist at character 296
postgres_1                  | 2021-04-08 21:01:03.644 UTC [15771] STATEMENT:  SELECT  coalesce(json_agg("root" ORDER BY "root.pg.number" DESC NULLS FIRST), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."number" AS "number"       ) AS "_1_e"      ) ) AS "root", "_0_root.base"."number" AS "root.pg.number" FROM  (SELECT  *  FROM "public"."Epoch"  WHERE ('true')     ) AS "_0_root.base"    ORDER BY "root.pg.number" DESC NULLS FIRST LIMIT 1 ) AS "_2_root" `

**hasura:**
`hasura_1                    | {"type":"http-log","timestamp":"2021-04-08T21:01:40.553+0000","level":"info","detail":{"operation":{"query_execution_time":8.81291e-4,"user_vars":{"x-hasura-role":"admin"},"request_id":"2ebec07a-0c6d-4ead-8a87-a89c6d679c54","response_size":68,"request_read_time":2.728e-6},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/query","ip":"172.18.0.2","method":"POST","content_encoding":"gzip"}}}
hasura_1                    | {"type":"http-log","timestamp":"2021-04-08T21:01:45.883+0000","level":"error","detail":{"operation":{"user_vars":{"x-hasura-role":"cardano-graphql"},"error":{"internal":{"statement":"SELECT  coalesce(json_agg(\"root\" ORDER BY \"root.pg.number\" DESC NULLS FIRST), '[]' ) AS \"root\" FROM  (SELECT  row_to_json((SELECT  \"_1_e\"  FROM  (SELECT  \"_0_root.base\".\"number\" AS \"number\"       ) AS \"_1_e\"      ) ) AS \"root\", \"_0_root.base\".\"number\" AS \"root.pg.number\" FROM  (SELECT  *  FROM \"public\".\"Epoch\"  WHERE ('true')     ) AS \"_0_root.base\"    ORDER BY \"root.pg.number\" DESC NULLS FIRST LIMIT 1 ) AS \"_2_root\"      ","prepared":true,"error":{"exec_status":"FatalError","hint":null,"message":"relation \"public.Epoch\" does not exist","status_code":"42P01","description":null},"arguments":["(Oid 114,Just (\"{\\\"x-hasura-role\\\":\\\"cardano-graphql\\\"}\",Binary))"]},"path":"$","error":"database query error","code":"unexpected"},"request_id":"556e16ce-83fa-4f2b-bb14-42f2104a6e60","response_size":802,"query":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              number\n          }\n          cardano {\n              tip {\n                  epoch {\n                      number\n                  }\n                  number\n                  forgedAt\n              }\n          }}"}},"http_info":{"status":200,"http_version":"HTTP/1.1","url":"/v1/graphql","ip":"172.18.0.2","method":"POST","content_encoding":null}}}`

**cardano-graphql:**
`cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"GraphQL HTTP server at http://0.0.0.0:3100/ started","time":"2021-04-08T21:00:53.612Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"DB ready","time":"2021-04-08T21:01:18.660Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-04-08T21:01:28.712Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-04-08T21:01:28.712Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":50,"msg":"Host for metadata server does not exist","time":"2021-04-08T21:01:39.273Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-04-08T21:01:40.449Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"GraphQL HTTP server at http://0.0.0.0:3100/ started","time":"2021-04-08T21:01:40.832Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"DB ready","time":"2021-04-08T21:02:05.883Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-04-08T21:02:16.309Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-04-08T21:02:16.310Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":50,"msg":"Host for metadata server does not exist","time":"2021-04-08T21:02:27.054Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-04-08T21:02:28.224Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"GraphQL HTTP server at http://0.0.0.0:3100/ started","time":"2021-04-08T21:02:28.590Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"DB ready","time":"2021-04-08T21:02:48.628Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-04-08T21:03:03.879Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"cb8d94279fec","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-04-08T21:03:03.880Z","v":0}`

**Comment by rhyslbw** [comment]
Hi @aleincsharp . 

I'll close this in favour of #464

Prior to the patch you can set `METADATA_SERVER_URI` to `https://tokens.cardano.org`
