### ISSUE TITLE
Staging Continuous Deployment

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/cardano-graphql#48]
When creating a release we should update our running task definition to use these most recent containers.

This will probably be achieved best with a `deploy.js` that leverages the aws-sdk to describe the currently running task, and apply updates to the container version of task defs.

**Comment by rhyslbw** [comment]
Requires upstream services Docker image CD (in progress)

**Comment by rhyslbw** [comment]
Moved to backlog
