### ISSUE TITLE
feature request: Support basic auth credentials in playground

### ISSUE THREAD

**Issue by CherryDT** [input-output-hk/cardano-graphql#486]
I am running the docker-based `cardano-graphql` setup on a non-public server, and for that reason I have Caddy in front of it which not only handles SSL termination but also adds HTTP basic auth.

This works great in general but I haven't found a way yet to make the playground usable.

With a URL without credentials, it seems the credentials are not forwarded (probably the request is missing the `credentials` init config) and I get a 401. With a URL _with_ credentials, I get an error `Failed to execute 'fetch' on 'Window': Request cannot be constructed from a URL that includes credentials`.

It would be perfect if the existing credentials would be used, by passing `credentials: 'include'` to `fetch`'s init options.

**Comment by rhyslbw** [comment]
> This works great in general but I haven't found a way yet to make the playground usable.

Does the Playground UI load, but the queries fail? Try this:

https://github.com/graphql/graphql-playground/issues/680
