### ISSUE TITLE
Docker does not seem to work properly.(db-sync-node.Subscription:Error)

### ISSUE THREAD

**Issue by vadym-skoryk** [input-output-hk/cardano-graphql#497]
For the last several days, I have been trying to set up cardano-graphql by using docker. 
The hosting server is Ubuntu 20.04 and the latest docker was used.
I used the 4.0.0 stable version and I followed your guide but it does not seem to work. 
I changed METADATA_SERVER_URI from `https://metadata.cardano.org/metadata` with `https://tokens.cardano.org` and then tried again but the same error occurred.
How can I figure it out?
Please help me.

![image](https://user-images.githubusercontent.com/74002705/117989467-056bd380-b345-11eb-95ec-68f04282b478.png)

**Comment by vadym-skoryk** [comment]
I tested 3.2.0 version but same issues.
Could someone help me?

![image](https://user-images.githubusercontent.com/74002705/118116479-ffccc700-b3f2-11eb-9c69-1f631ac04c93.png)

**Comment by rhyslbw** [comment]
Have you left it running? This error originates from a service dependency, and is expected during the startup sequence as `cardano-node` only creates the socket after verifying some internal state.

**Comment by vadym-skoryk** [comment]
Thank you for your reply.
I already stopped 4.0.0. In that case, I have waited for 1 day from it happened but seemed to show the same issue.
3.2.0 is still running now but not sure really if it works.
Should I wait for more?
My hosting server spec is Ubuntu 20.04, 4vCPUs, 8G RAM, 160GB. 
How long will it take to get ready to use approximately?

**Comment by rhyslbw** [comment]
I would try starting from scratch with `4.0.0`. Did you clone the release tag?

```console
git clone \
  --single-branch \
  --branch 4.0.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
  ```
  
  In addition to the volumes listed [here](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db), remove `cardano-graphql_node-ipc` too.

**Comment by vadym-skoryk** [comment]
sure I did.

like that
```
git clone \
  --single-branch \
  --branch 4.0.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
```
  
```
git clone \
  --single-branch \
  --branch 3.2.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
```

**Comment by vadym-skoryk** [comment]
I tried 3.2.0 and 4.0.0 on several ubuntu servers but never work. The stable version doesn't seem to work properly. Can you improve the ReadMe if there are some missing?

**Comment by rhyslbw** [comment]
There will be a new release once `cardano-db-sync@10.0.0` is out, but you can try the `master` branch now.

**Comment by rhyslbw** [comment]
The release branch has been made, and we'll be tagging once final QA checks are performed: 
https://github.com/input-output-hk/cardano-graphql/tree/5-0-stable
