### ISSUE TITLE
Running cardano-db-sync-extended docker container

### ISSUE THREAD

**Issue by ShiningPikachu** [input-output-hk/cardano-graphql#501]
I see in this docker-compose.yml file the service for the `cardano-db-sync` is set the `extended` mode in the name, however the image is set to the normal `cardano-db-sync` and I could not find a `cardano-db-sync-extended` docker image on their registry anywhere.

Additionally I looked at the config file here: https://github.com/input-output-hk/cardano-graphql/blob/master/config/network/mainnet/cardano-db-sync/config.json
as I suspected that might have an indication of the extended mode somewhere. However, I couldn't find any reference to the extended db sync build.

Should we be building the `cardano-db-sync-extended` process and running non-dockerized for now?

**Comment by ShiningPikachu** [comment]
This is the docker-compose.yml file: https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml

**Comment by erikd** [comment]
The config file for the standard and extended `db-sync` are the same.

**Comment by ShiningPikachu** [comment]
RIght, but where is the indication that the service in this docker-compose.yml file is the extended mode? I'm trying to figure out where that configuration is set.

**Comment by ShiningPikachu** [comment]
Ugh, apologize, I completely missed this environment variable in the docker-compose.yml file. 

https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml#L54

Will close this.
