### ISSUE TITLE
Cardano GraphQL Node DNSSubscriptionError

### ISSUE THREAD

**Issue by rajqumar** [input-output-hk/cardano-graphql#504]
I am running cardano-graphql in docker environment where it also runs node, It synced almost for 4-5 hours after that I started getting these errors

`cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:34] [2021-05-27 05:49:15.06 UTC] [String "Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)",String "SubscriptionTrace"]`

`cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2021-05-27 05:49:15.06 UTC] [String "ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 12>: does not exist (Connection refused))) 20s 20s",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"/node-ipc/node.socket\"}"]
cardano-node_1              | Listening on http://127.0.0.1:12798
cardano-node_1              | 
cardano-node_1              | cardano-node: FatalError {fatalErrorMessage = "Cardano.Node.Run.createTracers.readTopologyFile: Is your topology file formatted correctly? The port and valency fields should be numerical. Error in $: empty"}cardano-graphql_cardano-node_1 exited with code 1`

`cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:36] [2021-05-27 05:49:25.06 UTC] [String "Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)",String "SubscriptionTrace"]`

`cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2021-05-27 05:49:25.06 UTC] [String "ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 12>: does not exist (Connection refused))) 20s 20s",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"/node-ipc/node.socket\"}"]`

`cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:38] [2021-05-27 05:49:35.07 UTC] [String "Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)",String "SubscriptionTrace"]`

`cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2021-05-27 05:49:35.07 UTC] [String "ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 12>: does not exist (Connection refused))) 20s 20s",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"/node-ipc/node.socket\"}"]`

`cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:40] [2021-05-27 05:49:45.08 UTC] [String "Connection Attempt Exception, destination LocalAddress {getFilePath = \"/node-ipc/node.socket\"} exception: Network.Socket.connect: <socket: 12>: does not exist (Connection refused)",String "SubscriptionTrace"]`

`cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:4] [2021-05-27 05:49:45.08 UTC] [String "ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 12>: does not exist (Connection refused))) 20s 20s",String "ErrorPolicyTrace",String "LocalAddress {getFilePath = \"/node-ipc/node.socket\"}"]
cardano-node_1              | Listening on http://127.0.0.1:12798
`

**Comment by james-iohk** [comment]
Hi @rajqumar. This looks like the node is unable to deserialise the topology json file because is empty. May you confirm that the node container's volume still exists and has the correct `/config/topology.json` file?

**Comment by rajqumar** [comment]
@james-iohk Yes the node is running fine, and topology.json has been updated from the provided config
