### ISSUE TITLE
Step 25/82 : RUN cabal install cardano-cli   --install-method=copy   --installdir=/usr/local/bin   -f -systemd  ---> Running in 3079c85bb6ed

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#509]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [x] Docker

**Runtime version**: 
```console
node -v
docker version
```

### What is the expected behavior?

**Comment by malingzhao** [comment]
It don't work after this . My Machine is 8C 16 G

**Comment by rhyslbw** [comment]
Sounds like you're missing the git submodule. Please follow instructions in the [Readme](https://github.com/input-output-hk/cardano-graphql#getting-started)

**Comment by malingzhao** [comment]
I  do like this ,When I use 2-2 -stable , it is successful

**Comment by malingzhao** [comment]
but when I do it use 4-2-stable, It But stuck

**Comment by rhyslbw** [comment]
Please provide the logs

**Comment by malingzhao** [comment]
oh, It's need how long

**Comment by malingzhao** [comment]
it come on

**Comment by malingzhao** [comment]
rote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-api-1.25.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-api-test-1.24.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-cli-1.25.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-config-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-node-1.25.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-node-chairman-1.25.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/hedgehog-extras-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-slotting-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-tests-2.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-praos-2.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-class-2.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-binary-test-1.3.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-binary-1.5.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-1.1.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-ledger-shelley-ma-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/shelley-spec-ledger-test-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/shelley-spec-ledger-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/shelley-spec-non-integral-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/small-steps-test-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/small-steps-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-ledger-test-1.3.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-ledger-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/byron-spec-ledger-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-test-1.3.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-crypto-wrapper-1.3.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/byron-spec-chain-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-prelude-test-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/cardano-prelude-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/goblins-0.2.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/tracer-transformers-0.1.0.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/lobemo-scribe-systemd-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/lobemo-backend-trace-forwarder-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/lobemo-backend-monitoring-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/lobemo-backend-ekg-0.1.0.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/lobemo-backend-aggregation-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/iohk-monitoring-0.1.10.1.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/contra-tracer-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/Win32-network-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/typed-protocols-examples-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/typed-protocols-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-network-framework-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-network-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-consensus-shelley-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-consensus-cardano-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-consensus-byron-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/ouroboros-consensus-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/network-mux-0.1.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/io-sim-classes-0.2.0.0.tar.gz
Wrote tarball sdist to
/app/src/cardano-node/dist-newstyle/sdist/io-sim-0.2.0.0.tar.gz
Warning: Requested index-state2021-01-10T00:00:00Z is newer than
'hackage.haskell.org'! Fall

**Comment by rhyslbw** [comment]
I can't see a failure here. Please attach a log file with as much information as possible.

**Comment by malingzhao** [comment]
sorry, May be it's need a long time to complete this process

**Comment by rhyslbw** [comment]
Yes a build from scratch can take some time. The next version should be quicker as a Haskell dependency has been removed, and there are ways to use the remote cache from Dockerhub which will be documented.
