### ISSUE TITLE
{"name":"cardano-graphql","hostname":"08b292cf80dc","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-06-11T05:15:09.571Z","v":0} {"name":"cardano-graphql","hostname":"08b292cf80dc","pid":1,"level":30,"msg":"GraphQL HTTP server at http://0.0.0.0:3100/ started","time":"2021-06-11T05:15:09.911Z","v":0}

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#515]
I use "docker logs -f  cardanographql_cardano-graphql_1",Iti is this, but I cant connect to it , telnet is not usable

**Comment by rhyslbw** [comment]
I'm not sure if it's related as your issue reports and very vague, but please use only #514 until we get you up and running

**Comment by malingzhao** [comment]
"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-06-11T07:13:26.168Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"GraphQL HTTP server at http://0.0.0.0:3100/ started","time":"2021-06-11T07:13:26.628Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-06-11T07:13:26.653Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-06-11T07:16:25.565Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-06-11T07:16:25.566Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-06-11T07:18:58.205Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-06-11T07:18:58.205Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:19:00.664Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:19:02.306Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:19:04.756Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:19:32.392Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:20:17.087Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:20:35.760Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:21:03.812Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:21:06.828Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:21:12.491Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:21:21.416Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:21:26.073Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 3 }","time":"2021-06-11T07:22:03.365Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:22:07.730Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:22:09.498Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:22:11.079Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:22:25.049Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:22:30.490Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:22:34.135Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:23:20.449Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"DB ready","time":"2021-06-11T07:23:26.450Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:23:36.916Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:23:53.048Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:23:56.236Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:24:05.921Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:24:25.214Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:24:44.479Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:24:54.793Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:27:14.037Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:28:54.152Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:30:05.672Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:30:11.223Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 2 }","time":"2021-06-11T07:31:11.382Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":40,"msg":"DbClient.pgSubscriber: cardano-db-sync-extended starting, schema will be reset","time":"2021-06-11T07:31:29.925Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:31:31.522Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 3 }","time":"2021-06-11T07:31:48.001Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:32:01.362Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Adding metadata to assets { module: 'HasuraClient', value: 1 }","time":"2021-06-11T07:32:09.803Z","v":0}
ClientError: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          cardano { \n              currentEpoch {\n                  adaPots {\n                      reserves\n                  }\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
    at step (/app/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'query {\n' +
      '          cardano { \n' +
      '              currentEpoch {\n' +
      '                  adaPots {\n' +
      '                      reserves\n' +
      '                  }\n' +
      '              }\n' +
      '          }\n' +
      '          rewards_aggregate {\n' +
      '              aggregate {\n' +
      '                  sum {\n' +
      '                      amount\n' +
      '                  }\n' +
      '              }\n' +
      '          }\n' +
      '          utxos_aggregate {\n' +
      '              aggregate {\n' +
      '                  sum {\n' +
      '                      value\n' +
      '                  }\n' +
      '              }\n' +
      '          }\n' +
      '          withdrawals_aggregate {\n' +
      '              aggregate {\n' +
      '                  sum {\n' +
      '                      amount\n' +
      '                  }\n' +
      '              }\n' +
      '          }\n' +
      '      }',
    variables: undefined
  }
}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'HasuraClient' }","time":"2021-06-11T07:32:22.913Z","v":0}
ClientError: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              protocolParams {\n                  protocolVersion\n              }\n          }\n      }"}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
    at step (/app/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  response: { errors: [ [Object] ], status: 200 },
  request: {
    query: 'query {\n' +
      '          epochs (limit: 1, order_by: { number: desc }) {\n' +
      '              protocolParams {\n' +
      '                  protocolVersion\n' +
      '              }\n' +
      '          }\n' +
      '      }',
    variables: undefined
  }
}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initialized { module: 'HasuraClient' }","time":"2021-06-11T07:34:34.017Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initializing { module: 'DataSyncController' }","time":"2021-06-11T07:34:34.017Z","v":0}
{"name":"cardano-graphql","hostname":"67c14eedc5a1","pid":1,"level":30,"msg":"Initialized { module: 'DataSyncController' }","time":"2021-06-11T07:35:50.833Z","v":0}
