### ISSUE TITLE
I ask a problem, the cardano how to support the A start address , I  see this coin can support addr1 address And it has been successful, I want to know how to sign A start Address

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#519]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [ ] Docker

**Runtime version**: 
```console
node -v
docker version
```

### What is the expected behavior?

**Comment by rhyslbw** [comment]
Out of scope for this product. Comprehensive information for addresses [here](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0019/CIP-0019.md)
