### ISSUE TITLE
   "message": "database query error",

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#520]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [ ] Docker

**Runtime version**: 
```console
node -v
docker version
```

### What is the expected behavior?

**Comment by rhyslbw** [comment]
Closing due to incomplete report
