### ISSUE TITLE
the 4.0 graphql is not stable. when will  the release version can be used 

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#530]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [ ] Docker

**Runtime version**: 
```console
node -v
docker version
```

### What is the expected behavior?

**Comment by CyberCyclone** [comment]
You'll need to be more specific. 

I've been running 4.0 on ADATools.io since it was released and had pretty much no issues with it in regards to stability.

**Comment by malingzhao** [comment]
Thany you

**Comment by malingzhao** [comment]
does it has problems when it sync

**Comment by malingzhao** [comment]
what's your cardano-db-sync:$ version

**Comment by CyberCyclone** [comment]
You'll need to wait about 18 hours for cardano-node to fully sync before it's usable.

Also make sure you have issue #464 applied.

I use cardano-node version 1.27.0 and I leave the db-sync version as is.

**Comment by malingzhao** [comment]
some time it is good

**Comment by malingzhao** [comment]
but it is not stable

**Comment by malingzhao** [comment]
My machine is use 4C 8G what's your machine

**Comment by malingzhao** [comment]
It is the ADATools.io is public

**Comment by malingzhao** [comment]
can I see you docker-compose.yml

**Comment by malingzhao** [comment]
My cardano-node is 1.25.1

**Comment by CyberCyclone** [comment]
Typically I run it on a bare-metal, 4c, 32GB of RAM. You'll need 16GB of RAM minimum as cardano-node itself needs 8GB. I've found 16GB does work, but it's pretty close to hitting the limit based on usage. So 32GB is my recommendation if you can afford it.

**Comment by malingzhao** [comment]
Thank you very much . does you  use the master branch docker-compose.yml

**Comment by CyberCyclone** [comment]
No, I use the tagged 4.0 (or any latest official release). Master is almost always in a broken state and isn't meant to be used for production.

**Comment by malingzhao** [comment]
max-file: "10"
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.25.1}
    command: [
      "run",
      "--config", "/config/config.json",
      "--database-path", "/data/db",
      "--socket-path", "/ipc/node.socket",
      "--topology", "/config/topology.json"
    ]
    volumes:

**Comment by malingzhao** [comment]
it's version is 1.25.1

**Comment by CyberCyclone** [comment]
Also, keep in mind that since it's technically a database application, you'll get best performance from a machine with high SSD IOPS. DigitalOcean and Vultr (high frequency) both offer exceptional IOPS. I would avoid AWS as they have really low IOPS (unless you pay hundreds of dollars).

**Comment by CyberCyclone** [comment]
>         max-file: "10"
> 
>   cardano-node:
> 
>     image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.25.1}
> 
>     command: [
> 
>       "run",
> 
>       "--config", "/config/config.json",
> 
>       "--database-path", "/data/db",
> 
>       "--socket-path", "/ipc/node.socket",
> 
>       "--topology", "/config/topology.json"
> 
>     ]
> 
>     volumes:

Version 1.25.1 of cardano-node is fine, but if you're starting from scratch then you might as well jump to 1.27.0. There's some performance improvements in it.

**Comment by malingzhao** [comment]
what  your  db  sync  version

**Comment by malingzhao** [comment]
Thank you very much

**Comment by malingzhao** [comment]
Thank you

**Comment by luisg707** [comment]
I'm working through a configuration right now. I have somewhat docker experience. I noticed when I docker-compose up them, after a few hours, I still can't query (shown below). I know the node isn't fully sync'd, but the docs mention that you should be able to get progress from the command below. Based on the responses in this thread, it seems like it's not usable (meaning that you can't query) _untill_ the node is fully sync'd? 

Build Script:
`` git clone   --single-branch   --branch 4.0.0   --recurse-submodules   https://github.com/input-output-hk/cardano-graphql.git   && cd cardano-graphql``

``[root@graphql]# curl   -X POST   -H "Content-Type: application/json"   -d '{"query": "{ cardano { tip { number slotNo epoch { number } } } }"}' http://localhost:3100/graphql

curl: (56) Recv failure: Connection reset by peer``



                   Name                                 Command               State                    Ports                  
------------------------------------------------------------------------------------------------------------------------------
cardano-graphql_cardano-db-sync-extended_1   /nix/store/4b969l97p9lrb28 ...   Up                                              
cardano-graphql_cardano-graphql_1            node index.js                    Up      0.0.0.0:3100->3100/tcp,:::3100->3100/tcp
cardano-graphql_cardano-node_1               /nix/store/p435ajnazwhfyjs ...   Up                                              
cardano-graphql_hasura_1                     docker-entrypoint.sh graph ...   Up      0.0.0.0:8090->8080/tcp,:::8090->8080/tcp
cardano-graphql_postgres_1                   docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp,:::5432->5432/tcp
