### ISSUE TITLE
How long until Playground is available?

### ISSUE THREAD

**Issue by luisg707** [input-output-hk/cardano-graphql#538]
I'm working through a configuration right now. I have somewhat docker experience. I noticed when I docker-compose up them, after a few hours, I still can't query (shown below, http error). I know the node isn't fully sync'd, but the docs mention that you should be able to get progress from the command below. Based on the responses in other issues, it seems like it's not usable (meaning that you can't query) untill the node is fully sync'd?

I also saw "ℹ️ Wait for initialized to be true to ensure the epoch dataset is complete."  . It's "initializing". I can wait the 18+ hours, but just need to know what the expectations are here. 

Build Script:
```
git clone --single-branch --branch 4.0.0 --recurse-submodules https://github.com/input-output-hk/cardano-graphql.git && cd cardano-graphql

[root@graphql]# curl -X POST -H "Content-Type: application/json" -d '{"query": "{ cardano { tip { number slotNo epoch { number } } } }"}' http://localhost:3100/graphql

**curl: (56) Recv failure: Connection reset by peer**



------------------------------------------------------------------------------------------------------------------------------
cardano-graphql_cardano-db-sync-extended_1   /nix/store/4b969l97p9lrb28 ...   **Up**                                              
cardano-graphql_cardano-graphql_1            node index.js                    **Up**      0.0.0.0:3100->3100/tcp,:::3100->3100/tcp
cardano-graphql_cardano-node_1               /nix/store/p435ajnazwhfyjs ...   **Up**                                              
cardano-graphql_hasura_1                     docker-entrypoint.sh graph ...   **Up**      0.0.0.0:8090->8080/tcp,:::8090->8080/tcp
cardano-graphql_postgres_1                   docker-entrypoint.sh postgres    **Up**      0.0.0.0:5432->5432/tcp,:::5432->5432/tcp``


```
**Logs:** Cardano_graphql_1:

```
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"ab61af168341","pid":1,"level":50,"msg":"Command failed: /usr/local/bin/hasura --skip-update-check --project /app/packages/api-cardano-db-hasura/hasura/project --endpoint http://hasura:8080 migrate apply --up all\ntime=\"2021-07-10T22:19:39Z\" level=fatal msg=\"apply failed: [] query execution failed":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"ab61af168341","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-07-10T22:19:42.231Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"ab61af168341","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-07-10T22:19:42.450Z","v":0}
```

**Comment by CyberCyclone** [comment]
Did you update the docker-compose.yml file with the fix here: https://github.com/input-output-hk/cardano-graphql/issues/464

cardano-node should still sync, you're probably having issues with cardano-graphql not starting up.

**Comment by luisg707** [comment]
Hey CyberClone. Want to first point out, your site is -very-very- beautiful. I checked it out the other day.

In terms of fixing, yes. Just want to clarify- when you run the docker-compose build/etc. Is the "playground" available immediately (or within say, 2 hours)? or do you need to wait until a full cardano sync (~18 hours as you mentioned in a previous post)

  cardano-graphql:
    build:
      context: .
      target: server
      args:
        - NETWORK=${NETWORK:-mainnet}
        **- METADATA_SERVER_URI=${METADATA_SERVER_URI:-https://tokens.cardano.org}**
    image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-4.0.0}

**Comment by luisg707** [comment]
For cardano-graphql, I noticed this error happens every few minutes (I truncated). I am assuming the cardano db hasn't fully sync'd (it's only been ~4 hours). I rebuilt it

\\"\\n}\\r\\n[42P01] FatalError: relation \\\"pool_metadata_ref\\\" does not exist\"\n","time":"2021-07-11T00:27:22.942Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"ab61af168341","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-07-11T00:27:25.978Z","v":0}
cardano-graphql_1           | {"name":"cardano-graphql","hostname":"ab61af168341","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-07-11T00:27:26.382Z","v":0}

**Comment by CyberCyclone** [comment]
> Hey CyberClone. Want to first point out, your site is -very-very- beautiful. I checked it out the other day.
> 
> In terms of fixing, yes. Just want to clarify- when you run the docker-compose build/etc. Is the "playground" available immediately (or within say, 2 hours)? or do you need to wait until a full cardano sync (~18 hours as you mentioned in a previous post)
> 
> cardano-graphql:
> build:
> context: .
> target: server
> args:
> - NETWORK=${NETWORK:-mainnet}
> **- METADATA_SERVER_URI=${METADATA_SERVER_URI:-[https://tokens.cardano.org}](https://tokens.cardano.org%7D)**
> image: inputoutput/cardano-graphql:${CARDANO_GRAPHQL_VERSION:-4.0.0}

Thanks for the feedback on the site, I appreciate it :)

The playground should be usable, but I have a feeling that it might not be fully usable until syncing after epoch 208 (Shelley era). Although ```{ cardano { tip { number slotNo epoch { number } } } }``` should work.

Don't forget that any changes or re-builds, you need to do ```docker-compose down``` first to stop any running containers and then start them up.

**Comment by rhyslbw** [comment]
The next release is due out imminently, so I would suggest waiting for `v5`. The following query can be run prior to being in the current epoch, and should be used to check on the sync state:

```graphql
{ cardanoDbMeta { initialized syncPercentage }}
```

> ...you need to do `docker-compose down` first to stop any running containers and then start them up.

Actually, this is **not** advised as you will unnecessarily drop the `cardano-node` DB! Please follow the[ instructions here](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db)

**Comment by rhyslbw** [comment]
The release branch has been made, and we'll be tagging once final QA checks are performed: 
https://github.com/input-output-hk/cardano-graphql/tree/5-0-stable
