### ISSUE TITLE
Assets not found after full sync (v4.0.0 testnet)

### ISSUE THREAD

**Issue by VuongPham96** [input-output-hk/cardano-graphql#540]
### Environment
{
  os: {
    arch: 'x64',
    cpus: { count: 4, model: 'Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz' },
    release: '20.5.0',
    totalMem: 8589934592,
    type: 'Darwin'
  },
  version: '4.0.0'
}

#### Platform
- [x] macOS

**Platform version**: 
11.4 (20F71)

#### Runtime
- [X] Docker

**Runtime version**: 
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
### Steps to reproduce the bug
1. clone the repository 
```
git clone \
  --single-branch \
  --branch 4.0.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql

NETWORK=testnet docker-compose up -d --build && docker-compose logs -f

And wait for full sync
```
2. query assets by policyID
```
curl --location --request POST 'http://localhost:3100/graphql' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "{ assets(where: {policyId: { _eq: \"192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905\" } }) { assetId assetName policyId } }"
}'

return {
    "data": {
        "assets": []
    }
}
```
here is the transaction of an asset of this policyID
https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=8c37a8724d9e7f4004c8fd98e625ddbf44c2cc78b49f1a0f06a1e92b172dbc5f

### What is the expected behavior?
display assets of this policyID

**Comment by CyberCyclone** [comment]
Since it's a Hash28Hex, you need to add a ```\\x``` to the start.

E.g: ```\\x192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905```

**Comment by CyberCyclone** [comment]
If you access Hasura via port 8090 (localhost:8090), you'll see the tables in a bit more raw form. It makes it easier to debug stuff like this.

**Comment by VuongPham96** [comment]
> Since it's a Hash28Hex, you need to add a `\\x` to the start.
> 
> E.g: `\\x192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905`

Thanks @CyberCyclone 
I tried to access via Hasura and the result is still empty

query via Hasura
```
query MyQuery {
  assets(offset: 10, where: {policyId: {_eq: "\\x192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905"}}) {
    assetName
    description
    fingerprint
    logo
    metadataFetchAttempts
    metadataHash
    name
    policyId
    ticker
    url
  }
}
```
I also tried to fetch all assets, and find the policyID but not found too

**Comment by CyberCyclone** [comment]
The query works on my one: https://graphql-testnet.adatools.io/

Just remove the invalid fields from your query and it should work.

**Comment by VuongPham96** [comment]
maybe something wrong with my node sync, let me try to rebuild the docker again

> The query works on my one: https://graphql-testnet.adatools.io/
> 
> Just remove the invalid fields from your query and it should work.

maybe something wrong with my node sync, let me try to rebuild the docker again
btw is this public API ?

Thank you for support

**Comment by CyberCyclone** [comment]
What's your epoch? Does it match testnet.adatools.io?

It's publicly available, but it's not officially supported by Cardano or IOHK. It's just one I run to help devs, not meant for production.

**Comment by VuongPham96** [comment]
My epoch is currently 144
I've check the docker logs
```
[765b4ed7:cardano.node.DnsSubscription:Error:55118] [2021-07-16 06:55:57.79 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 3.129.133.68:3001 InvalidBlock (At (Block {blockPointSlot = SlotNo 32045373, blockPointHash = f88d45379fb347e00d0abaa2c952c07eb14b849396551daf534f51937c6ba523})) (InFutureExceedsClockSkew (RealPoint (SlotNo 32045373) f88d45379fb347e00d0abaa2c952c07eb14b849396551daf534f51937c6ba523))
```

**Comment by CyberCyclone** [comment]
That's the correct epoch. Not sure beyond that sorry without any further logs. Maybe shutdown and start it up again. 

You're welcome to use my one until you get it sorted though 👍

**Comment by VuongPham96** [comment]
Thank you, I will be closed this issue
