### ISSUE TITLE
Circulating and total supply computation

### ISSUE THREAD

**Issue by 1000101** [input-output-hk/cardano-graphql#550]
### Environment

[Release 4.0.0 ](https://github.com/input-output-hk/cardano-graphql/commit/058873f7cfa6d5d287f859a58bf511b128da6494)

#### Platform

Linux / Other

**Platform version**:  NixOS 21.05

### Steps to reproduce the bug

Query this:
```
query{
    ada{
        supply{
            circulating
            max
            total
        }
    }
}
``` 

### What is the expected behavior?

Get correct number for circulating supply.
Get correct number for total supply.

1. Circulating supply:

I have a strong suspicion that circulating supply [calculation](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/src/HasuraClient.ts#L136) might be off by ~billion. 

The current calculation consists of sum of `utxos + (rewards - withdrawals)`, but if you look closely, `rewards-withdrawals` are in fact negative.

Querying directly values from[ db sync (9.0.0)](https://github.com/input-output-hk/cardano-db-sync/commit/0b054e18aec3b1e387a1c7b713c562ade37417a3).

Utxos:
```
SELECT SUM(txo.value)
FROM tx_out txo
LEFT JOIN tx_in txi ON (txo.tx_id = txi.tx_out_id)
AND (txo.index = txi.tx_out_index)
WHERE txi IS NULL;

-------------------
 32247431809402515
(1 row)
```

We can also confirm this by querying graphql:
```
 curl -X POST -H "Content-Type: application/json" -d '{"query": "{ utxos_aggregate { aggregate {sum {value}} } }"}' http://localhost:3002/graphql

{
  "data": { "utxos_aggregate": { "aggregate": { "sum": { "value": "32247431809402516" } } } }
}

```

Next, we calculate rewards-withdrawals in dbsync:
```
SELECT
 (SELECT COALESCE(SUM(amount), 0) FROM reward)
  - 
 (SELECT SUM(amount) FROM withdrawal);

------------------
 -159211187454300
(1 row)
```

Adding it up to utxos, we get: `32088220621948215`.

This corresponds to what can be seen in graphql as circulating supply:
```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ ada{ supply{ circulating max total } } }"}' http://localhost:3002/graphql

{
  "data": {
    "ada": {
      "supply": {
        "circulating": "32088220621948216",
        "max": "45000000000000000",
        "total": "32913667440643408"
      }
    }
  }
}


```

However, this will yield circulating supply that is even lower than utxos and doesn't look right to me. `withdrawal` table also takes `treasury` and `reserve` into account, so I think the correct formula for calculating circulating supply should be `utxos + reward + treasury + reserve - withdrawal` 

or represented as query in db sync:
```
SELECT 
  (SELECT COALESCE(SUM(amount), 0) FROM reward) 
   - 
  (SELECT COALESCE(SUM(amount),0) FROM withdrawal) 
  + 
  (SELECT COALESCE(SUM(amount),0) FROM reserve ) 
  +
  (SELECT COALESCE(SUM(amount),0) FROM treasury);

------------------
 443141922376394
```
which yields a positive number of all withdrawals from all possibly available funds.

I have considered all the possibilities and I have reached the conclusion that the number from graphql might be wrong. Please, correct me if I'm at fault here, but it seems that circulating supply should be closer to `32690573731778909` than to the current value of `32088220621948216`.

Note: The outputs were collected few hours ago, so they are not entirely up to date. 
Note2: COALESCE is needed especially for testnet, where there is empty `reserve` table .

2. Total supply (testnet)

Querying total supply on **testnet** in the current epoch doesn't look right as the circulating supply is higher than total supply.

```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ ada{ supply{ circulating max total } } }"}' http://localhost:3002/graphql

{
  "data": {
    "ada": {
      "supply": {
        "circulating": "42050393097894181",
        "max": "45000000000000000",
        "total": "40233883596865181"
      }
    }
  }
}

```
Note: Edited (replaced data from stuck public dandelion instance with local synced data).

However, if I got this correctly, total supply is calculated as the `max supply` - `reserves` and `reserves` is taken from the ledger state at the epoch boundary. This means there will be a similar issue in the current epoch, as the current reserves are `4766116403134819` but querying utxos in db sync yield a number higher than total supply (`40233883596865181`):

```
SELECT SUM(txo.value)
FROM tx_out txo
LEFT JOIN tx_in txi ON (txo.tx_id = txi.tx_out_id)
AND (txo.index = txi.tx_out_index)
WHERE txi IS NULL;

-------------------
 42016202067224430
(1 row)
```

Again, querying graphql confirms the utxos value used in the computation is the one above:
```
curl -X POST -H "Content-Type: application/json" -d '{"query": "{ utxos_aggregate { aggregate {sum {value}} } }"}' http://localhost:3002/graphql
{"data":{"utxos_aggregate":{"aggregate":{"sum":{"value":"42016202067224430"}}}}
```

Sorry for the trouble, I'm not sure if I'm doing something wrong so I'd appreciate your help and clarification if I'm mistaken. Thanks a million.

**Comment by rhyslbw** [comment]
Would you mind comparing with `cardano-graphql@5.0.0`, which is paired with `cardano-db-sync@10.0.1`?. I'll investigate your report, but it will be good to check against the new version of the DB. Thank you for the detail.

**Comment by 1000101** [comment]
> Would you mind comparing with `cardano-graphql@5.0.0`, which is paired with `cardano-db-sync@10.0.1`?. I'll investigate your report, but it will be good to check against the new version of the DB. Thank you for the detail.

I'd love to, but my instance v5.0.0 with db sync v10.0.1 is getting stuck (I've tried waiting more than half an hour) at:
```
"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...",
```
Note: I'll update this post with relevant data if I get v5 working.

Querying just db sync 10.0.1 for underlying data seems to yield same/similar results:
```
SELECT SUM(txo.value)
FROM tx_out txo
LEFT JOIN tx_in txi ON (txo.tx_id = txi.tx_out_id)
AND (txo.index = txi.tx_out_index)
WHERE txi IS NULL;

-------------------
 32249557950613340
(1 row)

SELECT
 (SELECT COALESCE(SUM(amount), 0) FROM reward)
  -
 (SELECT COALESCE(SUM(amount),0) FROM withdrawal);

------------------
 -144637159774064
(1 row)

SELECT
  (SELECT COALESCE(SUM(amount), 0) FROM reward)
  -
  (SELECT COALESCE(SUM(amount),0) FROM withdrawal)
  +
  (SELECT COALESCE(SUM(amount),0) FROM reserve )
  +
  (SELECT COALESCE(SUM(amount),0) FROM treasury);

-----------------
 457717257188854
(1 row)

```

So my guess is that v5 will return the same data as v4.

However, my understanding is that db sync v10.0.1 is not yet production ready since it's having fair amount of issues of its own.

**Comment by rhyslbw** [comment]
> I'd love to, but my instance v5.0.0 with db sync v10.0.1 is getting stuck without binding to its port

How did you upgrade your stack? [cardano-db-sync@10.0.1](https://github.com/input-output-hk/cardano-db-sync/releases/tag/10.0.1) is the latest release

**Comment by 1000101** [comment]
> > I'd love to, but my instance v5.0.0 with db sync v10.0.1 is getting stuck without binding to its port
> 
> How did you upgrade your stack? [cardano-db-sync@10.0.1](https://github.com/input-output-hk/cardano-db-sync/releases/tag/10.0.1) is the latest release

Using nix.

However, dbsync is running fine, it's the graphql I'm having problem with (doesn't bind the configured port). I realized I have to run ogmios, so I used one from master, since it's written as NixOS service (3.2.0) but it still didn't help.

But back to the point of the issue - do you have problems replicating this in the current cardano-graphql version?

**Comment by rhyslbw** [comment]
Best to use the git submodule commit ref: https://github.com/CardanoSolutions/ogmios/tree/a2a92ee54b08e9b8b3c8cc95ea4f4c4d83904579

I need to cross reference against another discussion on the issue, and will get back to you

**Comment by rhyslbw** [comment]
Please send the `cardano-graphql` service logs

**Comment by 1000101** [comment]
> cardano-graphql

```
Jul 30 11:30:34 dbsync1 systemd[1]: Starting cardano-graphql.service...
Jul 30 11:30:34 dbsync1 cardano-graphql-pre-start[116865]: + rm -rf /root/.hasura/plugins
Jul 30 11:30:34 dbsync1 cardano-graphql-pre-start[116865]: + mkdir -p /root/.hasura/plugins/store/cli-ext/v1.3.3
Jul 30 11:30:34 dbsync1 cardano-graphql-pre-start[116865]: + ln -s /nix/store/y95nl4bhwp9p9z2kzqaxz7dgk175ipwg-hasura-cli-ext-1.3.3/bin/cli-ext-hasura-linux /root/.hasura/plugins/store/cli-ext/v1.3.3/cli-ext-hasura-linux
Jul 30 11:30:34 dbsync1 systemd[1]: Started cardano-graphql.service.

Jul 30 11:30:36 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"Db","msg":"pgSubscriber: Connected","time":"2021-07-30T11:30:36.108Z","v":0}
Jul 30 11:30:36 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"Server","msg":"Initializing","time":"2021-07-30T11:30:36.109Z","v":0}
Jul 30 11:30:36 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"Server","msg":"Prometheus metrics will be served at /metrics","time":"2021-07-30T11:30:36.350Z","v":0}
Jul 30 11:30:36 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-07-30T11:30:36.461Z","v":0}
Jul 30 11:30:37 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2021-07-30T11:30:37Z\"}\n{\"level\":\"info\",\"msg\":\"migrations applied\",\"time\":\"2021-07-30T11:30:37Z\"}\n","time":"2021-07-30T11:30:37.888Z","v":0}
Jul 30 11:33:12 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying migrations...\",\"time\":\"2021-07-30T11:30:37Z\"}\n{\"level\":\"info\",\"msg\":\"migrations applied\",\"time\":\"2021-07-30T11:33:12Z\"}\n","time":"2021-07-30T11:33:12.783Z","v":0}
Jul 30 11:33:13 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Clearing metadata...\",\"time\":\"2021-07-30T11:33:12Z\"}\n{\"level\":\"info\",\"msg\":\"Metadata cleared\",\"time\":\"2021-07-30T11:33:13Z\"}\n","time":"2021-07-30T11:33:13.339Z","v":0}
Jul 30 11:33:15 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"{\"level\":\"info\",\"msg\":\"Applying metadata...\",\"time\":\"2021-07-30T11:33:13Z\"}\n{\"level\":\"info\",\"msg\":\"Installing plugin cli-ext...\",\"time\":\"2021-07-30T11:33:14Z\"}\n{\"level\":\"info\",\"msg\":\"plugin installed\",\"name\":\"cli-ext\",\"time\":\"2021-07-30T11:33:14Z\"}\n{\"level\":\"info\",\"msg\":\"Metadata applied\",\"time\":\"2021-07-30T11:33:15Z\"}\n","time":"2021-07-30T11:33:15.584Z","v":0}
Jul 30 11:33:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"graphql-engine setup","time":"2021-07-30T11:33:17.051Z","v":0}
Jul 30 11:33:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","msg":"DB is in current era","time":"2021-07-30T11:33:17.079Z","v":0}
Jul 30 11:33:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","currentProtocolVersion":{"major":4,"minor":4},"msg":"currentProtocolVersionFetcher","time":"2021-07-30T11:33:17.092Z","v":0}
Jul 30 11:33:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"DataFetcher","instance":"ProtocolParams","value":{"major":4,"minor":4},"msg":"Initial value fetched","time":"2021-07-30T11:33:17.093Z","v":0}
Jul 30 11:34:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"HasuraClient","currentProtocolVersion":{"major":4,"minor":4},"msg":"currentProtocolVersionFetcher","time":"2021-07-30T11:34:17.407Z","v":0}
Jul 30 11:34:17 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"DataFetcher","instance":"ProtocolParams","value":{"major":4,"minor":4},"msg":"value fetched after 60 seconds","time":"2021-07-30T11:34:17.411Z","v":0}
Jul 30 11:34:19 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":20,"module":"DataFetcher","instance":"AdaPotsToCalculateSupply","value":{"circulating":"32104883994125521","reserves":12063362662818908},"msg":"Initial value fetched","time":"2021-07-30T11:34:19.924Z","v":0}
Jul 30 11:34:19 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2021-07-30T11:34:19.924Z","v":0}
Jul 30 11:34:19 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2021-07-30T11:34:19.925Z","v":0}
Jul 30 11:34:20 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":30,"module":"CardanoNodeClient","msg":"Initialized","time":"2021-07-30T11:34:20.016Z","v":0}
Jul 30 11:34:20 dbsync1 cardano-graphql-start[116871]: {"name":"cardano-graphql","hostname":"dbsync1","pid":116871,"level":50,"msg":"Cannot read property 'status' of undefined","time":"2021-07-30T11:34:20.054Z","v":0}
```

**Comment by 1000101** [comment]
@rhyslbw any updates please?

**Comment by 1000101** [comment]
:eyes: 

> @rhyslbw any updates, please?

**Comment by rhyslbw** [comment]
Sorry @1000101, I'll dedicate some time to review again tomorrow.

**Comment by rhyslbw** [comment]
@1000101 This is assigned for QA to verify the results, then we'll implement a fix for the next release. Thanks again for the detailed report

**Comment by cardistack** [comment]
same here. Starts fine wait for a few days to sync then graphql wont listen on 3100


{"name":"cardano-graphql","hostname":"f136361575bc","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initialized","time":"2021-09-10T08:26:43.076Z","v":0}


{"name":"cardano-graphql","hostname":"f136361575bc","pid":1,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2021-09-10T08:26:43.077Z","v":0}


{"name":"cardano-graphql","hostname":"f136361575bc","pid":1,"level":50,"msg":"Request failed with status code 504","time":"2021-09-10T08:27:43.231Z","v":0}

**Comment by 1000101** [comment]
> @1000101 This is assigned for QA to verify the results, then we'll implement a fix for the next release. Thanks again for the detailed report

Thanks @rhyslbw! However, this might (quite possible will) become obsolete in the new dbsync as `reserve` and `treasury` seems to be now included in the `reward` table, differentiated by a new `type` column. So the current computation will actually might become valid and fix automagically due to underlying changes in the upcoming dbsync release(s).
