### ISSUE TITLE
Support cardano-db-sync:10.0.0 snapshots

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#551]
With the release of cardano-db-sync:10.0.0 and the ability to backup and restore db-sync snapshots, it would be good to incorporate that into @cardano-graphql/cli.

While @cardano-graphql/cli can backup and restore it's own snapshots, being able to shorten the re-sync time when new versions come out (e.g, cardano-db-sync 9 to 10 requires dropping the DB) would be a good "nice to have".

This could be blocked until it has docker support though: https://github.com/input-output-hk/cardano-db-sync/issues/691

**Comment by rhyslbw** [comment]
I'm actually working on a solution for restoring the snapshots, but am taking a generic approach to enable any user of `cardano-db-sync` to restore a remote snapshot i0n a Docker context. The _mainnet_ snapshot has just ticked over the limit for single file transmission via S3, so the ops team will be implementing multi-part which I'll then implement and publish.

**Comment by CyberCyclone** [comment]
Awesome. Just in terms of snapshot file size. Maybe it's an option to host them via torrents? I'd be keen to keep a peer online to help.

**Comment by rhyslbw** [comment]
The image will soon support loading a snapshot on container startup https://github.com/input-output-hk/cardano-db-sync/pull/712, and we can use the feature directly once released.
