### ISSUE TITLE
Query extremely slow on mainnet

### ISSUE THREAD

**Issue by VuongPham96** [input-output-hk/cardano-graphql#557]
### Environment
I'm running on AWS t2.xlarge
```
{
  os: {
    arch: 'x64',
    cpus: { count: 4, model: 'Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz' },
    release: '4.14.232-177.418.amzn2.x86_64',
    totalMem: 16818012160,
    type: 'Linux'
  },
  version: '5.0.0'
}
```
**Alternatively, what release or Git revision are you using:**
2.32.0

#### Platform

- [x] Linux / Other

**Platform version**: 
Amazon Linux version 2

#### Runtime

- [x] Docker

**Runtime version**: 
```console
node -v
12.12.0

docker version
Client:
 Version:           20.10.4
 API version:       1.41
 Go version:        go1.15.8
 Git commit:        d3cb89e
 Built:             Mon Mar 29 18:54:36 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.4
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.8
  Git commit:       363e9a8
  Built:            Mon Mar 29 18:55:03 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0
  GitCommit:        %runc_commit
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

### Steps to reproduce the bug
1. clone the repository
```
git clone \
  --single-branch \
  --branch 4.0.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
```
2. start docker
```
docker-compose up -d --build && docker-compose logs -f
```
And wait for full sync

3. query transactions
```
curl --location --request POST 'http://localhost:3001' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "{ transactions(order_by: {includedAt: desc}, where: {outputs: {tokens: {asset:{assetId: {_eq: \"192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905474c43\"}}}}}){ outputs_aggregate(where: {tokens: {asset: {assetId: {_eq: \"192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905474c43\"}}}}) { aggregate { count } } inputs_aggregate(where: {tokens: {asset: {assetId: {_eq:\"192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905474c43\"}}}}) { aggregate { count } } hash metadata { key value } includedAt inputs { tokens { asset { assetId } } } outputs { tokens { asset { assetId } } } } }"
}'
```
this query took me 30 mins and still not finished

I also tried this simple query
```
curl --location --request POST 'http://localhost:3001' \
--header 'Content-Type: application/json' \
--data-raw '{
    "query": "{transactions(limit: 10, where: {outputs: {tokens: {assetId: {_eq: \"192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905474c43\"}}}}) { id }}"
}'
```
it's extremely slow

#### Here is the link of this address
https://cardanoscan.io/address/addr1q8s334nh9mn8ey2tewvr2gwywgsmn305ry2gyzw6pkuwyxmh0g3u9d9nhjzq9eeu9nmtjsv05ku6rdtjgcglad6p0qgqf3a4ms
https://cardanoscan.io/token/192b0b556d8729ea674cdf8a780c12d9f120d9e807102ebc5558c905474c43

### What is the expected behavior?
Display transactions

**Comment by CyberCyclone** [comment]
This is almost 100% bottlenecked by the way AWS provisions SSD IOPS. I avoid AWS or any service that restricts IOPS when it comes to databases.

Here's a good article with comparisons and a good explainer of the issue at the end of.

https://dzone.com/articles/iops-benchmarking-disk-io-aws-vs-digitalocean

To summarise, AWS allocates about IOPS based on how much GB you use. So to get the most performance, you need to pay a lot to provision enough IOPS.

**Comment by VuongPham96** [comment]
It seems to be the problem, my VPS only have 300 IOPS

**Comment by CyberCyclone** [comment]
My suggestion would be to try DigitalOcean, Vultr or Hetzner. They have typically high IOPS. Vultr and DigitalOcean both have High Frequency (Vultr) and Premium (DO) servers that have IOPS averaging between 100,000 and 150,000. 

Vultr also has very decent Bare Metal servers which I was using with ADATools.io for some time.

**Comment by VuongPham96** [comment]
I increased IOPS to 10,000 and it worked, thank you for your suggestion, I will try it
