### ISSUE TITLE
public graphql endpoint

### ISSUE THREAD

**Issue by maikelmclauflin** [input-output-hk/cardano-graphql#559]
hi there, i am wondering if there is a public endpoint that i can hit. i need to check ~65k addresses and have found that the https://explorer.cardano.org/graphql endpoint only responds with not allowed. wondering if i am simply doing something wrong or if i can get around this without downloading the whole chain locally. this will be a fairly ephemeral project and i would rather not maintain a node locally

**Comment by CyberCyclone** [comment]
My one is currently down for maintenance (part of ADATools.io). I should able to have it back up tonight.

**Comment by CyberCyclone** [comment]
Give this a go, it's running 4.0.0. Keep in mind that I'm running it for people to explore it / casual use. It's not meant for production use. If you depend on it 24/7 you'll need to run your own. Otherwise know yourself out: https://graphql.adatools.io/

**Comment by rhyslbw** [comment]
> only responds with not allowed

This is expected, as the API instance is paired for exclusive use by the explorer app. GraphQL pushes more power down to the client by way of query felxibility, but consequently complicates the access control model. This particular design is intended for running the API as a private service.
