### ISSUE TITLE
Cardano Graphql seems stuck in "Initializing"

### ISSUE THREAD

**Issue by YordanPavlov** [input-output-hk/cardano-graphql#569]
I am running a Cardano setup as Kubernetes pods, using the following images:

```
image: inputoutput/cardano-db-sync:10.0.1
image: inputoutput/cardano-graphql:5.0.0
image: inputoutput/cardano-node:1.25.1
image: inputoutput/cardano-graphql-hasura:5.0.0
image: bitnami/postgresql:11.7.0-debian-10-r9
```

I see no errors in the logs and the system seems to be synced. However the log of the graphql pod looks like so:
 
GraphQL log:
```
{"name":"cardano-graphql","hostname":"cardano-graphql-5f85fd486c-jgpwx","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-08-10T09:44:22.610Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-5f85fd486c-jgpwx","pid":1,"level":30,"module":"Server","msg":"Prometheus metrics will be served at /metrics","time":"2021-08-10T09:44:22.709Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-5f85fd486c-jgpwx","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-10T09:44:22.760Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-5f85fd486c-jgpwx","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2021-08-10T09:45:37.988Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-5f85fd486c-jgpwx","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2021-08-10T09:45:37.988Z","v":0}
```

How can I investigate what is happening, connecting to the pod there is no CPU activity. Also as a side question what is the way to install packages on the inputoutput images. For example I would like to install basic tools like `telnet` and `curl`. Thank you.

**Comment by rhyslbw** [comment]
The stack now uses `cardano-node-ogmios` to expose the node APIs over TCP, which is a drop-in replacement for `cardano-node`.

https://github.com/input-output-hk/cardano-graphql/blob/959768a63e8bd05dd81efdee4e3918a2fb20bb11/docker-compose.yml#L27-L44

Docs are [here](https://ogmios.dev/getting-started/docker/) and you will need [v4.0.0-beta.4-mainnet](https://hub.docker.com/layers/cardanosolutions/cardano-node-ogmios/v4.0.0-beta.4-mainnet/images/sha256-26151d96eb861fd057a99756b9427f723b4530603a0cfbc73cc4ed3d8f6afa33?context=repo), or you can build from source using the linked git-submodule.
