### ISSUE TITLE
Cardano Graphql does not open port 3100

### ISSUE THREAD

**Issue by YordanPavlov** [input-output-hk/cardano-graphql#575]
I am using the latest images as specified in:
https://github.com/input-output-hk/cardano-graphql/blob/master/docker-compose.yml
after 48 hours the log of cardano graphql container looks like so:

```
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-48wtv","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-08-17T12:48:45.356Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-48wtv","pid":1,"level":30,"module":"Server","msg":"Prometheus metrics will be served at /metrics","time":"2021-08-17T12:48:45.468Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-48wtv","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-17T12:48:45.523Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-48wtv","pid":1,"level":50,"msg":"Epoch information not yet available. This is expected during the initial chain-sync.","time":"2021-08-17T12:49:00.851Z","v":0}
```

And the connection port 3100 is not open. Is this expected and how should I proceed. Thank you.

**Comment by CyberCyclone** [comment]
Did you try `docker-compose down` and then starting them up again?

**Comment by YordanPavlov** [comment]
> Did you try `docker-compose down` and then starting them up again? After a fresh full-sync graphql can fail to come up.

Thanks for your feedback @CyberCyclone ! I am using the images in Kuberntes environment, so I restarted the pod hadnling Graphql as you suggested. Judging by the log it indeed got a bit further:

```
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-wgdtd","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2021-08-20T05:07:33.147Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-wgdtd","pid":1,"level":30,"module":"Server","msg":"Prometheus metrics will be served at /metrics","time":"2021-08-20T05:07:33.274Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-wgdtd","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2021-08-20T05:07:33.339Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-wgdtd","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2021-08-20T05:08:46.730Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-6748cbf586-wgdtd","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2021-08-20T05:08:46.731Z","v":0}
```

it's been like this for 8 hours now, port is still not open.

**Comment by CyberCyclone** [comment]
I can't help with Kubernetes sorry. In the logs every now any then it should say what epoch it's synced to? 

You can also access Hasura on port 8090 and see if there's anything in the tables.

**Comment by rhyslbw** [comment]
Start the `cardano-graphql` service with `LOGGER_MIN_SEVERITY=debug` for extra logs

**Comment by YordanPavlov** [comment]
> Start the `cardano-graphql` service with `LOGGER_MIN_SEVERITY=debug` for extra logs

After enabling debug logging I am seeing the following:

```
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"msg":"Establishing connection to cardano-node: Attempt 31 of 101, retrying...","time":"2021-08-23T16:05:51.774Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2021-08-23T16:05:51.826Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2021-08-23T16:05:52.560Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2021-08-23T16:05:54.869Z","v":0}
...
...
...
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2021-08-23T16:06:37.230Z","v":0}
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-rgnxw","pid":1,"level":20,"module":"DataFetcher","instance":"AdaPotsToCalculateSupply","value":{"circulating":"31977479957316968","reserves":11972182166198574},"msg":"value fetched after 60 seconds","time":"2021-08-23T16:06:38.802Z","v":0}
```

Identical lines being removed. I guess the most valuable log is the `"Establishing connection to cardano-node: Attempt 31 of 101"` failing. How is that connectivity being done? Is it through some port or through the IPC socket file? In my setup those systems are running in separate pods so I need to provide the connectivity.

**Comment by yungtechboy1** [comment]
I am having the same issue... I can connect to Ogmosis on port 1337. And Ogmosis is fully synced but I can not access port 3100. I also have this error: 


cardano-db-sync-extended_1  | cardano-db-sync-extended: FatalError {fatalErrorMessage = "Cannot find the DbSync configuration file at : /config/cardano-db-sync/config.json"}
cardano-graphql-510-beta1_cardano-db-sync-extended_1 exited with code 1

**Comment by cardanians** [comment]
same here. testnet started correctly and graphql instantly, but mainnet all, except graphql.

**Comment by CyberCyclone** [comment]
> same here. testnet started correctly and graphql instantly, but mainnet all, except graphql.

For 5.1.0, graphql won't come up until it's fully synced. Once it has synced, you'll most likely need to bring it all down and the back up again.

**Comment by cardanians** [comment]
@

> 
> 
> > same here. testnet started correctly and graphql instantly, but mainnet all, except graphql.
> 
> For 5.1.0, graphql won't come up until it's fully synced. Once it has synced, you'll most likely need to bring it all down and then back up again.

ok thanks, will wait.
weird is, with same version, on testnet, it worked correctly since start (incl graphql)

**Comment by cardanians** [comment]
@CyberCyclone thank you. autostart not worked, but start with docker-compose up spin up hasura container and all now working.

**Comment by CyberCyclone** [comment]
> @CyberCyclone thank you. autostart not worked, but start with docker-compose up spin up hasura container and all now working.

You're welcome, glad to hear!

**Comment by YordanPavlov** [comment]
I never managed to get this working. As last reported the logs are full of three types of logs:
```
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-f6vnx","pid":1,"level":20,"module":"DataFetcher","instance":"ServerHealth","msg":"value fetched after 30 seconds","time":"2021-09-10T14:55:25.883Z","v":0
```
Also:
```
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-f6vnx","pid":1,"level":20,"module":"DataFetcher","instance":"AdaPotsToCalculateSupply","value":{"circulating":"NaN","reserves":11904389292477516},"msg":"value fetched after 60 seconds","time":"2021-09-10T14:55:55.781Z","v":0}
```
And in-between:
```
{"name":"cardano-graphql","hostname":"cardano-graphql-7c79d7c497-f6vnx","pid":1,"level":20,"msg":"Establishing connection to cardano-node: Attempt 1 of 101, retrying...","time":"2021-09-10T14:55:50.256Z","v":0}
```
After the last `Attempt 66 of  101` the attempt logs stop and the other continue. Still the port is not open. What would be the ways to investigate this further?

**Comment by aghamir** [comment]
> I am having the same issue... I can connect to Ogmosis on port 1337. And Ogmosis is fully synced but I can not access port 3100. I also have this error:
> 
> cardano-db-sync-extended_1 | cardano-db-sync-extended: FatalError {fatalErrorMessage = "Cannot find the DbSync configuration file at : /config/cardano-db-sync/config.json"}
> cardano-graphql-510-beta1_cardano-db-sync-extended_1 exited with code 1

@yungtechboy1 
I get the same error `Cannot find the DbSync configuration file at : /config/cardano-db-sync/config.json` for cardano-db-syn-extended. How did you solve this issue?
