### ISSUE TITLE
db-sync-node.Subscription:Error

### ISSUE THREAD

**Issue by rezagazeri** [input-output-hk/cardano-graphql#579]
Hi,
I set up cardano-graphql with docker- compose on testnet and had set everything accoording to its documentation and it was sync until 98% ,but when I wanted to run cardano- graphql again with below command Get below error

DOCKER_BUILDKIT=1 \        
COMPOSE_DOCKER_CLI_BUILD=1 \
API_PORT=3101 \
HASURA_PORT=8091 \
OGMIOS_PORT=1338 \
POSTGRES_PORT=5433 \
![Selection_066](https://user-images.githubusercontent.com/51533908/131086684-41945904-7cbf-417e-9156-acb7b6ddf330.png)

METADATA_SERVER_URI="https://metadata.cardano-testnet.iohkdev.io" \
docker-compose -p testnet up -d --build &&\
docker-compose -p testnet logs 

`
error:
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:56] [2021-08-27 06:52:02.78 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 21>: does not exist (No such file or directory)

`

**Comment by rhyslbw** [comment]
Try this release candidate branch @rezagazeri https://github.com/input-output-hk/cardano-graphql/tree/5-1-stable
