### ISSUE TITLE
How to get unconfirmed utxo

### ISSUE THREAD

**Issue by aghamir** [input-output-hk/cardano-graphql#583]
Dear devs,
I need to get unconfirmed utxo in order to avoid double spend one utxo for two nearly simultaneous transactions.
I get the list of utxos as follow:
```
query getUtxos($address: String!){
                utxos(where: { address: { _eq: $address } } ){
                    txHash,
                    index,
                    value
                }
            }
```

**Comment by vae520283995** [comment]
There should be no way at the moment
https://github.com/input-output-hk/cardano-graphql/issues/398
