### ISSUE TITLE
Plutus queries 'order_by' - Feature Request

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#584]
Please expose the 'transaction' in the queries 'order_by' on the below to allow sorting by transaction included date. This will be useful for displaying in tables and using pagination.

1. collateralInputs
2. redeemers
3. scripts

**Comment by rhyslbw** [comment]
It's already present for `redeemers` and `scripts`
https://github.com/input-output-hk/cardano-graphql/blob/0a13e5b7224621a660bfa949a92ced8f629d2db4/packages/api-cardano-db-hasura/schema.graphql#L584

https://github.com/input-output-hk/cardano-graphql/blob/67a8777d912baeb969d40f3ae5723b07aae55fbe/packages/api-cardano-db-hasura/schema.graphql#L712

I'll add it to `collateralInputs` though
