### ISSUE TITLE
activeStake - db-sync epoch_stake discrepancy

### ISSUE THREAD

**Issue by CyberCyclone** [input-output-hk/cardano-graphql#587]
### Steps to reproduce the bug

Fully synced cardano-graphql:5.1.0.

Initially everything was fully synced and running normally. After leaving it for a day I came back and the containers had crashed and spitting out an error something about Postgres password incorrect, but I suspect Postgres had just died. After restarting, everything seems to have continued on fine.

After leaving it for another day I've noticed though for epoch 289 (current), when running 
```
{
  activeStake_aggregate(where: {epochNo: {_eq: 289}}){
    aggregate{
      count
    }
  }
}
```

It's only returning a count of 1000. I suspected that the change as mentioned in https://github.com/input-output-hk/cardano-db-sync/issues/709 had meant the bulk insert hadn't restarted after the containers crashing.

I've looked at the epoch_stake table and it's returned 2497980 rows.

<img width="810" alt="image" src="https://user-images.githubusercontent.com/4373888/132680088-d652e9fc-e2a3-4572-95d6-e86b0107e64c.png">

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/4373888/132680475-e6f3ba1c-843c-4d2f-b8a5-4620460b966e.png">

I'm not entirely sure on what's going on here, but the aggregate count isn't increasing.

**Comment by rhyslbw** [comment]
Is this still happening @CyberCyclone ?  On my local instance:
```graphql
{
  activeStake_aggregate(where: {epochNo: {_eq: 289}}){
    aggregate{
      count
    }
  }
}
```

``` json
{
  "data": {
    "activeStake_aggregate": {
      "aggregate": {
        "count": "801247"
      }
    }
  }
}
```

**Comment by CyberCyclone** [comment]
Yes, epoch 289 is still stuck at 1000 delegates. Epoch 290 has the correct number. I'm going to look into this further on Sunday and see if I can figure it out.

I had 1 local instance where this happened, but I've since had 2 production instances that have NOT had this issue.

**Comment by rhyslbw** [comment]
Any updates on this @CyberCyclone ?

**Comment by CyberCyclone** [comment]
I was mislead by Hasura. The epoch_stake table does not have as many rows as it states in the pagination and cardano-graphql is querying correctly. 

<img width="401" alt="Screen Shot 2021-09-23 at 8 00 01 pm" src="https://user-images.githubusercontent.com/4373888/134488767-e3619c23-e8ac-4dff-9d71-7dd2e56a9c80.png">

Therefore I don't see this as a cardano-graphql issue but a cardano-db-sync issue. Unfortunately since I did a docker-compose down and then brought them back up to see if that would fix it 6 days ago, it's deleted the container logs so I can't see if there was a particular error that occurred. 

Either way, if there was an error during the epoch_stake populating or if the containers were stopped, there should be a check at some point to verify that epoch_stake has completed and have the ability to continue importing.

This could somehow be managed in correlation with https://github.com/input-output-hk/cardano-db-sync/issues/797

I personally see this as a low priority issue as at this point there's no evidence of it being a bug. If this happened, most people would be able to drop the db and reimport from the snapshot.
