### ISSUE TITLE
Cannot return null for non-nullable field Token.asset

### ISSUE THREAD

**Issue by bgiegel** [input-output-hk/cardano-graphql#612]
### Environment
cardano-graphql v5.1.0-mainnet
cardano-node-v4.0.0-mainnet
cardano-db-sync:11.0.0

#### Platform

- [ ] Linux / Ubuntu
- [X] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [X] Node.js
- [ ] Docker

**Runtime version**: 
node v10.24.0

### Steps to reproduce the bug

I get an `Cannot return null for non-nullable field Token.asset` when executing this query
```{
  blocks(where: { number: { _eq: 6298170 } }) {
    forgedAt
    transactions {
      fee
      deposit
      hash
      inputs {
        address
        sourceTxHash
        sourceTxIndex
        value
        tokens {
          asset {
            assetName
            policyId
          }
          quantity
        }
      }
      outputs {
        address
        index
        value
        tokens {
          asset {
            assetName
            policyId
          }
          quantity
        }
      }
    }
  }
}
```

I find other issues with the exact same errors. It was supposed to be fixed but apparently it is not. Maybe a regression ?

### What is the expected behavior?

The response is returned without any error.

**Comment by bgiegel** [comment]
Sorry I did not see that the issue was not released yet. I close the issue

**Comment by rhyslbw** [comment]
Did this happen after upgrading from the previous version? Can you run the following query?:

```graphql
query {
  assets_aggregate {
    aggregate {
      count
    }
  }
  tokenMints_aggregate(distinct_on: assetId) {
    aggregate {
      count
    }
  }
}
```
There are two ways to recover:

1. _Recommended_: Run this SQL command on the database `TRUNCATE "Asset", pgboss.job` then restart the `cardano-graphql` service and wait for the asset table to rebuild  **OR** 
2. Rebuild the database following the [usual procedure](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db).

**Comment by bgiegel** [comment]
Hi ! And thank you for your answer. No we never done any upgrade when this error arrived. We just installed recently the latest version of cardano version 4.0.0. First from the beta 9 then the final one. On both the same error.

I ran the query you provided on the postgres DB. But I still have the same issue after restarting my graphql server.

**Comment by bgiegel** [comment]
Hi ! And thank you for your answer. No we never done any upgrade when this error arrived. We just installed recently the latest version of cardano version 4.0.0. First from the beta 9 then the final one. On both the same error.

I ran the query you provided on the postgres DB. But I still have the same issue after restarting my graphql server. I can see that the Asset table is being filled up again. Do I need to wait until the end ? Because if I query the table I still see a lot of fields that are null like name etc : 
```
                                         assetId                                          |            assetName             | decimals | description |                 fingerprint                  | firstAppearedInSlot | logo | metadataHash | name |                          policyId                          | ticker | url
------------------------------------------------------------------------------------------+----------------------------------+----------+-------------+----------------------------------------------+---------------------+------+--------------+------+------------------------------------------------------------+--------+-----
 \x3a9241cd79895e3a8d65261b40077d4437ce71e9d7c8c6c00e3f658e4669727374636f696e             | \x4669727374636f696e             |          |             | asset1aq460y056c3mm4jmuv9vg39n7w8y5gykywjwge |            23068966 |      |              |      | \x3a9241cd79895e3a8d65261b40077d4437ce71e9d7c8c6c00e3f658e |        |
 \xe8e62d329e73190190c3e323fb5c9fb98ee55f0676332ba949f29d724649525354                     | \x4649525354                     |          |             | asset14xc0dyfwcr2uuh0f2320yy9j3mar2ytr0nlqtf |            23068966 |      |              |      | \xe8e62d329e73190190c3e323fb5c9fb98ee55f0676332ba949f29d72 |        |
```

I tried to run the query you provided but it doesnt seem to work : 

```
{
   "errors":[
      {
         "message":"Unknown argument \"distinct_on\" on field \"tokenMints_aggregate\" of type \"Query\".",
         "locations":[
            {
               "line":1,
               "column":65
            }
         ],
         "extensions":{
            "code":"GRAPHQL_VALIDATION_FAILED",
            "exception":{
               "stacktrace":[
                  "GraphQLError: Unknown argument \"distinct_on\" on field \"tokenMints_aggregate\" of type \"Query\".",
                  "    at Object.Argument (/app/node_modules/graphql/validation/rules/KnownArgumentNames.js:60:29)",
                  ...
               ]
            }
         }
      }
   ]
}
```

**Comment by bgiegel** [comment]
Ok the Asset db now seems fully rebuild and our query is working again ! Thanx a lot for the help.
That means it was just a problem of data format on our postgres DB ? If true I suppose we can close the issue.

**Comment by rhyslbw** [comment]
> I tried to run the query you provided but it doesn't seem to work : 

My mistake. The distinct filter isn't currently exposed on the `cardano-graphql` server, but works on the Hasura server. I'll expose this and also include additional logging to reveal the sync state of the `Asset` table.

> That means it was just a problem of data format on our postgres DB 

Yes there must have been some corruption, probably in the DB schema.

**Comment by bgiegel** [comment]
@rhyslbw I think we need to reopen the issue. I’m having the same error again on another block (6298216 instead of 6298170). So I guess there is something else wrong..

**Comment by bgiegel** [comment]
Hello ! 

So I have some news. I ran the query that you provided on a brand new vm with plenty of resources and the docker-compose provided in this repo with the latest version of node and graphql. 

I have this : 
```
{
  "data": {
    "assets_aggregate": {
      "aggregate": {
        "count": "895295"
      }
    },
    "tokenMints_aggregate": {
      "aggregate": {
        "count": "1162536"
      }
    }
  }
}
```
What does it mean ? Looks good ? 
By the way on this same installation with the docker-compose provided I have the same error just after the full sync.

**Comment by ntauth** [comment]
@bgiegel Still same issue on v1.34.4
