### ISSUE TITLE
something wrong with install

### ISSUE THREAD

**Issue by lpf763827726** [input-output-hk/cardano-graphql#625]
i try `A) Build and Run via Docker Compose` to install, it always stuck in 
```
Step 14/46 : RUN git clone https://github.com/input-output-hk/cardano-node.git /app/src/cardano-node &&  git fetch --all --tags &&  git checkout ${CARDANO_NODE_REV}
Cloning into '/app/src/cardano-node'...
```

and `B) Pull and Run via Docker Compose`, it can install, but the postgres always report
```
FATAL: password authentication failed for user "postgres"
DETAIL: Password does not match for user "postgres".
```
i already tried [Rebuild Cardano DB](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db), but it doesn't work

**Comment by CyberCyclone** [comment]
> FATAL: password authentication failed for user "postgres"
> DETAIL: Password does not match for user "postgres".

I've always seen this and had no issues. If you use the docker pull based method, you'll still need to wait for the network to fully sync (18+ hours I think). 

Have you waited for it to sync or is there other errors?

**Comment by lpf763827726** [comment]
> 我一直看到这个并且没有问题。如果您使用基于 docker pull 的方法，您仍然需要等待网络完全同步（我认为 18 小时以上）。
> 
> 您是否等待它同步或是否有其他错误？

i still wait it sync, docker pull based method it just only the password not match, not other errors

**Comment by CyberCyclone** [comment]
> > 我一直看到这个并且没有问题。如果您使用基于 docker pull 的方法，您仍然需要等待网络完全同步（我认为 18 小时以上）。
> 
> > 
> 
> > 您是否等待它同步或是否有其他错误？
> 
> 
> 
> i still wait it sync, docker pull based method it just only the password not match, not other errors

Awesome. As long as you can see references to the "epochs" increasing then it's still syncing. Once you can see the epoch is in sync, do a docker-compose down and then start them up again and the graphql port should work.

**Comment by CyberCyclone** [comment]
> oh by the way, the Rebuild Cardano DB, i don't know why i always have to stop and rm the postgres-data and db-sync-data first before volume rm it
> 
> 
> 
> it let me have to run docker pull again, not only run docker-compose start

You only need to remove those volumes if cardano-db-sync requires you to drop them.

**Comment by lpf763827726** [comment]
> @lpf763827726 are you running baremetal or a server directly attached to the internet? If so then you might be seeing the same thing.

i running in baremetal,if docker ports can accessible from the outside, maybe it's my computer's postgresql link it? not the docker's error?

**Comment by CyberCyclone** [comment]
That's my suspicion since it can't be reproduced by the devs and I can only see it on my directly attached public servers. 

Here's some details, but do make sure you fully understand the issue that Docker introduces and the impact it has on your system before implementing any solution. This isn't advice from me, just a way to help explain the issue. https://github.com/chaifeng/ufw-docker

**Comment by lpf763827726** [comment]
ok, i will try it again, but i want to know, how can i not need to pull and rerun by this way [Rebuild Cardano DB](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db)

i was try to run
```
docker-compose stop
docker volume ls
docker stop *_postgres-data
docker rm *_postgres-data
docker volume rm *_postgres-data
docker stop *_db-sync-data
docker rm *_db-sync-data
docker volume rm *_db-sync-data
docker-compose start
```
always say missing container, then i only can repull and run it again, it takes a lot of time

**Comment by CyberCyclone** [comment]
The instructions on https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db are only for when cardano-db-sync requires you to drop the tables. You don't need to do it if you are simply stopping and starting.

The reason your commands are failing with "missing container" is because the `docker-compose stop` has already stopped all the containers. There should never be a reason to run `docker stop`. Also, `docker volume rm` and `docker stop` require the full container or volume name. As far as I know, using a wildcard `*` is interpreted literally and therefore the container `*_postgres-data` doesn't exist. 

To stop and start, the instructions on the GIt home page are all that's required.

**Comment by lpf763827726** [comment]
> As far as I know, using a wildcard `*` is interpreted literally and therefore the container `*_postgres-data` doesn't exist.

yea, i know it was a interpreted literally, the really name is `cardano-graphql_postgres-data` and `cardano-db-sync`
i just try `docker volume rm` it again, it remove volume success(not docker stop and rm container), then `docker-compose up` it again, still not match

![2021-10-22_12-24_1](https://user-images.githubusercontent.com/43004977/138393544-3e28c684-36d9-4a8f-ac4d-3e00e5a0cd01.png)
![2021-10-22_12-24_2](https://user-images.githubusercontent.com/43004977/138393548-7b43ce97-dff6-404d-9227-1dfc8eb1f731.png)
![2021-10-22_12-26](https://user-images.githubusercontent.com/43004977/138393551-ab8d6003-8cae-4e87-a476-4f2a55ce542f.png)

**Comment by lpf763827726** [comment]
i check my all command, nothing is connect the postgresql

**Comment by CyberCyclone** [comment]
> > As far as I know, using a wildcard `*` is interpreted literally and therefore the container `*_postgres-data` doesn't exist.
> 
> 
> 
> yea, i know it was a interpreted literally, the really name is `cardano-graphql_postgres-data` and `cardano-db-sync`
> 
> i just try `docker volume rm` it again, it remove volume success(not docker stop and rm container), then `docker-compose up` it again, still not match
> 
> 
> 
> ![2021-10-22_12-24_1](https://user-images.githubusercontent.com/43004977/138393544-3e28c684-36d9-4a8f-ac4d-3e00e5a0cd01.png)
> 
> ![2021-10-22_12-24_2](https://user-images.githubusercontent.com/43004977/138393548-7b43ce97-dff6-404d-9227-1dfc8eb1f731.png)
> 
> ![2021-10-22_12-26](https://user-images.githubusercontent.com/43004977/138393551-ab8d6003-8cae-4e87-a476-4f2a55ce542f.png)
> 
> 
Everything in those logs looks fine to me and it looks like it's starting up fine. So I'm not sure what the error is.

**Comment by lpf763827726** [comment]
> Everything in those logs looks fine to me and it looks like it's starting up fine. So I'm not sure what the error your reporting is.

is that mean actually i can ignore this error? It won't affect the API or restart docker?
