### ISSUE TITLE
db-sync-node.Subscription:Error:4070

### ISSUE THREAD

**Issue by wodingdong** [input-output-hk/cardano-graphql#626]
I already follow your readme document to run this cardano-graphql,
 

> git clone --single-branch --branch 6.0.0 --recurse-submodules https://github.com/input-output-hk/cardano-graphql.git && cd cardano-graphql

and

> DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 docker-compose up -d --build && docker-compose logs -f

I have to try to use 
> DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/11/db-sync-snapshot-schema-11-block-6278640-x86_64.tgz docker-compose up -d --build && docker-compose logs -f

It occur same error:

error information above:
```shell
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:4068] [2021-10-23 01:11:53.39 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2021-10-23 01:11:53.39 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:66] [2021-10-23 01:11:53.41 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:66] [2021-10-23 01:11:54.41 UTC] Identity Restarting Subscription after 1.026502384s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2021-10-23T01:11:54.955275633Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | [04971f52:cardano.node.ChainDB:Info:5] [2021-10-23 01:11:56.20 UTC] before next, messages elided = 31040728
cardano-node-ogmios_1       | [04971f52:cardano.node.ChainDB:Info:5] [2021-10-23 01:11:56.20 UTC] Replayed block: slot SlotNo 31060750 of At (SlotNo 31084183)
cardano-node-ogmios_1       | [04971f52:cardano.node.ChainDB:Info:5] [2021-10-23 01:11:56.28 UTC] Replayed block: slot SlotNo 31060781 of At (SlotNo 31084183)
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2021-10-23T01:11:59.960289103Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:66] [2021-10-23 01:12:03.39 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:4070] [2021-10-23 01:12:03.39 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:4070] [2021-10-23 01:12:03.39 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2021-10-23 01:12:03.39 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:66] [2021-10-23 01:12:03.42 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:66] [2021-10-23 01:12:04.42 UTC] Identity Restarting Subscription after 1.026451455s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2021-10-23T01:12:04.965269126Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2021-10-23T01:12:09.969449315Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}

cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:66] [2021-10-23 01:12:13.40 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:4072] [2021-10-23 01:12:13.40 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:4072] [2021-10-23 01:12:13.40 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2021-10-23 01:12:13.40 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:66] [2021-10-23 01:12:13.42 UTC] Identity Failed to start all required subscriptions

```
![image](https://user-images.githubusercontent.com/16595552/138536938-9dc3fbff-07da-4c42-99ef-90eb97ff418b.png)

【env】
> node -v
> v14.17.2

> docker-compose -v
> docker-compose version 1.29.2, build 5becea4c

**Comment by abumostafa** [comment]
Hey, did you find any solution? I'm facing same issue :(

**Comment by wodingdong** [comment]
> Hey, did you find any solution? I'm facing same issue :(

No, it didn't work well, It always gives this error, and the developers here seem to be ignoring these issues

**Comment by dagiopia** [comment]
I'm having the exact same issue and the sync has been running for four days. Any solution for this please?

**Comment by CyberCyclone** [comment]
I'm not a developer, but I know they've got their hands full on other things. I'm using cardano-graphql with ADATools and the current release (6.0.0) does work.

Here's what I do on a fresh setup.

Clone Repo:
```
git clone \
  --single-branch \
  --branch 6.0.0 \
  --recurse-submodules \
  https://github.com/input-output-hk/cardano-graphql.git \
  && cd cardano-graphql
```

DON'T Build, there's no point unless you've made your own changes. Use the instructions for pulling an existing Docker file, but also remove the "RESTORE_SNAPSHOT". I don't think it hurts to leave it, but I only use it when I have already fully synced cardano-node and it's just db-sync/postgres I'm wanting to restore.

```
export NETWORK=mainnet &&\
docker pull inputoutput/cardano-graphql:6.0.0-${NETWORK} &&\
docker pull inputoutput/cardano-graphql-hasura:6.0.0 &&\
docker pull cardanosolutions/cardano-node-ogmios:v4.1.0-${NETWORK} &&\
docker-compose up -d &&\
docker-compose logs -f
```

Wait at least 18 hours (maybe closer to 24 now) for it to fully sync.

Bring down the stack:

```
docker-compose down
```

Bring it back up:
```
docker-compose up -d &&\
docker-compose logs -f
```

The startup can take anywhere from 15 minutes to 45 minutes depending on your hardware and how many IOPS your SSD has provisioned (avoid AWS due to the way IOPS are provisioned unless you know what you're doing). Once cardano-node / gmios is receiving blocks you should be able to go to the GraphQL port.

Due to the fact that the current epoch data is kept in memory, it will roll back to the end of the last epoch and then start to replay from there to the current block tip; this process can take anywhere from 15 minutes to an hour depending on how far the tip is in the epoch. As in, if you're at day 5 of the epoch, expect the replay to take a while.

SUMMARY:
Based on the error above, it's hard to tell what the issue is, but it could be that you need to wait some time for cardano-node to start up if it's already synced. Some people wait 1 minute and assume it's broken and then kill it, but you need to wait.

Typically I've solved most start up issues just by bringing the stack down, bringing it up again and then waiting an hour.

**Comment by erikd** [comment]
> I'm having the exact same issue and the sync has been running for four days. Any solution for this please?

I am the main dev on `cardano-db-sync` which `graphql` sits on top of. If you sync from genesis on mainnet, it will take numerous days to sync. Between 4 and 8 days is expected.

However, IOHK/IOG releases snapshots of the database and other state as a snapshot which dramactically reduces the time needed to restore a `db-sync` instance.

**Comment by CyberCyclone** [comment]
> However, IOHK/IOG releases snapshots of the database and other state as a snapshot which dramactically reduces the time needed to restore a db-sync instance.

Just double checking. As far as I understand the snapshot does not include any cardano-node data. Does using the snapshot from an initial sync speed it up significantly or is it still held back by cardano-node syncing?

**Comment by erikd** [comment]
The snapshot does not include `cardano-node` data. However, the `node` syncs mainnet in well under day while `db-sync` takes several days.
