### ISSUE TITLE
docker-compose on testnet started successfully, but pg database init failed

### ISSUE THREAD

**Issue by somereason** [input-output-hk/cardano-graphql#628]
I use the following commend to start docker-compose
```
export NETWORK=testnet &&\
docker pull inputoutput/cardano-graphql:6.0.0-${NETWORK} &&\
docker pull inputoutput/cardano-graphql-hasura:6.0.0 &&\
docker pull cardanosolutions/cardano-node-ogmios:v4.1.0-${NETWORK} &&\
RESTORE_SNAPSHOT=https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/11/db-sync-snapshot-schema-11-block-2944498-x86_64.tgz \
docker-compose -p ${NETWORK} up -d &&\
docker-compose -p ${NETWORK} logs -f
```

and block sync is successful, but postgres sql has no table. and log says init sql execute failed. log says packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql execute failed, so I checked this file, find it just create views, tables are not created. I think you should execute schema sql  first.

**Comment by rhyslbw** [comment]
The tables are created by `cardano-db-sync`, and it's expected to see some failures that crash and cause service restarts initially while services are all booted sequentially. Sorry for the late reply, feel free to reopen if you're still seeing having trouble.
