### ISSUE TITLE
what is the machine Requirements , My machine is 8C 16G But is memory is become bigger and bigger, what is the problem , Memory leak

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#634]

**Comment by CyberCyclone** [comment]
Typically the RAM usage will grow as the cache in RAM increases, which is standard for a lot of databases. I've got servers with 64GB of RAM and typically it won't go above 29GB of RAM usage. So the minimum requirements are a lot lower, but if there's RAM it can use then it will.

**Comment by malingzhao** [comment]
It is 32 G ok

**Comment by CyberCyclone** [comment]
The official requirements according to db-sync (which is what cardano-graphql is based on) is 16GB, so 32GB should easily be enough unless you're doing hundreds + of concurrent queries. https://github.com/input-output-hk/cardano-db-sync
