### ISSUE TITLE
RESTORE_SNAPSHOT migrations can't run 

### ISSUE THREAD

**Issue by ctscobra** [input-output-hk/cardano-graphql#635]
Fresh installation with latest snapshot fails due to migrations not able to run. 99% of them already exist and can't be run .
Yesterday i spent hours checking them and manually increasing version counter and doing manual alters until they finished.
But in end did not have working setup.

running with : `export NETWORK=mainnet && docker pull inputoutput/cardano-graphql:6.0.0-${NETWORK} && docker pull inputoutput/cardano-graphql-hasura:6.0.0 && docker pull cardanosolutions/cardano-node-ogmios:v4.1.0-${NETWORK} && RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6451499-x86_64.tgz docker-compose up -d && docker-compose logs -f`

Today i started again and again facing migration issues (first one being):

`postgres_1                  | 2021-11-11 11:05:01.940 UTC [1502] ERROR:  column "op_cert_counter" of relation "block" already exists
postgres_1                  | 2021-11-11 11:05:01.940 UTC [1502] CONTEXT:  SQL statement "ALTER TABLE "block" ADD COLUMN "op_cert_counter" word63type NULL"
postgres_1                  |   PL/pgSQL function migrate() line 7 at EXECUTE
postgres_1                  | 2021-11-11 11:05:01.940 UTC [1502] STATEMENT:  SELECT migrate() ;
mainnet_cardano-db-sync-extended_1 exited with code 1
postgres_1                  | 2021-11-11 11:05:17.355 UTC [1431] ERROR:  column epoch_param.cost_models does not exist at character 3095`

this will happen for almost any alter in all migration scripts and creating new columns with NOT NULL will miss default value.

**Comment by CyberCyclone** [comment]
As far as I know the snapshot files only restore db-sync. @rhyslbw please correct me if I'm wrong, but I'm pretty sure the snapshot doesn't include cardano-node data.

For a fresh install you will need to run the commands but without the 'RESTORE_SNAPSHOT' line. I'm not sure if leaving it in has an impact or if it's ignored for a fresh install, but I've always taken it out for fresh runs. It can take 18+ hours to fully sync. Once it's fully synced, bring the stack down and bring it up again, then it should work correctly.

The snapshot file is good for when you need to restore just the db-sync and postgres data.

Whenever I start up a fresh install I always do a fresh full sync so I know that all the blockchain data is true.

**Comment by ctscobra** [comment]
Hmm i tried this due to fresh install being stuck for a ~week in parallel on 2 servers. 
I am trying to find a way to make installing and syncing faster (even tried copying the docker data and volumes to new server from 100% synced one and that works but it is a pain.)

What would be you best practise to populate new server if you have existing server on side lines? (or fresh)

Also it seems that 30GB of RAM with 2GB SWAP is not enough and 100% of SWAP is used all the time and all RAM (either as cache or real usage).

**Comment by rhyslbw** [comment]
@CyberCyclone 
> As far as I know the snapshot files only restore db-sync. @rhyslbw please correct me if I'm wrong, but I'm pretty sure the snapshot doesn't include cardano-node data.

That's correct, there's no `cardano-node` state snapshot. 

> For a fresh install you will need to run the commands but without the 'RESTORE_SNAPSHOT' line.

:+1: 

> I'm not sure if leaving it in has an impact or if it's ignored for a fresh install, but I've always taken it out for fresh runs.

On a fresh install it will restore the snapshot but then roll back to the node's tip, effectively producing a void result. We're just using the facility provided by the `cardano-db-sync` Docker image, so there's no much we can do about usability. 

@ctscobra 
> What would be you best practise to populate new server if you have existing server on side lines? (or fresh)

Start the stack with just the `cardano-node` service and let it sync. It will take a while, but will be much faster than a full `cardano-sb-sync` genesis sync. Once at the network tip, stop the Docker Compose stack, add the other services back in with `RESTORE_SNAPSHOT`, then start it all back up together. This will apply the snapshot and then sync the last part of the chain within a fraction of the time.

> Also it seems that 30GB of RAM with 2GB SWAP is not enough and 100% of SWAP is used all the time and all RAM (either as cache or real usage).

Seems a little high, but the system demand for the _mainnet_ is growing at quite a rate. I would try bumping the RAM to 64GB, then observe the usage over an epoch to determine a maximum required.
