### ISSUE TITLE
Is it possible to provide a detailed tutorial for upgrading

### ISSUE THREAD

**Issue by vae520283995** [input-output-hk/cardano-graphql#643]
Every time a new version is released, the database must be rebuilt. I can only empty the data directory and start syncing from 0, which took more than 50 hours. I am very happy to upgrade to the new version. At the same time, I am also very upset that it takes a lot of time to upgrade. I hope to publish some tutorials so that I can upgrade from the fully synchronized old version to the new version as soon as possible. Thank you.

**Comment by vae520283995** [comment]
@rhyslbw @CyberCyclone Hi, Can you help me？

**Comment by rhyslbw** [comment]
You can now use the `cardano-db-sync` DB snapshot to expedite the upgrade, and I've just updated the [Wiki](https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db) to direct you back to the _Getting Started_ section of the README after removing the volumes. Please try this procedure first, then let me know if you require further assistance.

**Comment by vae520283995** [comment]
```
 volumes:
      - ./config/network/${NETWORK:-mainnet}:/config
      - ./data/db-sync-data:/var/lib/cdbsync
      - ./data/node-ipc:/node-ipc
```
```
root:/node/cardano/v6.1.0/cardano-graphql/data# ls
db-sync-data  node-db  node-ipc  postgres-data
```
I designated the volume as the data directory under the current directory, how should I delete the volume? Delete the directory directly?

**Comment by vae520283995** [comment]
```
volumes:
  db-sync-data:
  node-db:
  node-ipc:
  postgres-data:
```
https://github.com/input-output-hk/cardano-graphql/blob/2202252d2a36e493f00ac0434063f75a363f8020/docker-compose.yml?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L133

By the way, how should I make a local directory in this place？

**Comment by CyberCyclone** [comment]
> ```
>  volumes:
>       - ./config/network/${NETWORK:-mainnet}:/config
>       - ./data/db-sync-data:/var/lib/cdbsync
>       - ./data/node-ipc:/node-ipc
> ```
> 
> 
>      
>   
> 
> ```
> root:/node/cardano/v6.1.0/cardano-graphql/data# ls
> db-sync-data  node-db  node-ipc  postgres-data
> ```
> 
> 
>      
>   
> 
> I designated the volume as the data directory under the current directory, how should I delete the volume? Delete the directory directly?

Deleting the directories for `_postgres-data` and `_db-sync-data` would have the same result, but you could also rename the folder as a quick backup to the previous version.

**Comment by CyberCyclone** [comment]
It's probably better to not store the data in the current directory though as it makes it difficult to do Git updates as it will complain about updated files not being committed.

**Comment by rhyslbw** [comment]
> By the way, how should I specify the local directory in this place？

You can just omit any mounted host paths from this section. See
https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes

**Comment by vae520283995** [comment]
Thank you, if I start syncing from 0, how do I use snapshot sync?

**Comment by CyberCyclone** [comment]
You just need to add the snapshot URL variable (make sure you have the right snapshot associated with the right db-sync version). 

If you only remove db-sync and postgres volumes and the rest is in sync then it will import the snapshot and then sync up once it's imported. This is insanely faster then the db following the chain and inserting block by block. 

If you're starting everything from scratch, using the snapshot is still fast then following the chain. As in, cardano-node can sync a lot quicker then db-sync takes to populate. So an import will be faster regardless.

**Comment by vae520283995** [comment]
> If you're starting everything from scratch, using the snapshot is still faster than following the chain. As in, cardano-node can sync a lot quicker than db-sync takes to populate. So an import will be faster regardless.

```
[db-sync-node.Handshake:Info:49] [2021-12-22 12:57:01.59 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Send (ClientAgency TokPropose,MsgProposeVersions (fromList [(NodeToClientV_1,TInt 764824073),(NodeToClientV_2,TInt 764824073),(NodeToClientV_3,TInt 764824073),(NodeToClientV_4,TInt 764824073),(NodeToClientV_5,TInt 764824073),(NodeToClientV_6,TInt 764824073),(NodeToClientV_7,TInt 764824073),(NodeToClientV_8,TInt 764824073),(NodeToClientV_9,TInt 764824073),(NodeToClientV_10,TInt 764824073)]))
[db-sync-node.Subscription:Notice:48] [2021-12-22 12:57:01.62 UTC] Identity Required subscriptions started
[db-sync-node.Handshake:Info:49] [2021-12-22 12:57:01.63 UTC] WithMuxBearer (ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"}) Recv (ServerAgency TokConfirm,MsgAcceptVersion NodeToClientV_10 (TInt 764824073))
[db-sync-node.Mux:Info:49] [2021-12-22 12:57:01.63 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: Handshake Client end, duration 0.035786967s
[db-sync-node.Mux:Info:50] [2021-12-22 12:57:01.63 UTC] Bearer on ConnectionId {localAddress = LocalAddress "", remoteAddress = LocalAddress "/ipc/node.socket"} event: State: Mature
[db-sync-node:Info:53] [2021-12-22 12:57:01.63 UTC] Starting chainSyncClient
[db-sync-node:Info:53] [2021-12-22 12:57:01.64 UTC] Cardano.Db tip is at slot 48360823, block 6647999
[db-sync-node:Info:58] [2021-12-22 12:57:01.64 UTC] Running DB thread
[db-sync-node:Info:58] [2021-12-22 12:57:01.95 UTC] Rolling back to genesis
[db-sync-node:Info:58] [2021-12-22 12:57:30.20 UTC] Deleting 6647999 blocks up to slot 48360823
```

I use snapshots to sync from a new server, it seems Rolling back to genesis

**Comment by vae520283995** [comment]
@rhyslbw 
https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db
Should execute docker-compose down instead of docker-compose stop

**Comment by vae520283995** [comment]
Initial synchronization, the snapshot cannot be used, you must wait for the cardano-node-ogmios synchronization to complete before you can use the snapshot

**Comment by vae520283995** [comment]
@rhyslbw @CyberCyclone Thank you, I now have the knack for using snapshots
