### ISSUE TITLE
cardano-graphql-cardano-db-sync-extended-1  | [db-sync-node.Subscription:Notice:130] [2022-01-04 03:53:45.73 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#646]
### Environment
The [CLI](../../packages/cli) can be used to gather generic information about your system to assist with support.
No installation is required thanks to [npx](https://github.com/npm/npx)

``` console
npx @cardano-graphql/cli system-info
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [ ] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [ ] Docker

**Runtime version**: 
```console
node -v
docker version
```

### What is the expected behavior?

**Comment by CyberCyclone** [comment]
The node is still starting up. Mainnet can take at least 10 - 20 minutes for cardano-node to start before the other services (db-sync) can connect.
