### ISSUE TITLE
cardano-db-sync-extended is it the same as cardano-db-sync

### ISSUE THREAD

**Issue by dorijan** [input-output-hk/cardano-graphql#651]
Hi to all,
I am using cardano-db-sync with cardano-wallet, cardano-node and ogmios_1 and of course postgres on one other project but there I am using just cardano-db-sync. Is this the same? Can I use the same db?
Thank you

**Comment by CyberCyclone** [comment]
Here's a full doc on what the components are.

https://docs.cardano.org/explore-cardano/cardano-architecture/about-db-sync-and-its-components

`cardano-db` – defines common data types and functions used by any application that needs to interact with the database from Haskell. In particular, it defines the database schema.
`cardano-db-tool` – a tool used to manage cardano-db-sync databases (create, run, validate and analyze migrations).
`cardano-db-sync` – acts as a Cardano node, following the chain and inserting data from the chain into a PostgreSQL database.
`cardano-db-sync-extended` – a relatively simple extension to cardano-db-sync, which maintains an extra table containing epoch data.
`db-sync-node` – designed to work with a locally running Cardano Node to store data in the PostgreSQL database.

Then you have this library that you've opened an issue on, `cardano-graphql` which just converts `cardano-db-sync` into a GraphQL endpoint.

**Comment by dorijan** [comment]
Great, thank you!
