### ISSUE TITLE
why

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#656]
ql-postgres-1                  | 2022-01-16 03:28:35.419 UTC [8721] STATEMENT:  WITH "Asset__mutation_result_alias" AS (UPDATE "public"."Asset" SET "decimals" = ($1)::integer,"description" = ($2)::text,"logo" = ($3)::text,"metadataHash" = ($4)::bpchar,"name" = ($5)::text,"ticker" = ($6)::text,"url" = ($7)::text  WHERE (('true') AND ((((("public"."Asset"."assetId") = (($8)::bytea)) AND ('true')) AND ('true')) AND ('true'))) RETURNING * , CASE WHEN 'true' THEN NULL ELSE "hdb_catalog"."check_violation"('update check constraint failed')  END ), "Asset__all_columns_alias" AS (SELECT  "assetId" , "assetName" , "decimals" , "description" , "fingerprint" , "firstAppearedInSlot" , "logo" , "metadataHash" , "name" , "policyId" , "ticker" , "url"  FROM "Asset__mutation_result_alias"      ) SELECT  json_build_object('affected_rows', (SELECT  COUNT(*)  FROM "Asset__all_columns_alias"      ), 'returning', (SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."assetId" AS "assetId"       ) AS "_1_e"      ) ) AS "root" FROM  (SELECT  *  FROM "Asset__all_columns_alias" WHERE ('true')     ) AS "_0_root.base"      ) AS "_2_root"      ) ) cardano-graphql-postgres-1                  | 2022-01-16 03:29:55.175 UTC [8811] ERROR:  value too long for type character varying(65536) cardano-graphql-postgres-1                  | 2022-01-16 03:29:55.175 UTC [8811] STATEMENT:  WITH "Asset__mutation_result_alias" AS (UPDATE "public"."Asset" SET "decimals" = ($1)::integer,"description" = ($2)::text,"logo" = ($3)::text,"metadataHash" = ($4)::bpchar,"name" = ($5)::text,"ticker" = ($6)::text,"url" = ($7)::text  WHERE (('true') AND ((((("public"."Asset"."assetId") = (($8)::bytea)) AND ('true')) AND ('true')) AND ('true'))) RETURNING * , CASE WHEN 'true' THEN NULL ELSE "hdb_catalog"."check_violation"('update check constraint failed')  END ), "Asset__all_columns_alias" AS (SELECT  "assetId" , "assetName" , "decimals" , "description" , "fingerprint" , "firstAppearedInSlot" , "logo" , "metadataHash" , "name" , "policyId" , "ticker" , "url"  FROM "Asset__mutation_result_alias"      ) SELECT  json_build_object('affected_rows', (SELECT  COUNT(*)  FROM "Asset__all_columns_alias"      ), 'returning', (SELECT  coalesce(json_agg("root" ), '[]' ) AS "root" FROM  (SELECT  row_to_json((SELECT  "_1_e"  FROM  (SELECT  "_0_root.base"."assetId" AS "assetId"       ) AS "_1_e"      ) ) AS "root" FROM  (SELECT  *  FROM "Asset__all_columns_alias" WHERE ('true')     ) AS "_0_root.base"      ) AS "_2_root"      ) ) cardano-graphql-postgres-1                  | 2022-01-16 03:32:25.573 UTC [8787] ERROR:  value too long for type character varying(65536) cardano-graphql-postgres-1                  |

**Comment by CyberCyclone** [comment]
Please fill in the issue template and give some context. Without knowing how you got to this stage and how to replicate it there isn't any chance of anyone being able to help you.
