### ISSUE TITLE
Querying assets returns null 

### ISSUE THREAD

**Issue by marijanp** [input-output-hk/cardano-graphql#666]
Using the following Query I get always returned null for any field of asset. What could be the reason for this?
`curl   -X POST   -H "Content-Type: application/json"   -d '{"query": "{ tokenMints { quantity asset { name } }    }"}' http://localhost:9999/v1/graphql`
returns
`{"data":{"tokenMints":[{"quantity":1,"asset":null}, {"quantity":1,"asset":null}]}}`

**Comment by marijanp** [comment]
I suspect it is related to #664 as the table `Asset` is created in this [migration](https://github.com/input-output-hk/cardano-graphql/blob/43c7850b11c9f3bc868267f4efab57a71973d21f/packages/api-cardano-db-hasura/hasura/project/migrations/1589369664961_init/up.sql#L14) and this also populates this table. Inspecting the postgres database I found out that the table multi_asset is populated as expected but Asset is empty.

**Comment by rhyslbw** [comment]
Yes, let's close this and keep the discussion in one place.
