### ISSUE TITLE
Unable to restore from PG snapshot

### ISSUE THREAD

**Issue by zikarad** [input-output-hk/cardano-graphql#668]
### Environment
Docker-compose

**Alternatively, what release or Git revision are you using:**
6.1.0

#### Platform

- [ x] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 
20.04LTS

#### Runtime

- [ ] Node.js
- [ x] Docker

**Runtime version**: 
Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58

### Steps to reproduce the bug
RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6793499-x86_64.tgz \
docker-compose up -d

### What is the expected behavior?
PG restored from snapshot and started

### Observed behavior
```
cardano-db-sync-extended_1  | db-sync-snapshot-schema-12-block-6793499-x86_64.tgz: OK                                                                   [92/1995]
postgres_1                  | 2022-01-27 16:35:11.252 UTC [182] ERROR:  cannot drop objects owned by role postgres because they are required by the database syst
em
postgres_1                  | 2022-01-27 16:35:11.252 UTC [182] STATEMENT:  DROP OWNED BY CURRENT_USER;
cardano-db-sync-extended_1  | ERROR:  cannot drop objects owned by role postgres because they are required by the database system
```

**Comment by rhyslbw** [comment]
Try dropping the postgres and db-sync volumes and retrying: https://github.com/input-output-hk/cardano-graphql/wiki/Docker#rebuild-cardano-db

**Comment by Robinyo** [comment]
See: [Getting started with Cardano GraphQL](https://robferguson.org/blog/2022/02/19/getting-started-with-cardano-graphql/)

**Comment by Displee** [comment]
Dropping the volumes did not work for me.
