### ISSUE TITLE
I found this error

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#683]
\\\n  stake_address.view \\\\\\\"address\\\\\\\",\\\\n  withdrawal.redeemer_id AS \\\\\\\"redeemerId\\\\\\\",\\\\n  withdrawal.tx_id AS \\\\\\\"tx_id\\\\\\\"\\\\nFROM withdrawal\\\\nJOIN stake_address on withdrawal.addr_id = stake_address.id;\\\\n\\\\nCREATE INDEX idx_block_hash\\\\n    ON block(hash);\\\\n\\\\nCREATE INDEX idx_multi_asset_name\\\\n    ON multi_asset(name);\\\\n\\\\nCREATE INDEX idx_multi_asset_policy\\\\n    ON multi_asset(policy);\\\\n\\\\nCREATE INDEX idx_reward_type\\\\n    ON reward(type);\\\\n\\\\nCREATE INDEX idx_tx_hash\\\\n    ON tx(hash);\\\\n\\\\nCREATE INDEX idx_tx_in_consuming_tx\\\\n   ON tx_in(tx_out_id);\\\\n\\\\nCREATE INDEX idx_tx_out_tx\\\\n    ON tx_out(tx_id);\\\\n\\\\nCREATE function utxo_set_at_block(\\\\\\\"hash\\\\\\\" hash32type)\\\\nRETURNS SETOF \\\\\\\"TransactionOutput\\\\\\\" AS $$\\\\n  SELECT\\\\n    \\\\\\\"TransactionOutput\\\\\\\".address,\\\\n    \\\\\\\"TransactionOutput\\\\\\\".\\\\\\\"addressHasScript\\\\\\\",\\\\n    \\\\\\\"TransactionOutput\\\\\\\".value,\\\\n    \\\\\\\"TransactionOutput\\\\\\\".\\\\\\\"txHash\\\\\\\",\\\\n    \\\\\\\"TransactionOutput\\\\\\\".\\\\\\\"id\\\\\\\",\\\\n    \\\\\\\"TransactionOutput\\\\\\\".index\\\\n  FROM tx\\\\n  JOIN tx_out\\\\n    ON tx.id = tx_out.tx_id\\\\n  JOIN \\\\\\\"TransactionOutput\\\\\\\"\\\\n    ON tx.hash = \\\\\\\"TransactionOutput\\\\\\\".\\\\\\\"txHash\\\\\\\"\\\\n  LEFT OUTER JOIN tx_in\\\\n    ON tx_out.tx_id = tx_in.tx_out_id\\\\n    AND tx_out.index = tx_in.tx_out_index\\\\n  WHERE tx_in.tx_in_id IS NULL\\\\n  AND tx.block_id \\\\u003c= (SELECT id FROM block WHERE hash = \\\\\\\"hash\\\\\\\")\\\\n$$ LANGUAGE SQL stable;\\\\n\\\\n\\\"\\n}\\r\\n[42P01] FatalError: relation \\\"ada_pots\\\" does not exist\"\n","time":"2022-02-17T10:16:09.279Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"Server","msg":"Initializing","time":"2022-02-17T10:16:13.766Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"HasuraClient","msg":"Initializing","time":"2022-02-17T10:16:14.028Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2022-02-17T10:20:25.304Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2022-02-17T10:20:25.305Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initialized","time":"2022-02-17T10:20:25.336Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2022-02-17T10:20:25.336Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":50,"msg":"Cannot read property 'status' of undefined","time":"2022-02-17T10:22:36.541Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: cardano-db-sync-extended starting, schema will be reset","time":"2022-02-17T14:10:36.089Z","v":0} (node:1) UnhandledPromiseRejectionWarning: Error: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}     at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)     at step (/app/node_modules/graphql-request/dist/index.js:63:23)     at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)     at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)     at runMicrotasks (<anonymous>)     at processTicksAndRejections (internal/process/task_queues.js:95:5) (Use `node --trace-warnings ...` to show where the warning was created) (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2) (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"ChainFollower","msg":"Initializing","time":"2022-02-17T14:12:37.813Z","v":0} {"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"ChainFollower","msg":"Initialized","time":"2022-02-17T14:12:37.833Z","v":0}

**Comment by lcgogo** [comment]
> See: [Getting started with Cardano GraphQL](https://robferguson.org/blog/2022/02/19/getting-started-with-cardano-graphql/)

Where can download the snapthot?

**Comment by Robinyo** [comment]
mainnet: https://update-cardano-mainnet.iohk.io/cardano-db-sync/index.html#12/
testnet: https://updates-cardano-testnet.s3.amazonaws.com/cardano-db-sync/index.html#12/
