### ISSUE TITLE
start up with docker compose fail. 

### ISSUE THREAD

**Issue by kiddx01** [input-output-hk/cardano-graphql#684]
### Environment
docker version:
Docker version 20.10.12, build e91ed57

``` console
root@iZj6c8znm5l1ysn7c1dxstZ:/data/ada/cardano-graphql# DOCKER_BUILDKIT=1 \
> COMPOSE_DOCKER_CLI_BUILD=1 \
> RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6764999-x86_64.tgz \
> docker-compose up -d --build &&\
> docker-compose logs -f
ERROR: yaml.scanner.ScannerError: while scanning a plain scalar
  in "./docker-compose.yml", line 31, column 21
found unexpected ':'
  in "./docker-compose.yml", line 31, column 57
Please check http://pyyaml.org/wiki/YAMLColonInFlowContext for details.
root@iZj6c8znm5l1ysn7c1dxstZ:/data/ada/cardano-graphql#
```
[PASTE_REPORT_HERE]

**Alternatively, what release or Git revision are you using:**

#### Platform

- [√ ] Linux / Ubuntu
- [ ] Linux / Other
- [ ] macOS
- [ ] Windows

**Platform version**: 

#### Runtime

- [ ] Node.js
- [√ ] Docker

**Runtime version**: 
```console
 node -v
v16.14.0
docker version
```

### Steps to reproduce the bug
# 1
git clone   --single-branch   --branch 6.2.0   --recurse-submodules   https://github.com/input-output-hk/cardano-graphql.git   && cd cardano-graphq
# 2
DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 RESTORE_SNAPSHOT=https://update-cardano-mainnet.iohk.io/cardano-db-sync/12/db-sync-snapshot-schema-12-block-6764999-x86_64.tgz docker-compose up -d --build &&docker-compose logs -f

### What is the expected behavior?

**Comment by Robinyo** [comment]
See: [Getting started with Cardano GraphQL](https://robferguson.org/blog/2022/02/19/getting-started-with-cardano-graphql/)

**Comment by Decision2016** [comment]
I also encountered this problem, maybe you can update your **docker-compose to version 1.25.4**?After update docker-compose from version 1.17.1 to 1.25.4 then it worked.
