### ISSUE TITLE
docker log

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#685]
"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"HasuraClient","msg":"Initialized","time":"2022-02-17T10:20:25.304Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initializing. This can take a few minutes...","time":"2022-02-17T10:20:25.305Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"CardanoNodeClient","msg":"Initialized","time":"2022-02-17T10:20:25.336Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"MetadataFetchClient","msg":"Initializing","time":"2022-02-17T10:20:25.336Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":50,"msg":"Cannot read property 'status' of undefined","time":"2022-02-17T10:22:36.541Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":40,"module":"Db","msg":"pgSubscriber: cardano-db-sync-extended starting, schema will be reset","time":"2022-02-17T14:10:36.089Z","v":0}
(node:1) UnhandledPromiseRejectionWarning: Error: database query error: {"response":{"errors":[{"extensions":{"path":"$","code":"unexpected"},"message":"database query error"}],"status":200},"request":{"query":"query {\n          epochs (limit: 1, order_by: { number: desc }) {\n              adaPots {\n                  reserves\n              }\n          }\n          rewards_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n          utxos_aggregate {\n              aggregate {\n                  sum {\n                      value\n                  }\n              }\n          }\n          withdrawals_aggregate {\n              aggregate {\n                  sum {\n                      amount\n                  }\n              }\n          }\n      }"}}
    at GraphQLClient.<anonymous> (/app/node_modules/graphql-request/dist/index.js:170:35)
    at step (/app/node_modules/graphql-request/dist/index.js:63:23)
    at Object.next (/app/node_modules/graphql-request/dist/index.js:44:53)
    at fulfilled (/app/node_modules/graphql-request/dist/index.js:35:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"ChainFollower","msg":"Initializing","time":"2022-02-17T14:12:37.813Z","v":0}
{"name":"cardano-graphql","hostname":"f8ed14899758","pid":1,"level":30,"module":"ChainFollower","msg":"Initialized","time":"2022-02-17T14:12:37.833Z","v":0}

**Comment by Robinyo** [comment]
See: [Getting started with Cardano GraphQL](https://robferguson.org/blog/2022/02/19/getting-started-with-cardano-graphql/)
