### ISSUE TITLE
Is cardarno-graphql-ts up-to-date?

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-graphql#688]
```
(alias) type TransactionOutput = {
    __typename?: "TransactionOutput" | undefined;
    address: Scalars['String'];
    index: Scalars['Int'];
    txHash: Scalars['Hash32HexString'];
    value: Scalars['String'];
}
import TransactionOutput
```

I installed `cardano-graphql-ts` with yarn. There is no `tokens` in `TransactionOutput`. `Token` type is missing too.

**Comment by Robinyo** [comment]
@siegfried 

Are you raising an issue with the correct project?  What is 'cardano-graph-ts'?

**Comment by siegfried** [comment]
@Robinyo Sorry, I had a typo. It is `cardamon-graphql-ts`. https://www.npmjs.com/package/cardano-graphql-ts

**Comment by rhyslbw** [comment]
Please use the new org-scoped package https://www.npmjs.com/package/@cardano-graphql/client-ts
