### ISSUE TITLE
There have been a few times when running has gone wrong

### ISSUE THREAD

**Issue by kiddx01** [input-output-hk/cardano-graphql#691]
ardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:48] [2022-02-27 03:21:39.57 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:21:40.58 UTC] Identity Restarting Subscription after 1.026390036s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:21:41.672205389Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:21:46.673207441Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:21:49.56 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:53] [2022-02-27 03:21:49.56 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:53] [2022-02-27 03:21:49.56 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2022-02-27 03:21:49.56 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:48] [2022-02-27 03:21:49.58 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:21:50.58 UTC] Identity Restarting Subscription after 1.026358454s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:21:51.676272063Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:21:56.678628141Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:21:59.56 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:55] [2022-02-27 03:21:59.56 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:55] [2022-02-27 03:21:59.56 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2022-02-27 03:21:59.56 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:48] [2022-02-27 03:21:59.58 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:22:00.59 UTC] Identity Restarting Subscription after 1.026420236s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:22:01.68111521Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:22:06.683471893Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:22:09.57 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:57] [2022-02-27 03:22:09.57 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:57] [2022-02-27 03:22:09.57 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2022-02-27 03:22:09.57 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:48] [2022-02-27 03:22:09.59 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:22:10.59 UTC] Identity Restarting Subscription after 1.026436656s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:22:11.685889345Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:22:16.686995933Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:22:19.58 UTC] Identity Starting Subscription Worker, valency 1
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:59] [2022-02-27 03:22:19.58 UTC] Identity Connection Attempt Start, destination LocalAddress "/node-ipc/node.socket"
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Error:59] [2022-02-27 03:22:19.58 UTC] Identity Connection Attempt Exception, destination LocalAddress "/node-ipc/node.socket" exception: Network.Socket.connect: <socket: 22>: does not exist (No such file or directory)
cardano-db-sync-extended_1  | [db-sync-node.ErrorPolicy:Warning:6] [2022-02-27 03:22:19.58 UTC] IP LocalAddress "/node-ipc/node.socket" ErrorPolicySuspendPeer (Just (ConnectionExceptionTrace Network.Socket.connect: <socket: 22>: does not exist (No such file or directory))) 20s 20s
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Warning:48] [2022-02-27 03:22:19.60 UTC] Identity Failed to start all required subscriptions
cardano-db-sync-extended_1  | [db-sync-node.Subscription:Notice:48] [2022-02-27 03:22:20.60 UTC] Identity Restarting Subscription after 1.026575356s desired valency 1 current valency 0
cardano-node-ogmios_1       | {"severity":"Warning","timestamp":"2022-02-27T03:22:21.688272263Z","thread":"7","message":{"tag":"OgmiosHealth","healthCheck":{"tag":"HealthFailedToConnect","socket":"/ipc/node.socket","retryingIn":5}},"version":"v4.1.0"}
^Ccanceled

**Comment by kiddx01** [comment]
And the restart cannot be restored

**Comment by Robinyo** [comment]
See: [Getting started with Cardano GraphQL](https://robferguson.org/blog/2022/02/19/getting-started-with-cardano-graphql/)
