### ISSUE TITLE
docker logs -f cardano-graphql

### ISSUE THREAD

**Issue by malingzhao** [input-output-hk/cardano-graphql#695]
":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"ccb3577601d6cf0e021288871112926338bee685c6c37eeadf6dddd943617264616e6961466f756e646572426c7565","msg":"Adding metadata to asset","time":"2022-03-04T02:56:23.707Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"ccb3577601d6cf0e021288871112926338bee685c6c37eeadf6dddd943617264616e6961466f756e646572477265656e","msg":"Adding metadata to asset","time":"2022-03-04T02:56:23.713Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"ccb3577601d6cf0e021288871112926338bee685c6c37eeadf6dddd943617264616e6961466f756e646572526564","msg":"Adding metadata to asset","time":"2022-03-04T02:56:23.720Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54796335,"hash":"7dbc85b1764d4ec47b64fd166753c741de0d80deb3cf1f84e273b3e3f7005792","blockNo":6952907},"rollbackPoint":{"slot":54796305,"hash":"ea4eaeb6c1c06dd5d5d1fd801c9521a65dfc77629e8a57c7622b2b85842f0f92"},"msg":"Rolling back","time":"2022-03-04T02:57:08.406Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 0 assets","time":"2022-03-04T02:57:09.029Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54796495,"hash":"eff367c146b64ffc66693d5523e7abb4c16eb49d7d847840f1b1596ed5269f20","blockNo":6952915},"rollbackPoint":{"slot":54796470,"hash":"1378b86624d993401825fbf85147b4cbfec8322cf46d2a2129ea90b9b13fe5bb"},"msg":"Rolling back","time":"2022-03-04T02:59:49.330Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 0 assets","time":"2022-03-04T02:59:49.964Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54796496,"hash":"6fbb9e0563a44ed86610cc736358695ea61ef9023c380e4c7078a1268d6cff67","blockNo":6952916},"rollbackPoint":{"slot":54796470,"hash":"1378b86624d993401825fbf85147b4cbfec8322cf46d2a2129ea90b9b13fe5bb"},"msg":"Rolling back","time":"2022-03-04T02:59:50.519Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 0 assets","time":"2022-03-04T02:59:51.170Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54796647,"hash":"5f1a996ac4617fe1a800e02ae1683dacf8152f5cb3ed123f59c097ca57324aab","blockNo":6952923},"rollbackPoint":{"slot":54796638,"hash":"d24adcc1766be38350624502e5fbc6c67e0d8cb327b95a85d28e234c3930c3e0"},"msg":"Rolling back","time":"2022-03-04T03:02:20.445Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 1 assets","time":"2022-03-04T03:02:21.079Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54796834,"hash":"96db9fcee2994ef27277f49ca465558111e40c1f9e9a727039778fc09e6005b5","blockNo":6952932},"rollbackPoint":{"slot":54796828,"hash":"e7dd6d29a1a3da1cc4c0b640b0e87d42cf220eb341d68c81a734fc0217d8a32d"},"msg":"Rolling back","time":"2022-03-04T03:05:28.195Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 1 assets","time":"2022-03-04T03:05:28.838Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"894212cbfc91f506fd273a9814625c425477790a35bda34e13a1c167544158","msg":"Adding metadata to asset","time":"2022-03-04T03:07:42.341Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"31be0db77af0f3d74281cb973c0476210574daa00f76b8e2b82065254e4f444f","msg":"Adding metadata to asset","time":"2022-03-04T03:13:53.717Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"c4c00fbd8fa227442a5e7cdecde33b24588494d05a2c50fda8938c6d4b49445a","msg":"Adding metadata to asset","time":"2022-03-04T03:13:53.754Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"ec5d618931d59ca06da2ce203366177cf75650f890062ff07976a52d6e6577546f6b656e","msg":"Adding metadata to asset","time":"2022-03-04T03:15:13.961Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"b1b41a71ea01a911682691ea87ad3822daf5d8f4cb269417fd84181c57655468696e6b49744d617474657273546f6b656e","msg":"Adding metadata to asset","time":"2022-03-04T03:17:36.599Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54797940,"hash":"0ea41d3186a39bed76ee9472fe68efbec47708f0fadbf2f8f26b9d004077e9cf","blockNo":6952988},"rollbackPoint":{"slot":54797932,"hash":"9559334f647a274c3781273ef2305d3552985ef1afdebc9306a5758aa3610f62"},"msg":"Rolling back","time":"2022-03-04T03:23:53.556Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","msg":"Deleted 33 assets","time":"2022-03-04T03:23:54.189Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"87a59599f8f47db431de642329a275cd4b297f21f1517af9db442cee506f705570576f726c64","msg":"Adding metadata to asset","time":"2022-03-04T03:28:44.458Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"06c315525c6f18cd62fc44db5ce0482a3f20de57bf2f5a4ff03b7d164d6f6f6e","msg":"Adding metadata to asset","time":"2022-03-04T03:28:44.468Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"abdaf627f607e9ef12e6d4c9ba5f30fe3802a47275e502c63f2f41fd6269746368636f696e","msg":"Adding metadata to asset","time":"2022-03-04T03:28:44.474Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"ec5d618931d59ca06da2ce203366177cf75650f890062ff07976a52d6e6577546f6b656e","msg":"Adding metadata to asset","time":"2022-03-04T03:29:12.452Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"6f69a35a962c154bab4f2de4d9e116043697c333ade763c2b46fce6e41414441","msg":"Adding metadata to asset","time":"2022-03-04T03:29:23.986Z","v":0}
cardano-graphql  | {"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"HasuraClient","assetId":"2966f762075766ec934945fd7e7da23458991f15ba2a8e930c35af7a417374726f636f696e73","msg":"Adding metadata to asset","time":"2022-03-04T03:29:23.994Z","v":0}
:"ec5d618931d59ca06da2ce203366177cf75650f890062ff07976a52d6e6577546f6b656e","msg":"Adding metadata to asset","time":"2022-03-04T03:29:12.452Z","v":0}

**Comment by malingzhao** [comment]
It can not visited

**Comment by malingzhao** [comment]
It is always rollback

{"name":"cardano-graphql","hostname":"bde06ef4d0fd","pid":1,"level":30,"module":"ChainFollower","tip":{"slot":54798788,"hash":"84cf5f81806b7380259b2be8eacf72a6aeb2b42ec01a3c62a6d17e54acf0c3b1","blockNo":6953027},"rollbackPoint":{"slot":54798786,"hash":"d2ac2379738e706dac493bc89cc5011d8beea4bf34a9dbdf1384fb8977771ade"},"msg":"Rolling back","time":"2022-03-04T03:38:05.313Z","v":0}

**Comment by malingzhao** [comment]
Now it was successful , does I can change it's  graphl api  port

**Comment by rhyslbw** [comment]
> Now it was successful , does I can change it's graphl api port

Do you mean, can you change the API port? If so, yes you can set the ENV `API_PORT` when starting up the stack
