### ISSUE TITLE
Deserialization failed in Transaction because: Invalid cbor: not enough bytes, expect 0 bytes but received 0 bytes.

### ISSUE THREAD

**Issue by mahnunchik** [input-output-hk/cardano-graphql#697]
### Environment

Testnet https://gimbalabs.com/dandelion/endpoints/graphql-api

### Steps to reproduce the bug

Send well formatted transaction with:

```graphql
mutation submitTransaction(
    $transaction: String!
) {
    submitTransaction(transaction: $transaction) {
        hash
    }
}
```

I got the error: `Deserialization failed in Transaction because: Invalid cbor: not enough bytes, expect 0 bytes but received 0 bytes.`

But the transaction is actually send to network: https://explorer.cardano-testnet.iohkdev.io/en/transaction?id=6f5762b2e52cd8f81380e197daae2ab6bded8db34e62346c3434085c0b6b27cd

### What is the expected behavior?

No false negative error.

**Comment by rhyslbw** [comment]
Thanks for the report. Just to confirm, the API is throwing an error, but the tx is being submitted?
