### ISSUE TITLE
Missing Slot Leader Schedule Info

### ISSUE THREAD

**Issue by ZiruiXue** [input-output-hk/cardano-graphql#699]
Hi Team, 
I am working on monitoring the validators' performance. I only found the slot leader who creates the block from the block table. 
I found cardano-node just supports the CLI [command](https://github.com/input-output-hk/cardano-node/pull/3464) to query the slot leader schedules. Will we consider adding the slot leader schedule into cardano-graphql? So we can know the schedules before the block is generated. Thanks for answering.

**Comment by rhyslbw** [comment]
No, there's a couple of issues here. This API is intended to provide a network-wide cache of state using a passive node, whereas the leadership schedule is intended to be local information that only the block producing node operator should know. I can see value in what you're asking, but it's currently not the intent of this API to support such a use-case.
