### ISSUE TITLE
Cannot get collateral for failed transaction

### ISSUE THREAD

**Issue by alecalve** [input-output-hk/cardano-graphql#706]
### Summary

When a transaction fails, its collateral is used to cover fees.

`cardano-graphql` doesn't return collateral for failed transactions.

### Steps to reproduce the bug

Using query:

```graphql
query GetTxCollateral($hash: Hash32Hex) {
    transactions(limit: 1, where: {hash: {_eq: $hash}}) {
        collateral {
            address
            sourceTxHash
            sourceTxIndex
            tokens {
                quantity
            }
            txHash
            value
        }
    }
}
```

Executing it with parameter `5b1ed49e557cde401df3c10d871c3fd852d7d0ca677c296def33ffc2b96e3bde` ([link to explorer](https://cardanoscan.io/transaction/5b1ed49e557cde401df3c10d871c3fd852d7d0ca677c296def33ffc2b96e3bde))

### Actual Result

Response from graphql cardano has no collateral.

### Expected Result

I'd have expected to see a collateral of 4.1337 ADA as shown [here](https://cardanoscan.io/transaction/5b1ed49e557cde401df3c10d871c3fd852d7d0ca677c296def33ffc2b96e3bde?tab=collateral).

### Environment

```
cardano_fullnode_version: "1.34.1"
cardano_fullnode_db_sync_version: "12.0.2"
cardano_fullnode_db_explorer_api_version: "3.1.2"
cardano_fullnode_graphql_version: "6.2.0"
cardano_fullnode_ogmios_version: "v5.2.0-mainnet"
```

### Platform

- [X] Linux (Ubuntu)
- [ ] Linux (Other)
- [ ] macOS
- [ ] Windows

### Runtime

- [ ] Node.js
- [X] Docker

**Comment by alecalve** [comment]
Probably related https://github.com/input-output-hk/cardano-db-sync/issues/1019

**Comment by alecalve** [comment]
Created https://github.com/input-output-hk/cardano-db-sync/issues/1105

**Comment by DevPeter46** [comment]
Talk to Cardano Support on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.

**Comment by CyberCyclone** [comment]
> Talk to Cardano Support on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.
> 
> 

 Beware, phishing site. Don't click it.

**Comment by rhyslbw** [comment]
Thanks @CyberCyclone, deleted
