### ISSUE TITLE
Why do we need Ogmios and Hasura to run GraphQL

### ISSUE THREAD

**Issue by air3ijai** [input-output-hk/cardano-graphql#719]
### Ask a question

Hello, we are trying to setup Cardano API endpoint and found that for this we should use Cardano-GraphQL.

Accordingly to the [Architecture](https://docs.cardano.org/explore-cardano/cardano-architecture), it is about [Node](https://github.com/input-output-hk/cardano-node), [DB-Sync](https://github.com/input-output-hk/cardano-db-sync), Postgres and [GraphQL](https://github.com/input-output-hk/cardano-graphql). There is nothing about [Ogmios](https://github.com/CardanoSolutions/ogmios) and Hasura.

Can someone explain, why do we need these two components or they are optional? We saw errors in GraphQL logs when we used just Node and not Ogmios and same was without Hasura.

Thanks!

**Comment by thatsbrandon** [comment]
If I remember correctly Ogmios enables clients to talk to the cardano-node using JSON/RPC. Since the cardano network coded in Haskell they had to implement Ogmios so Cardano - Haskell types can be converted to JSON.

I honestly would like to not have Ogmios or Hasura but I haven't seen much information on whether that is possible on not

**Comment by rhyslbw** [comment]
Ogmios is indeed our interface for submitting transactions, making state queries, and syncing the chain to manage extra state required for the application. You can see some of the use [here](https://github.com/input-output-hk/cardano-graphql/blob/master/packages/api-cardano-db-hasura/src/CardanoNodeClient.ts)

Hasura is a translator for GraphQL -> SQL queries

**Comment by air3ijai** [comment]
So, we can't run GraphQL without Hasura, but looks like Ogmios is optional when we need just to query data from blockchain?
