### ISSUE TITLE
`@cardano-graphql/client-ts` on NPM needs an update

### ISSUE THREAD

**Issue by siegfried** [input-output-hk/cardano-graphql#735]
### Summary

`coinsPerUtxoWord` was renamed to `coinsPerUtxoSize` whereas the type definition are still using the old one.

### Actual Result

`coinsPerUtxoWord`

### Expected Result

`coinsPerUtxoSize`

### Environment

{
  os: {
    arch: 'x64',
    cpus: { count: 12, model: 'Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz' },
    release: '21.5.0',
    totalMem: 68719476736,
    type: 'Darwin'
  },
  version: '6.2.0'
}

### Platform

- [ ] Linux (Ubuntu)
- [ ] Linux (Other)
- [X] macOS
- [ ] Windows

### Platform version

12.4

### Runtime

- [X] Node.js
- [ ] Docker

### Runtime version

v18.2.0

**Comment by rhyslbw** [comment]
See #730
