### ISSUE TITLE
How do you query a transaction utxo outputs for the datum?

### ISSUE THREAD

**Issue by theuttermost0001** [input-output-hk/cardano-graphql#737]
### Ask a question

Is there a way to get the datum hash for a utxo using GraphQL? Currently a uxto is represented by the TransactionOutput type. However there is no way to get the datum hash.

Does anyone know of a way to get the datum hash?

**Comment by rhyslbw** [comment]
It's been added recently in #740 and will be included in the next release.

https://github.com/input-output-hk/cardano-graphql/blob/28643cef5b63cbc0cc364992fa12e25b4c26a660/packages/api-cardano-db-hasura/schema.graphql#L1557

https://github.com/input-output-hk/cardano-graphql/blob/28643cef5b63cbc0cc364992fa12e25b4c26a660/packages/api-cardano-db-hasura/schema.graphql#L613

**Comment by theuttermost0001** [comment]
> 

Thank you very much!
