### ISSUE TITLE
When will cardano-graphql release an update to support hard forks?

### ISSUE THREAD

**Issue by apufvqsp** [input-output-hk/cardano-graphql#742]
### Ask a question

Because the synchronization of block data is relatively slow, a hard fork upgrade will be carried out at the end of this month. I want to upgrade our nodes in advance. When will the new version of cardano-graphql support this hard fork upgrade be released?

If it's released too late, and we haven't synced to the latest block data by the time of the hard fork, we may have to suspend our ada service,that's too bad

**Comment by rhyslbw** [comment]
>  the synchronization of block data is relatively slow

Are you referring to resyncing the node from genesis? If so, it's not required. The `cardano-db-sync` state, which does require a resync, can be accelerated by using a recent snapshot linked from the [releases page](https://github.com/input-output-hk/cardano-db-sync/releases).

The release is dependent on a new version of `cardano-node`. I'm not in a position to comment on timelines, but you can expect there to be sufficient time to get your instances updated, and the DB resynced.

#730 covers this question, so I'll close this as a duplicate.
