### ISSUE TITLE
when cardano-graphql  support cardano-node 1.35.5?

### ISSUE THREAD

**Issue by lcgogo** [input-output-hk/cardano-graphql#807]
### Ask a question

Now cardano-graphql only support cardano-node 1.35.3

**Comment by lcgogo** [comment]
I tried set CARDANO_NODE_VERSION=1.35.5
```shell
NETWORK=mainnet LOGGER_MIN_SEVERITY=debug CARDANO_NODE_VERSION=1.35.5 docker-compose -f docker-compose.yml up -d
```
but seems the ogmios not receive the CARDANO_NODE_VERSION value

```shell
Building cardano-node-ogmios
Sending build context to Docker daemon  2.314MB
Step 1/40 : ARG CARDANO_NODE_VERSION=1.35.3
Step 2/40 : FROM --platform=${TARGETPLATFORM:-linux/amd64} nixos/nix:2.11.0 as build
2.11.0: Pulling from nixos/nix
40a20fdeab12: Pulling fs layer
aec9f58ab42a: Pulling fs layer
```

**Comment by rhyslbw** [comment]
https://github.com/input-output-hk/cardano-graphql/releases/tag/8.0.0

The Ogmios [Dockerfile](https://github.com/CardanoSolutions/ogmios/blob/master/Dockerfile) looks a bit different now, so it should handle the ENV, mapped to a build arg, correctly now
