### ISSUE TITLE
When cardano-graphql-background is planned to public?

### ISSUE THREAD

**Issue by EV6999** [input-output-hk/cardano-graphql#812]
### Ask a question

When cardano-graphql-background is planned to public? As cardano-graphql 8.0.0 needs it.

https://hub.docker.com/r/inputoutput/cardano-graphql-background/tags

**Comment by rhyslbw** [comment]
The new repositories, both `-background` and [-server](https://hub.docker.com/r/inputoutput/cardano-graphql-server/tags) now have the images available. Please try again.
