### ISSUE TITLE
have no docker images

### ISSUE THREAD

**Issue by zhy827827** [input-output-hk/cardano-graphql#813]
### Ask a question

root@rockx-mainnet-access-ada-node-02:/opt/rockx/cardano-graphql-8.0.0# docker pull cardanosolutions/cardano-node-ogmios:v5.5.8_1.35.5-mainnet
Error response from daemon: manifest for cardanosolutions/cardano-node-ogmios:v5.5.8_1.35.5-mainnet not found: manifest unknown: manifest unknown

**Comment by rhyslbw** [comment]
It will work now if you set `OGMIOS_VERSION` to `v5.6.0`. I'll update the dependency and release a small update to align the versions.
