### ISSUE TITLE
Model Transaction to represent the intitial state, then once it's been included in a block

### ISSUE THREAD

**Issue by rhyslbw** [input-output-hk/cardano-graphql#89]
Currently the `Transaction.block` field is nullable to handle both the initial state of a transaction prior to it being included in a block. It would be better to define a type that extends the base transaction with chain information

**Comment by roccomuso** [comment]
So if "Block" doesn't exists in the returned tx it means it could be an unconfirmed tx?

**Comment by rhyslbw** [comment]
The type supports this, however only transactions included in blocks will be returned at the moment.
