### ISSUE TITLE
Apply views on application boot, if they don't exist

### ISSUE THREAD

**Issue by Sam-Jeston** [input-output-hk/cardano-graphql#90]
To remove the dependance on cardano-explorer, we want cardano-graphql to apply the views it depends on at boot.

retry-as-promised will be used to attempt the application of the views until it succeeds (as we have no control over when the underlying tables will be created by cardano-explorer)

There are 2 potential pitfalls with this approach:
1) cardano-explorer, if it crashes, will fail to start again due to the sql in this file: https://github.com/input-output-hk/cardano-explorer/blob/master/schema/migration-1-0002-20190912.sql
2) We have no way of migrating the views, outside of explicitly dropping the database such that the `create view if not exists` statements execute

**Comment by rhyslbw** [comment]
Closed in favour of merging upstream https://github.com/input-output-hk/cardano-explorer/pull/172
